--  ETCS on-board (EVC)
--  Random valid packets and round trips, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with ETCS_Variables; use ETCS_Variables;
with ETCS_Track_Packets.P0;
with ETCS_Track_Packets.P2;
with ETCS_Track_Packets.P3;
with ETCS_Track_Packets.P5;
with ETCS_Track_Packets.P12;
with ETCS_Track_Packets.P15;
with ETCS_Track_Packets.P21;
with ETCS_Track_Packets.P27;
with ETCS_Track_Packets.P41;
with ETCS_Track_Packets.P44;
with ETCS_Track_Packets.P65;
with ETCS_Track_Packets.P73;
with ETCS_Track_Packets.P136;
with ETCS_Track_Packets.P255;
with ETCS_Train_Packets.P0;
with ETCS_Train_Packets.P1;
with ETCS_Train_Packets.P2;
with ETCS_Train_Packets.P4;
with ETCS_Train_Packets.P5;
with ETCS_Train_Packets.P44;

package body ETCS_Language_Random is

   pragma Warnings (Off, "formal parameter ""P"" is not referenced");

   use Interfaces;
   use ETCS_Bits;

   package Track_P0_Pkg renames ETCS_Track_Packets.P0;
   package Track_P2_Pkg renames ETCS_Track_Packets.P2;
   package Track_P3_Pkg renames ETCS_Track_Packets.P3;
   package Track_P5_Pkg renames ETCS_Track_Packets.P5;
   package Track_P12_Pkg renames ETCS_Track_Packets.P12;
   package Track_P15_Pkg renames ETCS_Track_Packets.P15;
   package Track_P21_Pkg renames ETCS_Track_Packets.P21;
   package Track_P27_Pkg renames ETCS_Track_Packets.P27;
   package Track_P41_Pkg renames ETCS_Track_Packets.P41;
   package Track_P44_Pkg renames ETCS_Track_Packets.P44;
   package Track_P65_Pkg renames ETCS_Track_Packets.P65;
   package Track_P73_Pkg renames ETCS_Track_Packets.P73;
   package Track_P136_Pkg renames ETCS_Track_Packets.P136;
   package Track_P255_Pkg renames ETCS_Track_Packets.P255;
   package Train_P0_Pkg renames ETCS_Train_Packets.P0;
   package Train_P1_Pkg renames ETCS_Train_Packets.P1;
   package Train_P2_Pkg renames ETCS_Train_Packets.P2;
   package Train_P4_Pkg renames ETCS_Train_Packets.P4;
   package Train_P5_Pkg renames ETCS_Train_Packets.P5;
   package Train_P44_Pkg renames ETCS_Train_Packets.P44;

   State      : Unsigned_32 := 1;
   Value_Mode : Value_Mode_T := Random_Values;
   Count_Mode : Count_Mode_T := Random_Items;

   type Seen_T is array (Boolean) of Boolean;
   Conditions : array (1 .. Condition_Count) of Seen_T :=
     (others => (others => False));
   type Loop_Seen_T is array (Items_T) of Boolean;
   Loops : array (1 .. Loop_Count) of Loop_Seen_T :=
     (others => (others => False));

   function Next return Unsigned_32 is
   begin
      State := State xor Shift_Left (State, 13);
      State := State xor Shift_Right (State, 17);
      State := State xor Shift_Left (State, 5);
      return State;
   end Next;

   --  Uniform in Low .. High
   function Uniform (Low, High : Unsigned_64) return Unsigned_64 is
      R : constant Unsigned_64 :=
        Shift_Left (Unsigned_64 (Next), 32) or Unsigned_64 (Next);
   begin
      if High - Low = Unsigned_64'Last then
         return R;
      end if;
      return Low + R mod (High - Low + 1);
   end Uniform;

   procedure Reset (Seed : Unsigned_32) is
   begin
      State := (if Seed = 0 then 1 else Seed);
   end Reset;

   procedure Clear_Coverage is
   begin
      Conditions := (others => (others => False));
      Loops := (others => (others => False));
   end Clear_Coverage;

   procedure Cover (C : Natural; Value : Boolean) is
   begin
      Conditions (C + 1) (Value) := True;
   end Cover;

   function Condition_Seen (C : Positive; Value : Boolean) return Boolean
   is (Conditions (C) (Value));

   function Loop_Seen (L : Positive; Items : Items_T) return Boolean
   is (Loops (L) (Items));

   --  The count of the loop Id (0 based) of maximum Max at Depth
   function Count (Max : Natural; Depth : Positive; Id : Natural)
     return Unsigned_64
   is
      N : Natural;
   begin
      case Count_Mode is
         when No_Items => N := 0;
         when One_Item => N := 1;
         when Max_Items => N := (if Depth = 1 then Max else 1);
         when Random_Items =>
            case Uniform (1, 10) is
               when 1 .. 3 => N := 0;
               when 4 .. 6 => N := 1;
               when 7 => N := (if Depth = 1 then Max else 2);
               when others =>
                  N := Natural (Uniform (0, Unsigned_64
                    (Natural'Min (Max, (if Depth = 1 then 8 else 3)))));
            end case;
      end case;
      N := Natural'Min (N, Max);
      Loops (Id + 1) ((if N = 0 then None elsif N = Max then Maximum
                       elsif N = 1 then One else One)) := True;
      return Unsigned_64 (N);
   end Count;

   --  A length in bits for raw data
   function Raw_Count (Max : Natural) return Unsigned_64 is
     (case Count_Mode is
         when No_Items => 0,
         when One_Item => 1,
         when Max_Items => Unsigned_64 (Max),
         when Random_Items => Uniform (0, Unsigned_64 (Max)));

   procedure Random_Bits (Data : out Byte_Array; Bits : Natural) is
   begin
      Data := (others => 0);
      for I in 0 .. Bits - 1 loop
         if Uniform (0, 1) = 1 then
            Data (Data'First + I / 8) := Data (Data'First + I / 8)
              or Shift_Left (1, 7 - I mod 8);
         end if;
      end loop;
   end Random_Bits;

   type U64_Array is array (Positive range <>) of Unsigned_64;

   --  A code of Low .. High or of Specials, by the value mode
   function Choose (Low, High : Unsigned_64; Specials : U64_Array)
     return Unsigned_64
   is
   begin
      if Specials'Length > 0 and then Value_Mode = Random_Values
        and then Uniform (1, 5) = 1
      then
         return Specials (Specials'First + Natural (Uniform
           (0, Unsigned_64 (Specials'Length - 1))));
      end if;
      case Value_Mode is
         when Min_Values => return Low;
         when Max_Values => return High;
         when Random_Values =>
            case Uniform (1, 10) is
               when 1 => return Low;
               when 2 => return High;
               when others => return Uniform (Low, High);
            end case;
      end case;
   end Choose;

   --  A code of a signed variable of Bits bits in Low .. High
   function Choose_Signed (Low, High : Long_Long_Integer;
                           Bits      : Positive) return Unsigned_64
   is
      X : constant Long_Long_Integer :=
        (case Value_Mode is
            when Min_Values => Low,
            when Max_Values => High,
            when Random_Values =>
              Low + Long_Long_Integer
                      (Uniform (0, Unsigned_64 (High - Low))));
   begin
      return (if X < 0 then Unsigned_64 (X + 2 ** Bits)
              else Unsigned_64 (X));
   end Choose_Signed;

   --  A valid code of the variable, by the value mode
   function Pick (Var : Variable_T) return Unsigned_64 is
   begin
      case Var is
         when A_NVMAXREDADH1 =>
            return Choose (0, 60, (1 => 61, 2 => 62, 3 => 63));
         when A_NVMAXREDADH2 =>
            return Choose (0, 60, (1 => 61, 2 => 62, 3 => 63));
         when A_NVMAXREDADH3 =>
            return Choose (0, 60, (1 => 61, 2 => 62, 3 => 63));
         when A_NVP12 =>
            return Choose (0, 63, (1 .. 0 => 0));
         when A_NVP23 =>
            return Choose (0, 63, (1 .. 0 => 0));
         when D_DP =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_EMERGENCYSTOP =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_ENDTIMERSTARTLOC =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_GRADIENT =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_LEVELTR =>
            return Choose (0, 32766, (1 => 32767));
         when D_LINK =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_LRBG =>
            return Choose (0, 32766, (1 => 32767));
         when D_NVOVTRP =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_NVPOTRP =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_NVROLL =>
            return Choose (0, 32766, (1 => 32767));
         when D_NVSTFF =>
            return Choose (0, 32766, (1 => 32767));
         when D_OL =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_REF =>
            return Choose_Signed (-32768, 32767, 16);
         when D_SECTIONTIMERSTOPLOC =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_SR =>
            return Choose (0, 32766, (1 => 32767));
         when D_STARTOL =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_STATIC =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_TAFDISPLAY =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_TEXTDISPLAY =>
            return Choose (0, 32766, (1 => 32767));
         when D_TSR =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when D_VALIDNV =>
            return Choose (0, 32766, (1 => 32767));
         when G_A =>
            return Choose (0, 254, (1 => 255));
         when L_ACKLEVELTR =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when L_DOUBTOVER =>
            return Choose (0, 32766, (1 => 32767));
         when L_DOUBTUNDER =>
            return Choose (0, 32766, (1 => 32767));
         when L_ENDSECTION =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when L_MESSAGE =>
            return Choose (0, 1023, (1 .. 0 => 0));
         when L_NVKRINT =>
            return Choose (0, 31, (1 .. 0 => 0));
         when L_PACKET =>
            return Choose (0, 8191, (1 .. 0 => 0));
         when L_SECTION =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when L_TAFDISPLAY =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when L_TEXT =>
            return Choose (0, 255, (1 .. 0 => 0));
         when L_TEXTDISPLAY =>
            return Choose (0, 32766, (1 => 32767));
         when L_TRAININT =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when L_TSR =>
            return Choose (0, 32767, (1 .. 0 => 0));
         when M_ACK =>
            return Choose (0, 1, (1 .. 0 => 0));
         when M_DUP =>
            return Choose (0, 2, (1 .. 0 => 0));
         when M_ERROR =>
            return Choose (0, 10, (1 .. 0 => 0));
         when M_LEVEL =>
            return Choose (0, 3, (1 => 1));
         when M_LEVELTEXTDISPLAY =>
            return Choose (0, 4, (1 => 1));
         when M_LEVELTR =>
            return Choose (0, 3, (1 => 1));
         when M_MCOUNT =>
            return Choose (0, 253, (1 => 254, 2 => 255));
         when M_MODE =>
            return Choose (0, 17, (1 .. 0 => 0));
         when M_MODETEXTDISPLAY =>
            return Choose (0, 15, (1 .. 0 => 0));
         when M_NVAVADH =>
            return Choose (0, 20, (1 .. 0 => 0));
         when M_NVCONTACT =>
            return Choose (0, 2, (1 .. 0 => 0));
         when M_NVDERUN =>
            return Choose (0, 1, (1 .. 0 => 0));
         when M_NVEBCL =>
            return Choose (0, 9, (1 .. 0 => 0));
         when M_NVKRINT =>
            return Choose (0, 31, (1 .. 0 => 0));
         when M_NVKTINT =>
            return Choose (0, 31, (1 .. 0 => 0));
         when M_NVKVINT =>
            return Choose (0, 127, (1 .. 0 => 0));
         when M_VERSION =>
            return Choose (0, 127, (1 .. 0 => 0));
         when NC_CDDIFF =>
            return Choose (0, 10, (1 .. 0 => 0));
         when NC_DIFF =>
            return Choose (0, 2, (1 .. 0 => 0));
         when NID_BG =>
            return Choose (0, 16382, (1 => 16383));
         when NID_C =>
            return Choose (0, 1023, (1 .. 0 => 0));
         when NID_EM =>
            return Choose (0, 15, (1 .. 0 => 0));
         when NID_ENGINE =>
            return Choose (0, 16777215, (1 .. 0 => 0));
         when NID_MESSAGE =>
            return Choose (0, 255, (1 .. 0 => 0));
         when NID_NTC =>
            return Choose (0, 255, (1 .. 0 => 0));
         when NID_OPERATIONAL =>
            return Choose (0, 4294967295, (1 .. 0 => 0));
         when NID_PACKET =>
            return Choose (0, 255, (1 .. 0 => 0));
         when NID_RBC =>
            return Choose (0, 16382, (1 => 16383));
         when NID_TEXTMESSAGE =>
            return Choose (0, 255, (1 .. 0 => 0));
         when NID_TSR =>
            return Choose (0, 255, (1 .. 0 => 0));
         when NID_VBCMK =>
            return Choose (0, 63, (1 .. 0 => 0));
         when NID_XUSER =>
            return Choose (0, 511, (1 => 102));
         when N_ITER =>
            return Choose (0, 31, (1 .. 0 => 0));
         when N_PIG =>
            return Choose (0, 7, (1 .. 0 => 0));
         when N_TOTAL =>
            return Choose (0, 7, (1 .. 0 => 0));
         when Q_CONFTEXTDISPLAY =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_DANGERPOINT =>
            return Choose (0, 1, (1 => 1));
         when Q_DESK =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_DIFF =>
            return Choose (0, 2, (1 => 0, 2 => 1, 3 => 2));
         when Q_DIR =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_DIRLRBG =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_DIRTRAIN =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_DLRBG =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_EMERGENCYSTOP =>
            return Choose (0, 3, (1 .. 0 => 0));
         when Q_ENDTIMER =>
            return Choose (0, 1, (1 => 1));
         when Q_FRONT =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_GDIR =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_INFILL =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_INTEGRITY =>
            return Choose (0, 3, (1 => 1, 2 => 2));
         when Q_LINK =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_LINKORIENTATION =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_LINKREACTION =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_LOCACC =>
            return Choose (0, 63, (1 .. 0 => 0));
         when Q_MARQSTREASON =>
            return Choose (0, 31, (1 .. 0 => 0));
         when Q_MEDIA =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_NEWCOUNTRY =>
            return Choose (0, 1, (1 => 1));
         when Q_NVDRIVER_ADHES =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_NVEMRRLS =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_NVGUIPERM =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_NVINHSMICPERM =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_NVKINT =>
            return Choose (0, 1, (1 => 1));
         when Q_NVKVINTSET =>
            return Choose (0, 1, (1 => 1));
         when Q_NVLOCACC =>
            return Choose (0, 63, (1 .. 0 => 0));
         when Q_NVSBFBPERM =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_NVSBTSMPERM =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_ORIENTATION =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_OVERLAP =>
            return Choose (0, 1, (1 => 1));
         when Q_SCALE =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_SECTIONTIMER =>
            return Choose (0, 1, (1 => 1));
         when Q_STATUSLRBG =>
            return Choose (0, 2, (1 .. 0 => 0));
         when Q_TEXTCLASS =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_TEXTCONFIRM =>
            return Choose (0, 3, (1 => 0, 2 => 1));
         when Q_TEXTDISPLAY =>
            return Choose (0, 1, (1 .. 0 => 0));
         when Q_TEXTREPORT =>
            return Choose (0, 1, (1 => 1));
         when Q_UPDOWN =>
            return Choose (0, 1, (1 .. 0 => 0));
         when T_EMA =>
            return Choose (0, 1022, (1 => 1023));
         when T_ENDTIMER =>
            return Choose (0, 1022, (1 => 1023));
         when T_NVCONTACT =>
            return Choose (0, 254, (1 => 255));
         when T_NVOVTRP =>
            return Choose (0, 255, (1 .. 0 => 0));
         when T_OL =>
            return Choose (0, 1022, (1 => 1023));
         when T_SECTIONTIMER =>
            return Choose (0, 1022, (1 => 1023));
         when T_TEXTDISPLAY =>
            return Choose (0, 1022, (1 => 1023));
         when T_TRAIN =>
            return Choose (0, 4294967294, (1 => 4294967295));
         when V_DIFF =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_EMA =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_MAIN =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVALLOWOVTRP =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVKVINT =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVLIMSUPERV =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVONSIGHT =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVREL =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVSHUNT =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVSTFF =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVSUPOVTRP =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_NVUNFIT =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_RELEASEDP =>
            return Choose (0, 120, (1 => 126, 2 => 127));
         when V_RELEASEOL =>
            return Choose (0, 120, (1 => 126, 2 => 127));
         when V_SM =>
            return Choose (0, 120, (1 .. 0 => 0));
         when V_STATIC =>
            return Choose (0, 120, (1 => 127));
         when V_TRAIN =>
            return Choose (0, 120, (1 => 127));
         when V_TSR =>
            return Choose (0, 120, (1 .. 0 => 0));
         when X_TEXT =>
            return Choose (0, 255, (1 .. 0 => 0));
      end case;
   end Pick;

   procedure Fill_Track_P0 (P : out Track_P0_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P0_Pkg.NID);
      P.NID_VBCMK := To_NID_VBCMK (Pick (NID_VBCMK));
   end Fill_Track_P0;

   procedure Fill_Track_P2 (P : out Track_P2_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P2_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.M_VERSION := To_M_VERSION (Pick (M_VERSION));
   end Fill_Track_P2;

   procedure Fill_Track_P3 (P : out Track_P3_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P3_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.D_VALIDNV := To_D_VALIDNV (Pick (D_VALIDNV));
      P.NID_C := To_NID_C (Pick (NID_C));
      P.N_ITER := To_N_ITER (Count (31, 1, 0));
      for I1 in 1 .. Natural (P.N_ITER) loop
         P.NID_C_List (I1) := To_NID_C (Pick (NID_C));
      end loop;
      P.V_NVSHUNT := To_V_NVSHUNT (Pick (V_NVSHUNT));
      P.V_NVSTFF := To_V_NVSTFF (Pick (V_NVSTFF));
      P.V_NVONSIGHT := To_V_NVONSIGHT (Pick (V_NVONSIGHT));
      P.V_NVLIMSUPERV := To_V_NVLIMSUPERV (Pick (V_NVLIMSUPERV));
      P.V_NVUNFIT := To_V_NVUNFIT (Pick (V_NVUNFIT));
      P.V_NVREL := To_V_NVREL (Pick (V_NVREL));
      P.D_NVROLL := To_D_NVROLL (Pick (D_NVROLL));
      P.Q_NVSBTSMPERM := To_Q_NVSBTSMPERM (Pick (Q_NVSBTSMPERM));
      P.Q_NVEMRRLS := To_Q_NVEMRRLS (Pick (Q_NVEMRRLS));
      P.Q_NVGUIPERM := To_Q_NVGUIPERM (Pick (Q_NVGUIPERM));
      P.Q_NVSBFBPERM := To_Q_NVSBFBPERM (Pick (Q_NVSBFBPERM));
      P.Q_NVINHSMICPERM := To_Q_NVINHSMICPERM (Pick (Q_NVINHSMICPERM));
      P.V_NVALLOWOVTRP := To_V_NVALLOWOVTRP (Pick (V_NVALLOWOVTRP));
      P.V_NVSUPOVTRP := To_V_NVSUPOVTRP (Pick (V_NVSUPOVTRP));
      P.D_NVOVTRP := To_D_NVOVTRP (Pick (D_NVOVTRP));
      P.T_NVOVTRP := To_T_NVOVTRP (Pick (T_NVOVTRP));
      P.D_NVPOTRP := To_D_NVPOTRP (Pick (D_NVPOTRP));
      P.M_NVCONTACT := To_M_NVCONTACT (Pick (M_NVCONTACT));
      P.T_NVCONTACT := To_T_NVCONTACT (Pick (T_NVCONTACT));
      P.M_NVDERUN := To_M_NVDERUN (Pick (M_NVDERUN));
      P.D_NVSTFF := To_D_NVSTFF (Pick (D_NVSTFF));
      P.Q_NVDRIVER_ADHES := To_Q_NVDRIVER_ADHES (Pick (Q_NVDRIVER_ADHES));
      P.A_NVMAXREDADH1 := To_A_NVMAXREDADH1 (Pick (A_NVMAXREDADH1));
      P.A_NVMAXREDADH2 := To_A_NVMAXREDADH2 (Pick (A_NVMAXREDADH2));
      P.A_NVMAXREDADH3 := To_A_NVMAXREDADH3 (Pick (A_NVMAXREDADH3));
      P.Q_NVLOCACC := To_Q_NVLOCACC (Pick (Q_NVLOCACC));
      P.M_NVAVADH := To_M_NVAVADH (Pick (M_NVAVADH));
      P.M_NVEBCL := To_M_NVEBCL (Pick (M_NVEBCL));
      P.Q_NVKINT := To_Q_NVKINT (Pick (Q_NVKINT));
      P.Has_Q_NVKVINTSET := P.Q_NVKINT = 1;
      Cover (6, P.Has_Q_NVKVINTSET);
      if P.Has_Q_NVKVINTSET then
         P.Q_NVKVINTSET := To_Q_NVKVINTSET (Pick (Q_NVKVINTSET));
         P.Has_A_NVP12 := P.Q_NVKVINTSET = 1;
         Cover (0, P.Has_A_NVP12);
         if P.Has_A_NVP12 then
            P.A_NVP12 := To_A_NVP12 (Pick (A_NVP12));
            P.A_NVP23 := To_A_NVP23 (Pick (A_NVP23));
         end if;
         P.V_NVKVINT := To_V_NVKVINT (Pick (V_NVKVINT));
         P.M_NVKVINT := To_M_NVKVINT (Pick (M_NVKVINT));
         P.Has_M_NVKVINT_P23 := P.Q_NVKVINTSET = 1;
         Cover (1, P.Has_M_NVKVINT_P23);
         if P.Has_M_NVKVINT_P23 then
            P.M_NVKVINT_P23 := To_M_NVKVINT (Pick (M_NVKVINT));
         end if;
         P.N_ITER_KV := To_N_ITER (Count (31, 1, 1));
         for I1 in 1 .. Natural (P.N_ITER_KV) loop
            declare
               E1 : Track_P3_Pkg.V_NVKVINT_Item renames P.V_NVKVINT_List (I1);
            begin
               E1.V_NVKVINT := To_V_NVKVINT (Pick (V_NVKVINT));
               E1.M_NVKVINT := To_M_NVKVINT (Pick (M_NVKVINT));
               E1.Has_M_NVKVINT_P23 := P.Q_NVKVINTSET = 1;
               Cover (2, E1.Has_M_NVKVINT_P23);
               if E1.Has_M_NVKVINT_P23 then
                  E1.M_NVKVINT_P23 := To_M_NVKVINT (Pick (M_NVKVINT));
               end if;
            end;
         end loop;
         P.N_ITER_SET := To_N_ITER (Count (31, 1, 3));
         for I1 in 1 .. Natural (P.N_ITER_SET) loop
            declare
               E1 : Track_P3_Pkg.Q_NVKVINTSET_Item
                 renames P.Q_NVKVINTSET_List (I1);
            begin
               E1.Q_NVKVINTSET := To_Q_NVKVINTSET (Pick (Q_NVKVINTSET));
               E1.Has_A_NVP12 := E1.Q_NVKVINTSET = 1;
               Cover (3, E1.Has_A_NVP12);
               if E1.Has_A_NVP12 then
                  E1.A_NVP12 := To_A_NVP12 (Pick (A_NVP12));
                  E1.A_NVP23 := To_A_NVP23 (Pick (A_NVP23));
               end if;
               E1.V_NVKVINT := To_V_NVKVINT (Pick (V_NVKVINT));
               E1.M_NVKVINT := To_M_NVKVINT (Pick (M_NVKVINT));
               E1.Has_M_NVKVINT_P23 := E1.Q_NVKVINTSET = 1;
               Cover (4, E1.Has_M_NVKVINT_P23);
               if E1.Has_M_NVKVINT_P23 then
                  E1.M_NVKVINT_P23 := To_M_NVKVINT (Pick (M_NVKVINT));
               end if;
               E1.N_ITER := To_N_ITER (Count (31, 2, 2));
               for I2 in 1 .. Natural (E1.N_ITER) loop
                  declare
                     E2 : Track_P3_Pkg.V_NVKVINT_Item_2
                       renames E1.V_NVKVINT_List (I2);
                  begin
                     E2.V_NVKVINT := To_V_NVKVINT (Pick (V_NVKVINT));
                     E2.M_NVKVINT := To_M_NVKVINT (Pick (M_NVKVINT));
                     E2.Has_M_NVKVINT_P23 := E1.Q_NVKVINTSET = 1;
                     Cover (5, E2.Has_M_NVKVINT_P23);
                     if E2.Has_M_NVKVINT_P23 then
                        E2.M_NVKVINT_P23 := To_M_NVKVINT (Pick (M_NVKVINT));
                     end if;
                  end;
               end loop;
            end;
         end loop;
         P.L_NVKRINT := To_L_NVKRINT (Pick (L_NVKRINT));
         P.M_NVKRINT := To_M_NVKRINT (Pick (M_NVKRINT));
         P.N_ITER_KR := To_N_ITER (Count (31, 1, 4));
         for I1 in 1 .. Natural (P.N_ITER_KR) loop
            declare
               E1 : Track_P3_Pkg.L_NVKRINT_Item renames P.L_NVKRINT_List (I1);
            begin
               E1.L_NVKRINT := To_L_NVKRINT (Pick (L_NVKRINT));
               E1.M_NVKRINT := To_M_NVKRINT (Pick (M_NVKRINT));
            end;
         end loop;
         P.M_NVKTINT := To_M_NVKTINT (Pick (M_NVKTINT));
      end if;
   end Fill_Track_P3;

   procedure Fill_Track_P5 (P : out Track_P5_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P5_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.D_LINK := To_D_LINK (Pick (D_LINK));
      P.Q_NEWCOUNTRY := To_Q_NEWCOUNTRY (Pick (Q_NEWCOUNTRY));
      P.Has_NID_C := P.Q_NEWCOUNTRY = 1;
      Cover (7, P.Has_NID_C);
      if P.Has_NID_C then
         P.NID_C := To_NID_C (Pick (NID_C));
      end if;
      P.NID_BG := To_NID_BG (Pick (NID_BG));
      P.Q_LINKORIENTATION := To_Q_LINKORIENTATION (Pick (Q_LINKORIENTATION));
      P.Q_LINKREACTION := To_Q_LINKREACTION (Pick (Q_LINKREACTION));
      P.Q_LOCACC := To_Q_LOCACC (Pick (Q_LOCACC));
      P.N_ITER := To_N_ITER (Count (31, 1, 5));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : Track_P5_Pkg.D_LINK_Item renames P.D_LINK_List (I1);
         begin
            E1.D_LINK := To_D_LINK (Pick (D_LINK));
            E1.Q_NEWCOUNTRY := To_Q_NEWCOUNTRY (Pick (Q_NEWCOUNTRY));
            E1.Has_NID_C := E1.Q_NEWCOUNTRY = 1;
            Cover (8, E1.Has_NID_C);
            if E1.Has_NID_C then
               E1.NID_C := To_NID_C (Pick (NID_C));
            end if;
            E1.NID_BG := To_NID_BG (Pick (NID_BG));
            E1.Q_LINKORIENTATION :=
              To_Q_LINKORIENTATION (Pick (Q_LINKORIENTATION));
            E1.Q_LINKREACTION := To_Q_LINKREACTION (Pick (Q_LINKREACTION));
            E1.Q_LOCACC := To_Q_LOCACC (Pick (Q_LOCACC));
         end;
      end loop;
   end Fill_Track_P5;

   procedure Fill_Track_P12 (P : out Track_P12_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P12_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.V_MAIN := To_V_MAIN (Pick (V_MAIN));
      P.V_EMA := To_V_EMA (Pick (V_EMA));
      P.T_EMA := To_T_EMA (Pick (T_EMA));
      P.N_ITER := To_N_ITER (Count (31, 1, 6));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : Track_P12_Pkg.L_SECTION_Item renames P.L_SECTION_List (I1);
         begin
            E1.L_SECTION := To_L_SECTION (Pick (L_SECTION));
            E1.Q_SECTIONTIMER := To_Q_SECTIONTIMER (Pick (Q_SECTIONTIMER));
            E1.Has_T_SECTIONTIMER := E1.Q_SECTIONTIMER = 1;
            Cover (9, E1.Has_T_SECTIONTIMER);
            if E1.Has_T_SECTIONTIMER then
               E1.T_SECTIONTIMER := To_T_SECTIONTIMER (Pick (T_SECTIONTIMER));
               E1.D_SECTIONTIMERSTOPLOC :=
                 To_D_SECTIONTIMERSTOPLOC (Pick (D_SECTIONTIMERSTOPLOC));
            end if;
         end;
      end loop;
      P.L_ENDSECTION := To_L_ENDSECTION (Pick (L_ENDSECTION));
      P.Q_SECTIONTIMER := To_Q_SECTIONTIMER (Pick (Q_SECTIONTIMER));
      P.Has_T_SECTIONTIMER := P.Q_SECTIONTIMER = 1;
      Cover (10, P.Has_T_SECTIONTIMER);
      if P.Has_T_SECTIONTIMER then
         P.T_SECTIONTIMER := To_T_SECTIONTIMER (Pick (T_SECTIONTIMER));
         P.D_SECTIONTIMERSTOPLOC :=
           To_D_SECTIONTIMERSTOPLOC (Pick (D_SECTIONTIMERSTOPLOC));
      end if;
      P.Q_ENDTIMER := To_Q_ENDTIMER (Pick (Q_ENDTIMER));
      P.Has_T_ENDTIMER := P.Q_ENDTIMER = 1;
      Cover (11, P.Has_T_ENDTIMER);
      if P.Has_T_ENDTIMER then
         P.T_ENDTIMER := To_T_ENDTIMER (Pick (T_ENDTIMER));
         P.D_ENDTIMERSTARTLOC :=
           To_D_ENDTIMERSTARTLOC (Pick (D_ENDTIMERSTARTLOC));
      end if;
      P.Q_DANGERPOINT := To_Q_DANGERPOINT (Pick (Q_DANGERPOINT));
      P.Has_D_DP := P.Q_DANGERPOINT = 1;
      Cover (12, P.Has_D_DP);
      if P.Has_D_DP then
         P.D_DP := To_D_DP (Pick (D_DP));
         P.V_RELEASEDP := To_V_RELEASEDP (Pick (V_RELEASEDP));
      end if;
      P.Q_OVERLAP := To_Q_OVERLAP (Pick (Q_OVERLAP));
      P.Has_D_STARTOL := P.Q_OVERLAP = 1;
      Cover (13, P.Has_D_STARTOL);
      if P.Has_D_STARTOL then
         P.D_STARTOL := To_D_STARTOL (Pick (D_STARTOL));
         P.T_OL := To_T_OL (Pick (T_OL));
         P.D_OL := To_D_OL (Pick (D_OL));
         P.V_RELEASEOL := To_V_RELEASEOL (Pick (V_RELEASEOL));
      end if;
   end Fill_Track_P12;

   procedure Fill_Track_P15 (P : out Track_P15_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P15_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.V_EMA := To_V_EMA (Pick (V_EMA));
      P.T_EMA := To_T_EMA (Pick (T_EMA));
      P.N_ITER := To_N_ITER (Count (31, 1, 7));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : Track_P15_Pkg.L_SECTION_Item renames P.L_SECTION_List (I1);
         begin
            E1.L_SECTION := To_L_SECTION (Pick (L_SECTION));
            E1.Q_SECTIONTIMER := To_Q_SECTIONTIMER (Pick (Q_SECTIONTIMER));
            E1.Has_T_SECTIONTIMER := E1.Q_SECTIONTIMER = 1;
            Cover (14, E1.Has_T_SECTIONTIMER);
            if E1.Has_T_SECTIONTIMER then
               E1.T_SECTIONTIMER := To_T_SECTIONTIMER (Pick (T_SECTIONTIMER));
               E1.D_SECTIONTIMERSTOPLOC :=
                 To_D_SECTIONTIMERSTOPLOC (Pick (D_SECTIONTIMERSTOPLOC));
            end if;
         end;
      end loop;
      P.L_ENDSECTION := To_L_ENDSECTION (Pick (L_ENDSECTION));
      P.Q_SECTIONTIMER := To_Q_SECTIONTIMER (Pick (Q_SECTIONTIMER));
      P.Has_T_SECTIONTIMER := P.Q_SECTIONTIMER = 1;
      Cover (15, P.Has_T_SECTIONTIMER);
      if P.Has_T_SECTIONTIMER then
         P.T_SECTIONTIMER := To_T_SECTIONTIMER (Pick (T_SECTIONTIMER));
         P.D_SECTIONTIMERSTOPLOC :=
           To_D_SECTIONTIMERSTOPLOC (Pick (D_SECTIONTIMERSTOPLOC));
      end if;
      P.Q_ENDTIMER := To_Q_ENDTIMER (Pick (Q_ENDTIMER));
      P.Has_T_ENDTIMER := P.Q_ENDTIMER = 1;
      Cover (16, P.Has_T_ENDTIMER);
      if P.Has_T_ENDTIMER then
         P.T_ENDTIMER := To_T_ENDTIMER (Pick (T_ENDTIMER));
         P.D_ENDTIMERSTARTLOC :=
           To_D_ENDTIMERSTARTLOC (Pick (D_ENDTIMERSTARTLOC));
      end if;
      P.Q_DANGERPOINT := To_Q_DANGERPOINT (Pick (Q_DANGERPOINT));
      P.Has_D_DP := P.Q_DANGERPOINT = 1;
      Cover (17, P.Has_D_DP);
      if P.Has_D_DP then
         P.D_DP := To_D_DP (Pick (D_DP));
         P.V_RELEASEDP := To_V_RELEASEDP (Pick (V_RELEASEDP));
      end if;
      P.Q_OVERLAP := To_Q_OVERLAP (Pick (Q_OVERLAP));
      P.Has_D_STARTOL := P.Q_OVERLAP = 1;
      Cover (18, P.Has_D_STARTOL);
      if P.Has_D_STARTOL then
         P.D_STARTOL := To_D_STARTOL (Pick (D_STARTOL));
         P.T_OL := To_T_OL (Pick (T_OL));
         P.D_OL := To_D_OL (Pick (D_OL));
         P.V_RELEASEOL := To_V_RELEASEOL (Pick (V_RELEASEOL));
      end if;
   end Fill_Track_P15;

   procedure Fill_Track_P21 (P : out Track_P21_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P21_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.D_GRADIENT := To_D_GRADIENT (Pick (D_GRADIENT));
      P.Q_GDIR := To_Q_GDIR (Pick (Q_GDIR));
      P.G_A := To_G_A (Pick (G_A));
      P.N_ITER := To_N_ITER (Count (31, 1, 8));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : Track_P21_Pkg.D_GRADIENT_Item renames P.D_GRADIENT_List (I1);
         begin
            E1.D_GRADIENT := To_D_GRADIENT (Pick (D_GRADIENT));
            E1.Q_GDIR := To_Q_GDIR (Pick (Q_GDIR));
            E1.G_A := To_G_A (Pick (G_A));
         end;
      end loop;
   end Fill_Track_P21;

   procedure Fill_Track_P27 (P : out Track_P27_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P27_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.D_STATIC := To_D_STATIC (Pick (D_STATIC));
      P.V_STATIC := To_V_STATIC (Pick (V_STATIC));
      P.Q_FRONT := To_Q_FRONT (Pick (Q_FRONT));
      P.N_ITER := To_N_ITER (Count (31, 1, 9));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : Track_P27_Pkg.Q_DIFF_Item renames P.Q_DIFF_List (I1);
         begin
            E1.Q_DIFF := To_Q_DIFF (Pick (Q_DIFF));
            E1.Has_NC_CDDIFF := E1.Q_DIFF = 0;
            Cover (19, E1.Has_NC_CDDIFF);
            if E1.Has_NC_CDDIFF then
               E1.NC_CDDIFF := To_NC_CDDIFF (Pick (NC_CDDIFF));
            end if;
            E1.Has_NC_DIFF := E1.Q_DIFF in 1 | 2;
            Cover (20, E1.Has_NC_DIFF);
            if E1.Has_NC_DIFF then
               E1.NC_DIFF := To_NC_DIFF (Pick (NC_DIFF));
            end if;
            E1.V_DIFF := To_V_DIFF (Pick (V_DIFF));
         end;
      end loop;
      P.N_ITER_K := To_N_ITER (Count (31, 1, 11));
      for I1 in 1 .. Natural (P.N_ITER_K) loop
         declare
            E1 : Track_P27_Pkg.D_STATIC_Item renames P.D_STATIC_List (I1);
         begin
            E1.D_STATIC := To_D_STATIC (Pick (D_STATIC));
            E1.V_STATIC := To_V_STATIC (Pick (V_STATIC));
            E1.Q_FRONT := To_Q_FRONT (Pick (Q_FRONT));
            E1.N_ITER := To_N_ITER (Count (31, 2, 10));
            for I2 in 1 .. Natural (E1.N_ITER) loop
               declare
                  E2 : Track_P27_Pkg.Q_DIFF_Item_2 renames E1.Q_DIFF_List (I2);
               begin
                  E2.Q_DIFF := To_Q_DIFF (Pick (Q_DIFF));
                  E2.Has_NC_CDDIFF := E2.Q_DIFF = 0;
                  Cover (21, E2.Has_NC_CDDIFF);
                  if E2.Has_NC_CDDIFF then
                     E2.NC_CDDIFF := To_NC_CDDIFF (Pick (NC_CDDIFF));
                  end if;
                  E2.Has_NC_DIFF := E2.Q_DIFF in 1 | 2;
                  Cover (22, E2.Has_NC_DIFF);
                  if E2.Has_NC_DIFF then
                     E2.NC_DIFF := To_NC_DIFF (Pick (NC_DIFF));
                  end if;
                  E2.V_DIFF := To_V_DIFF (Pick (V_DIFF));
               end;
            end loop;
         end;
      end loop;
   end Fill_Track_P27;

   procedure Fill_Track_P41 (P : out Track_P41_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P41_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.D_LEVELTR := To_D_LEVELTR (Pick (D_LEVELTR));
      P.M_LEVELTR := To_M_LEVELTR (Pick (M_LEVELTR));
      P.Has_NID_NTC := P.M_LEVELTR = 1;
      Cover (23, P.Has_NID_NTC);
      if P.Has_NID_NTC then
         P.NID_NTC := To_NID_NTC (Pick (NID_NTC));
      end if;
      P.L_ACKLEVELTR := To_L_ACKLEVELTR (Pick (L_ACKLEVELTR));
      P.N_ITER := To_N_ITER (Count (31, 1, 12));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : Track_P41_Pkg.M_LEVELTR_Item renames P.M_LEVELTR_List (I1);
         begin
            E1.M_LEVELTR := To_M_LEVELTR (Pick (M_LEVELTR));
            E1.Has_NID_NTC := E1.M_LEVELTR = 1;
            Cover (24, E1.Has_NID_NTC);
            if E1.Has_NID_NTC then
               E1.NID_NTC := To_NID_NTC (Pick (NID_NTC));
            end if;
            E1.L_ACKLEVELTR := To_L_ACKLEVELTR (Pick (L_ACKLEVELTR));
         end;
      end loop;
   end Fill_Track_P41;

   procedure Fill_Track_P44 (P : out Track_P44_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P44_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.NID_XUSER := To_NID_XUSER (Pick (NID_XUSER));
      P.Has_NID_NTC := P.NID_XUSER = 102;
      Cover (25, P.Has_NID_NTC);
      if P.Has_NID_NTC then
         P.NID_NTC := To_NID_NTC (Pick (NID_NTC));
      end if;
      P.Raw_Bits := Natural (Raw_Count (64));
      Random_Bits (P.Raw, P.Raw_Bits);
   end Fill_Track_P44;

   procedure Fill_Track_P65 (P : out Track_P65_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P65_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.NID_TSR := To_NID_TSR (Pick (NID_TSR));
      P.D_TSR := To_D_TSR (Pick (D_TSR));
      P.L_TSR := To_L_TSR (Pick (L_TSR));
      P.Q_FRONT := To_Q_FRONT (Pick (Q_FRONT));
      P.V_TSR := To_V_TSR (Pick (V_TSR));
   end Fill_Track_P65;

   procedure Fill_Track_P73 (P : out Track_P73_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P73_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.Q_TEXTCLASS := To_Q_TEXTCLASS (Pick (Q_TEXTCLASS));
      P.Q_TEXTDISPLAY := To_Q_TEXTDISPLAY (Pick (Q_TEXTDISPLAY));
      P.D_TEXTDISPLAY := To_D_TEXTDISPLAY (Pick (D_TEXTDISPLAY));
      P.M_MODETEXTDISPLAY := To_M_MODETEXTDISPLAY (Pick (M_MODETEXTDISPLAY));
      P.M_LEVELTEXTDISPLAY :=
        To_M_LEVELTEXTDISPLAY (Pick (M_LEVELTEXTDISPLAY));
      P.Has_NID_NTC := P.M_LEVELTEXTDISPLAY = 1;
      Cover (26, P.Has_NID_NTC);
      if P.Has_NID_NTC then
         P.NID_NTC := To_NID_NTC (Pick (NID_NTC));
      end if;
      P.L_TEXTDISPLAY := To_L_TEXTDISPLAY (Pick (L_TEXTDISPLAY));
      P.T_TEXTDISPLAY := To_T_TEXTDISPLAY (Pick (T_TEXTDISPLAY));
      P.M_MODETEXTDISPLAY_END :=
        To_M_MODETEXTDISPLAY (Pick (M_MODETEXTDISPLAY));
      P.M_LEVELTEXTDISPLAY_END :=
        To_M_LEVELTEXTDISPLAY (Pick (M_LEVELTEXTDISPLAY));
      P.Has_NID_NTC_END := P.M_LEVELTEXTDISPLAY_END = 1;
      Cover (27, P.Has_NID_NTC_END);
      if P.Has_NID_NTC_END then
         P.NID_NTC_END := To_NID_NTC (Pick (NID_NTC));
      end if;
      P.Q_TEXTCONFIRM := To_Q_TEXTCONFIRM (Pick (Q_TEXTCONFIRM));
      P.Has_Q_CONFTEXTDISPLAY := P.Q_TEXTCONFIRM /= 0;
      Cover (29, P.Has_Q_CONFTEXTDISPLAY);
      if P.Has_Q_CONFTEXTDISPLAY then
         P.Q_CONFTEXTDISPLAY :=
           To_Q_CONFTEXTDISPLAY (Pick (Q_CONFTEXTDISPLAY));
         P.Q_TEXTREPORT := To_Q_TEXTREPORT (Pick (Q_TEXTREPORT));
         P.Has_NID_TEXTMESSAGE := P.Q_TEXTREPORT = 1;
         Cover (28, P.Has_NID_TEXTMESSAGE);
         if P.Has_NID_TEXTMESSAGE then
            P.NID_TEXTMESSAGE := To_NID_TEXTMESSAGE (Pick (NID_TEXTMESSAGE));
            P.NID_C := To_NID_C (Pick (NID_C));
            P.NID_RBC := To_NID_RBC (Pick (NID_RBC));
         end if;
      end if;
      P.L_TEXT := To_L_TEXT (Count (255, 1, 13));
      for I1 in 1 .. Natural (P.L_TEXT) loop
         P.X_TEXT_List (I1) := To_X_TEXT (Pick (X_TEXT));
      end loop;
   end Fill_Track_P73;

   procedure Fill_Track_P136 (P : out Track_P136_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P136_Pkg.NID);
      P.Q_DIR := To_Q_DIR (Pick (Q_DIR));
      P.Q_NEWCOUNTRY := To_Q_NEWCOUNTRY (Pick (Q_NEWCOUNTRY));
      P.Has_NID_C := P.Q_NEWCOUNTRY = 1;
      Cover (30, P.Has_NID_C);
      if P.Has_NID_C then
         P.NID_C := To_NID_C (Pick (NID_C));
      end if;
      P.NID_BG := To_NID_BG (Pick (NID_BG));
   end Fill_Track_P136;

   procedure Fill_Track_P255 (P : out Track_P255_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Track_P255_Pkg.NID);
   end Fill_Track_P255;

   procedure Fill_Train_P0 (P : out Train_P0_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Train_P0_Pkg.NID);
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.NID_C := To_NID_C (Pick (NID_C));
      P.NID_BG := To_NID_BG (Pick (NID_BG));
      P.D_LRBG := To_D_LRBG (Pick (D_LRBG));
      P.Q_DIRLRBG := To_Q_DIRLRBG (Pick (Q_DIRLRBG));
      P.Q_DLRBG := To_Q_DLRBG (Pick (Q_DLRBG));
      P.L_DOUBTOVER := To_L_DOUBTOVER (Pick (L_DOUBTOVER));
      P.L_DOUBTUNDER := To_L_DOUBTUNDER (Pick (L_DOUBTUNDER));
      P.Q_INTEGRITY := To_Q_INTEGRITY (Pick (Q_INTEGRITY));
      P.Has_L_TRAININT := P.Q_INTEGRITY in 1 | 2;
      Cover (31, P.Has_L_TRAININT);
      if P.Has_L_TRAININT then
         P.L_TRAININT := To_L_TRAININT (Pick (L_TRAININT));
      end if;
      P.V_TRAIN := To_V_TRAIN (Pick (V_TRAIN));
      P.Q_DIRTRAIN := To_Q_DIRTRAIN (Pick (Q_DIRTRAIN));
      P.M_MODE := To_M_MODE (Pick (M_MODE));
      P.M_LEVEL := To_M_LEVEL (Pick (M_LEVEL));
      P.Has_NID_NTC := P.M_LEVEL = 1;
      Cover (32, P.Has_NID_NTC);
      if P.Has_NID_NTC then
         P.NID_NTC := To_NID_NTC (Pick (NID_NTC));
      end if;
   end Fill_Train_P0;

   procedure Fill_Train_P1 (P : out Train_P1_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Train_P1_Pkg.NID);
      P.Q_SCALE := To_Q_SCALE (Pick (Q_SCALE));
      P.NID_C := To_NID_C (Pick (NID_C));
      P.NID_BG := To_NID_BG (Pick (NID_BG));
      P.NID_C_PRVLRBG := To_NID_C (Pick (NID_C));
      P.NID_BG_PRVLRBG := To_NID_BG (Pick (NID_BG));
      P.D_LRBG := To_D_LRBG (Pick (D_LRBG));
      P.Q_DIRLRBG := To_Q_DIRLRBG (Pick (Q_DIRLRBG));
      P.Q_DLRBG := To_Q_DLRBG (Pick (Q_DLRBG));
      P.L_DOUBTOVER := To_L_DOUBTOVER (Pick (L_DOUBTOVER));
      P.L_DOUBTUNDER := To_L_DOUBTUNDER (Pick (L_DOUBTUNDER));
      P.Q_INTEGRITY := To_Q_INTEGRITY (Pick (Q_INTEGRITY));
      P.Has_L_TRAININT := P.Q_INTEGRITY in 1 | 2;
      Cover (33, P.Has_L_TRAININT);
      if P.Has_L_TRAININT then
         P.L_TRAININT := To_L_TRAININT (Pick (L_TRAININT));
      end if;
      P.V_TRAIN := To_V_TRAIN (Pick (V_TRAIN));
      P.Q_DIRTRAIN := To_Q_DIRTRAIN (Pick (Q_DIRTRAIN));
      P.M_MODE := To_M_MODE (Pick (M_MODE));
      P.M_LEVEL := To_M_LEVEL (Pick (M_LEVEL));
      P.Has_NID_NTC := P.M_LEVEL = 1;
      Cover (34, P.Has_NID_NTC);
      if P.Has_NID_NTC then
         P.NID_NTC := To_NID_NTC (Pick (NID_NTC));
      end if;
   end Fill_Train_P1;

   procedure Fill_Train_P2 (P : out Train_P2_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Train_P2_Pkg.NID);
      P.M_VERSION := To_M_VERSION (Pick (M_VERSION));
      P.N_ITER := To_N_ITER (Count (31, 1, 14));
      for I1 in 1 .. Natural (P.N_ITER) loop
         P.M_VERSION_List (I1) := To_M_VERSION (Pick (M_VERSION));
      end loop;
   end Fill_Train_P2;

   procedure Fill_Train_P4 (P : out Train_P4_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Train_P4_Pkg.NID);
      P.M_ERROR := To_M_ERROR (Pick (M_ERROR));
   end Fill_Train_P4;

   procedure Fill_Train_P5 (P : out Train_P5_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Train_P5_Pkg.NID);
      P.NID_OPERATIONAL := To_NID_OPERATIONAL (Pick (NID_OPERATIONAL));
   end Fill_Train_P5;

   procedure Fill_Train_P44 (P : out Train_P44_Pkg.Packet_T) is
   begin
      P := (others => <>);
      P.NID_PACKET := To_NID_PACKET (Train_P44_Pkg.NID);
      P.NID_XUSER := To_NID_XUSER (Pick (NID_XUSER));
      P.Raw_Bits := Natural (Raw_Count (64));
      Random_Bits (P.Raw, P.Raw_Bits);
   end Fill_Train_P44;

   generic
      type Packet_T is private;
      Has_Length : Boolean;
      with procedure Fill (P : out Packet_T);
      with procedure Encode (P  : Packet_T;
                             W  : in out Writer;
                             OK : out Boolean);
      with procedure Decode (R  : in out Reader;
                             P  : out Packet_T;
                             OK : out Boolean);
      with function Length (P : Packet_T) return Natural;
      with procedure Set_Length (P : in out Packet_T; L : Natural);
   procedure Generic_Round_Trip (Result : out Result_T;
                                 Bits   : out Natural);

   procedure Generic_Round_Trip (Result : out Result_T;
                                 Bits   : out Natural)
   is
      P, Q : Packet_T;
      W    : Writer (Max_Bytes);
      R    : Reader (Max_Bytes);
      OK   : Boolean;
   begin
      Fill (P);
      Encode (P, W, OK);
      Bits := Position (W);
      if not OK then
         Result := (if Failed (W) or else Position (W) > 8191
                    then Too_Long else Encode_Failed);
         return;
      end if;
      Load (R, Data (W), Position (W));
      Decode (R, Q, OK);
      if not OK then
         Result := Decode_Failed;
      elsif Position (R) /= Position (W)
        or else (Has_Length and then Length (Q) /= Position (W))
      then
         Result := Length_Differs;
      else
         Set_Length (P, Length (Q));
         Result := (if P = Q then Passed else Record_Differs);
      end if;
   end Generic_Round_Trip;

   function Length_Track_P0 (P : Track_P0_Pkg.Packet_T)
     return Natural is (0);
   procedure Set_Length_Track_P0
     (P : in out Track_P0_Pkg.Packet_T; L : Natural) is null;
   procedure Round_Trip_Track_P0 is new Generic_Round_Trip
     (Track_P0_Pkg.Packet_T, False, Fill_Track_P0,
      Track_P0_Pkg.Encode, Track_P0_Pkg.Decode,
      Length_Track_P0, Set_Length_Track_P0);

   function Length_Track_P2 (P : Track_P2_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P2
     (P : in out Track_P2_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P2
     (P : in out Track_P2_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P2;
   procedure Round_Trip_Track_P2 is new Generic_Round_Trip
     (Track_P2_Pkg.Packet_T, True, Fill_Track_P2,
      Track_P2_Pkg.Encode, Track_P2_Pkg.Decode,
      Length_Track_P2, Set_Length_Track_P2);

   function Length_Track_P3 (P : Track_P3_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P3
     (P : in out Track_P3_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P3
     (P : in out Track_P3_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P3;
   procedure Round_Trip_Track_P3 is new Generic_Round_Trip
     (Track_P3_Pkg.Packet_T, True, Fill_Track_P3,
      Track_P3_Pkg.Encode, Track_P3_Pkg.Decode,
      Length_Track_P3, Set_Length_Track_P3);

   function Length_Track_P5 (P : Track_P5_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P5
     (P : in out Track_P5_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P5
     (P : in out Track_P5_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P5;
   procedure Round_Trip_Track_P5 is new Generic_Round_Trip
     (Track_P5_Pkg.Packet_T, True, Fill_Track_P5,
      Track_P5_Pkg.Encode, Track_P5_Pkg.Decode,
      Length_Track_P5, Set_Length_Track_P5);

   function Length_Track_P12 (P : Track_P12_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P12
     (P : in out Track_P12_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P12
     (P : in out Track_P12_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P12;
   procedure Round_Trip_Track_P12 is new Generic_Round_Trip
     (Track_P12_Pkg.Packet_T, True, Fill_Track_P12,
      Track_P12_Pkg.Encode, Track_P12_Pkg.Decode,
      Length_Track_P12, Set_Length_Track_P12);

   function Length_Track_P15 (P : Track_P15_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P15
     (P : in out Track_P15_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P15
     (P : in out Track_P15_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P15;
   procedure Round_Trip_Track_P15 is new Generic_Round_Trip
     (Track_P15_Pkg.Packet_T, True, Fill_Track_P15,
      Track_P15_Pkg.Encode, Track_P15_Pkg.Decode,
      Length_Track_P15, Set_Length_Track_P15);

   function Length_Track_P21 (P : Track_P21_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P21
     (P : in out Track_P21_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P21
     (P : in out Track_P21_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P21;
   procedure Round_Trip_Track_P21 is new Generic_Round_Trip
     (Track_P21_Pkg.Packet_T, True, Fill_Track_P21,
      Track_P21_Pkg.Encode, Track_P21_Pkg.Decode,
      Length_Track_P21, Set_Length_Track_P21);

   function Length_Track_P27 (P : Track_P27_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P27
     (P : in out Track_P27_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P27
     (P : in out Track_P27_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P27;
   procedure Round_Trip_Track_P27 is new Generic_Round_Trip
     (Track_P27_Pkg.Packet_T, True, Fill_Track_P27,
      Track_P27_Pkg.Encode, Track_P27_Pkg.Decode,
      Length_Track_P27, Set_Length_Track_P27);

   function Length_Track_P41 (P : Track_P41_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P41
     (P : in out Track_P41_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P41
     (P : in out Track_P41_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P41;
   procedure Round_Trip_Track_P41 is new Generic_Round_Trip
     (Track_P41_Pkg.Packet_T, True, Fill_Track_P41,
      Track_P41_Pkg.Encode, Track_P41_Pkg.Decode,
      Length_Track_P41, Set_Length_Track_P41);

   function Length_Track_P44 (P : Track_P44_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P44
     (P : in out Track_P44_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P44
     (P : in out Track_P44_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P44;
   procedure Round_Trip_Track_P44 is new Generic_Round_Trip
     (Track_P44_Pkg.Packet_T, True, Fill_Track_P44,
      Track_P44_Pkg.Encode, Track_P44_Pkg.Decode,
      Length_Track_P44, Set_Length_Track_P44);

   function Length_Track_P65 (P : Track_P65_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P65
     (P : in out Track_P65_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P65
     (P : in out Track_P65_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P65;
   procedure Round_Trip_Track_P65 is new Generic_Round_Trip
     (Track_P65_Pkg.Packet_T, True, Fill_Track_P65,
      Track_P65_Pkg.Encode, Track_P65_Pkg.Decode,
      Length_Track_P65, Set_Length_Track_P65);

   function Length_Track_P73 (P : Track_P73_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P73
     (P : in out Track_P73_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P73
     (P : in out Track_P73_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P73;
   procedure Round_Trip_Track_P73 is new Generic_Round_Trip
     (Track_P73_Pkg.Packet_T, True, Fill_Track_P73,
      Track_P73_Pkg.Encode, Track_P73_Pkg.Decode,
      Length_Track_P73, Set_Length_Track_P73);

   function Length_Track_P136 (P : Track_P136_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Track_P136
     (P : in out Track_P136_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Track_P136
     (P : in out Track_P136_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Track_P136;
   procedure Round_Trip_Track_P136 is new Generic_Round_Trip
     (Track_P136_Pkg.Packet_T, True, Fill_Track_P136,
      Track_P136_Pkg.Encode, Track_P136_Pkg.Decode,
      Length_Track_P136, Set_Length_Track_P136);

   function Length_Track_P255 (P : Track_P255_Pkg.Packet_T)
     return Natural is (0);
   procedure Set_Length_Track_P255
     (P : in out Track_P255_Pkg.Packet_T; L : Natural) is null;
   procedure Round_Trip_Track_P255 is new Generic_Round_Trip
     (Track_P255_Pkg.Packet_T, False, Fill_Track_P255,
      Track_P255_Pkg.Encode, Track_P255_Pkg.Decode,
      Length_Track_P255, Set_Length_Track_P255);

   function Length_Train_P0 (P : Train_P0_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Train_P0
     (P : in out Train_P0_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Train_P0
     (P : in out Train_P0_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Train_P0;
   procedure Round_Trip_Train_P0 is new Generic_Round_Trip
     (Train_P0_Pkg.Packet_T, True, Fill_Train_P0,
      Train_P0_Pkg.Encode, Train_P0_Pkg.Decode,
      Length_Train_P0, Set_Length_Train_P0);

   function Length_Train_P1 (P : Train_P1_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Train_P1
     (P : in out Train_P1_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Train_P1
     (P : in out Train_P1_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Train_P1;
   procedure Round_Trip_Train_P1 is new Generic_Round_Trip
     (Train_P1_Pkg.Packet_T, True, Fill_Train_P1,
      Train_P1_Pkg.Encode, Train_P1_Pkg.Decode,
      Length_Train_P1, Set_Length_Train_P1);

   function Length_Train_P2 (P : Train_P2_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Train_P2
     (P : in out Train_P2_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Train_P2
     (P : in out Train_P2_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Train_P2;
   procedure Round_Trip_Train_P2 is new Generic_Round_Trip
     (Train_P2_Pkg.Packet_T, True, Fill_Train_P2,
      Train_P2_Pkg.Encode, Train_P2_Pkg.Decode,
      Length_Train_P2, Set_Length_Train_P2);

   function Length_Train_P4 (P : Train_P4_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Train_P4
     (P : in out Train_P4_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Train_P4
     (P : in out Train_P4_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Train_P4;
   procedure Round_Trip_Train_P4 is new Generic_Round_Trip
     (Train_P4_Pkg.Packet_T, True, Fill_Train_P4,
      Train_P4_Pkg.Encode, Train_P4_Pkg.Decode,
      Length_Train_P4, Set_Length_Train_P4);

   function Length_Train_P5 (P : Train_P5_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Train_P5
     (P : in out Train_P5_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Train_P5
     (P : in out Train_P5_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Train_P5;
   procedure Round_Trip_Train_P5 is new Generic_Round_Trip
     (Train_P5_Pkg.Packet_T, True, Fill_Train_P5,
      Train_P5_Pkg.Encode, Train_P5_Pkg.Decode,
      Length_Train_P5, Set_Length_Train_P5);

   function Length_Train_P44 (P : Train_P44_Pkg.Packet_T)
     return Natural is (Natural (P.L_PACKET));
   procedure Set_Length_Train_P44
     (P : in out Train_P44_Pkg.Packet_T; L : Natural);
   procedure Set_Length_Train_P44
     (P : in out Train_P44_Pkg.Packet_T; L : Natural) is
   begin
      P.L_PACKET := L_PACKET_T (L);
   end Set_Length_Train_P44;
   procedure Round_Trip_Train_P44 is new Generic_Round_Trip
     (Train_P44_Pkg.Packet_T, True, Fill_Train_P44,
      Train_P44_Pkg.Encode, Train_P44_Pkg.Decode,
      Length_Train_P44, Set_Length_Train_P44);

   procedure Round_Trip (Kind   : ETCS_Catalogue.Known_Kind_T;
                         Values : Value_Mode_T;
                         Counts : Count_Mode_T;
                         Result : out Result_T;
                         Bits   : out Natural)
   is
      use ETCS_Catalogue;
   begin
      Value_Mode := Values;
      Count_Mode := Counts;
      case Kind is
         when Track_P0 => Round_Trip_Track_P0 (Result, Bits);
         when Track_P2 => Round_Trip_Track_P2 (Result, Bits);
         when Track_P3 => Round_Trip_Track_P3 (Result, Bits);
         when Track_P5 => Round_Trip_Track_P5 (Result, Bits);
         when Track_P12 => Round_Trip_Track_P12 (Result, Bits);
         when Track_P15 => Round_Trip_Track_P15 (Result, Bits);
         when Track_P21 => Round_Trip_Track_P21 (Result, Bits);
         when Track_P27 => Round_Trip_Track_P27 (Result, Bits);
         when Track_P41 => Round_Trip_Track_P41 (Result, Bits);
         when Track_P44 => Round_Trip_Track_P44 (Result, Bits);
         when Track_P65 => Round_Trip_Track_P65 (Result, Bits);
         when Track_P73 => Round_Trip_Track_P73 (Result, Bits);
         when Track_P136 => Round_Trip_Track_P136 (Result, Bits);
         when Track_P255 => Round_Trip_Track_P255 (Result, Bits);
         when Train_P0 => Round_Trip_Train_P0 (Result, Bits);
         when Train_P1 => Round_Trip_Train_P1 (Result, Bits);
         when Train_P2 => Round_Trip_Train_P2 (Result, Bits);
         when Train_P4 => Round_Trip_Train_P4 (Result, Bits);
         when Train_P5 => Round_Trip_Train_P5 (Result, Bits);
         when Train_P44 => Round_Trip_Train_P44 (Result, Bits);
      end case;
   end Round_Trip;

   procedure Write_Random (Kind   : ETCS_Catalogue.Known_Kind_T;
                           Values : Value_Mode_T;
                           Counts : Count_Mode_T;
                           W      : in out ETCS_Bits.Writer;
                           OK     : out Boolean)
   is
      use ETCS_Catalogue;
   begin
      Value_Mode := Values;
      Count_Mode := Counts;
      case Kind is
         when Track_P0 =>
            declare
               P : Track_P0_Pkg.Packet_T;
            begin
               Fill_Track_P0 (P);
               Track_P0_Pkg.Encode (P, W, OK);
            end;
         when Track_P2 =>
            declare
               P : Track_P2_Pkg.Packet_T;
            begin
               Fill_Track_P2 (P);
               Track_P2_Pkg.Encode (P, W, OK);
            end;
         when Track_P3 =>
            declare
               P : Track_P3_Pkg.Packet_T;
            begin
               Fill_Track_P3 (P);
               Track_P3_Pkg.Encode (P, W, OK);
            end;
         when Track_P5 =>
            declare
               P : Track_P5_Pkg.Packet_T;
            begin
               Fill_Track_P5 (P);
               Track_P5_Pkg.Encode (P, W, OK);
            end;
         when Track_P12 =>
            declare
               P : Track_P12_Pkg.Packet_T;
            begin
               Fill_Track_P12 (P);
               Track_P12_Pkg.Encode (P, W, OK);
            end;
         when Track_P15 =>
            declare
               P : Track_P15_Pkg.Packet_T;
            begin
               Fill_Track_P15 (P);
               Track_P15_Pkg.Encode (P, W, OK);
            end;
         when Track_P21 =>
            declare
               P : Track_P21_Pkg.Packet_T;
            begin
               Fill_Track_P21 (P);
               Track_P21_Pkg.Encode (P, W, OK);
            end;
         when Track_P27 =>
            declare
               P : Track_P27_Pkg.Packet_T;
            begin
               Fill_Track_P27 (P);
               Track_P27_Pkg.Encode (P, W, OK);
            end;
         when Track_P41 =>
            declare
               P : Track_P41_Pkg.Packet_T;
            begin
               Fill_Track_P41 (P);
               Track_P41_Pkg.Encode (P, W, OK);
            end;
         when Track_P44 =>
            declare
               P : Track_P44_Pkg.Packet_T;
            begin
               Fill_Track_P44 (P);
               Track_P44_Pkg.Encode (P, W, OK);
            end;
         when Track_P65 =>
            declare
               P : Track_P65_Pkg.Packet_T;
            begin
               Fill_Track_P65 (P);
               Track_P65_Pkg.Encode (P, W, OK);
            end;
         when Track_P73 =>
            declare
               P : Track_P73_Pkg.Packet_T;
            begin
               Fill_Track_P73 (P);
               Track_P73_Pkg.Encode (P, W, OK);
            end;
         when Track_P136 =>
            declare
               P : Track_P136_Pkg.Packet_T;
            begin
               Fill_Track_P136 (P);
               Track_P136_Pkg.Encode (P, W, OK);
            end;
         when Track_P255 =>
            declare
               P : Track_P255_Pkg.Packet_T;
            begin
               Fill_Track_P255 (P);
               Track_P255_Pkg.Encode (P, W, OK);
            end;
         when Train_P0 =>
            declare
               P : Train_P0_Pkg.Packet_T;
            begin
               Fill_Train_P0 (P);
               Train_P0_Pkg.Encode (P, W, OK);
            end;
         when Train_P1 =>
            declare
               P : Train_P1_Pkg.Packet_T;
            begin
               Fill_Train_P1 (P);
               Train_P1_Pkg.Encode (P, W, OK);
            end;
         when Train_P2 =>
            declare
               P : Train_P2_Pkg.Packet_T;
            begin
               Fill_Train_P2 (P);
               Train_P2_Pkg.Encode (P, W, OK);
            end;
         when Train_P4 =>
            declare
               P : Train_P4_Pkg.Packet_T;
            begin
               Fill_Train_P4 (P);
               Train_P4_Pkg.Encode (P, W, OK);
            end;
         when Train_P5 =>
            declare
               P : Train_P5_Pkg.Packet_T;
            begin
               Fill_Train_P5 (P);
               Train_P5_Pkg.Encode (P, W, OK);
            end;
         when Train_P44 =>
            declare
               P : Train_P44_Pkg.Packet_T;
            begin
               Fill_Train_P44 (P);
               Train_P44_Pkg.Encode (P, W, OK);
            end;
      end case;
   end Write_Random;

   function Condition_Name (C : Positive) return String is
   begin
      case C is
         when 1 =>
            return "Track_P3 National Values: if Q_NVKVINTSET == 1";
         when 2 =>
            return "Track_P3 National Values: if Q_NVKVINTSET == 1";
         when 3 =>
            return "Track_P3 National Values: if Q_NVKVINTSET == 1";
         when 4 =>
            return "Track_P3 National Values: if Q_NVKVINTSET == 1";
         when 5 =>
            return "Track_P3 National Values: if Q_NVKVINTSET == 1";
         when 6 =>
            return "Track_P3 National Values: if Q_NVKVINTSET == 1";
         when 7 =>
            return "Track_P3 National Values: if Q_NVKINT == 1";
         when 8 =>
            return "Track_P5 Linking: if Q_NEWCOUNTRY == 1";
         when 9 =>
            return "Track_P5 Linking: if Q_NEWCOUNTRY == 1";
         when 10 =>
            return
              "Track_P12 Level 1 Movement Authority: if Q_SECTIONTIMER =="
              & " 1";
         when 11 =>
            return
              "Track_P12 Level 1 Movement Authority: if Q_SECTIONTIMER =="
              & " 1";
         when 12 =>
            return "Track_P12 Level 1 Movement Authority: if Q_ENDTIMER == 1";
         when 13 =>
            return
              "Track_P12 Level 1 Movement Authority: if Q_DANGERPOINT == 1";
         when 14 =>
            return "Track_P12 Level 1 Movement Authority: if Q_OVERLAP == 1";
         when 15 =>
            return
              "Track_P15 Level 2 Movement Authority: if Q_SECTIONTIMER =="
              & " 1";
         when 16 =>
            return
              "Track_P15 Level 2 Movement Authority: if Q_SECTIONTIMER =="
              & " 1";
         when 17 =>
            return "Track_P15 Level 2 Movement Authority: if Q_ENDTIMER == 1";
         when 18 =>
            return
              "Track_P15 Level 2 Movement Authority: if Q_DANGERPOINT == 1";
         when 19 =>
            return "Track_P15 Level 2 Movement Authority: if Q_OVERLAP == 1";
         when 20 =>
            return
              "Track_P27 International Static Speed Profile: if Q_DIFF =="
              & " 0";
         when 21 =>
            return
              "Track_P27 International Static Speed Profile: if Q_DIFF in"
              & " [1, 2]";
         when 22 =>
            return
              "Track_P27 International Static Speed Profile: if Q_DIFF =="
              & " 0";
         when 23 =>
            return
              "Track_P27 International Static Speed Profile: if Q_DIFF in"
              & " [1, 2]";
         when 24 =>
            return "Track_P41 Level Transition Order: if M_LEVELTR == 1";
         when 25 =>
            return "Track_P41 Level Transition Order: if M_LEVELTR == 1";
         when 26 =>
            return
              "Track_P44 Data used by applications outside the ERTMS/ETCS"
              & " system: if NID_XUSER == 102";
         when 27 =>
            return
              "Track_P73 Packet for sending plain text messages: if"
              & " M_LEVELTEXTDISPLAY == 1";
         when 28 =>
            return
              "Track_P73 Packet for sending plain text messages: if"
              & " M_LEVELTEXTDISPLAY_END == 1";
         when 29 =>
            return
              "Track_P73 Packet for sending plain text messages: if"
              & " Q_TEXTREPORT == 1";
         when 30 =>
            return
              "Track_P73 Packet for sending plain text messages: if"
              & " Q_TEXTCONFIRM != 0";
         when 31 =>
            return
              "Track_P136 Infill location reference: if Q_NEWCOUNTRY == 1";
         when 32 =>
            return "Train_P0 Position Report: if Q_INTEGRITY in [1, 2]";
         when 33 =>
            return "Train_P0 Position Report: if M_LEVEL == 1";
         when 34 =>
            return
              "Train_P1 Position Report based on two balise groups: if"
              & " Q_INTEGRITY in [1, 2]";
         when 35 =>
            return
              "Train_P1 Position Report based on two balise groups: if"
              & " M_LEVEL == 1";
         when others => return "";
      end case;
   end Condition_Name;

   function Loop_Name (L : Positive) return String is
   begin
      case L is
         when 1 =>
            return "Track_P3 National Values: loop NID_C_List";
         when 2 =>
            return "Track_P3 National Values: loop V_NVKVINT_List";
         when 3 =>
            return "Track_P3 National Values: loop V_NVKVINT_List";
         when 4 =>
            return "Track_P3 National Values: loop Q_NVKVINTSET_List";
         when 5 =>
            return "Track_P3 National Values: loop L_NVKRINT_List";
         when 6 =>
            return "Track_P5 Linking: loop D_LINK_List";
         when 7 =>
            return "Track_P12 Level 1 Movement Authority: loop L_SECTION_List";
         when 8 =>
            return "Track_P15 Level 2 Movement Authority: loop L_SECTION_List";
         when 9 =>
            return "Track_P21 Gradient Profile: loop D_GRADIENT_List";
         when 10 =>
            return
              "Track_P27 International Static Speed Profile: loop"
              & " Q_DIFF_List";
         when 11 =>
            return
              "Track_P27 International Static Speed Profile: loop"
              & " Q_DIFF_List";
         when 12 =>
            return
              "Track_P27 International Static Speed Profile: loop"
              & " D_STATIC_List";
         when 13 =>
            return "Track_P41 Level Transition Order: loop M_LEVELTR_List";
         when 14 =>
            return
              "Track_P73 Packet for sending plain text messages: loop"
              & " X_TEXT_List";
         when 15 =>
            return
              "Train_P2 Onboard supported system versions: loop"
              & " M_VERSION_List";
         when others => return "";
      end case;
   end Loop_Name;

   function Loop_Depth (L : Positive) return Positive is
   begin
      case L is
         when 1 => return 1;
         when 2 => return 1;
         when 3 => return 2;
         when 4 => return 1;
         when 5 => return 1;
         when 6 => return 1;
         when 7 => return 1;
         when 8 => return 1;
         when 9 => return 1;
         when 10 => return 1;
         when 11 => return 2;
         when 12 => return 1;
         when 13 => return 1;
         when 14 => return 1;
         when 15 => return 1;
         when others => return 1;
      end case;
   end Loop_Depth;

end ETCS_Language_Random;
