--  ETCS on-board (EVC)
--  Packet 0, train to track: Position Report.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.3.1. Sent by: RBC, RIU.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

--  ETCS_Bits, ETCS_Variables and Interfaces are withed and used
--  by the parent package, which makes them visible here.

pragma Unevaluated_Use_Of_Old (Allow);

package ETCS_Train_Packets.P0
  with SPARK_Mode => On
is

   NID : constant := 0;
   Name : constant String := "Position Report";

   type Packet_T is record
      NID_PACKET     : NID_PACKET_T := NID;
      L_PACKET       : L_PACKET_T := 0;
      Q_SCALE        : Q_SCALE_T := 0;
      NID_C          : NID_C_T := 0;
      NID_BG         : NID_BG_T := 0;
      D_LRBG         : D_LRBG_T := 0;
      Q_DIRLRBG      : Q_DIRLRBG_T := 0;
      Q_DLRBG        : Q_DLRBG_T := 0;
      L_DOUBTOVER    : L_DOUBTOVER_T := 0;
      L_DOUBTUNDER   : L_DOUBTUNDER_T := 0;
      Q_INTEGRITY    : Q_INTEGRITY_T := 0;
      --  present when Q_INTEGRITY in [1, 2]
      Has_L_TRAININT : Boolean := False;
      L_TRAININT     : L_TRAININT_T := 0;
      V_TRAIN        : V_TRAIN_T := 0;
      Q_DIRTRAIN     : Q_DIRTRAIN_T := 0;
      M_MODE         : M_MODE_T := 0;
      M_LEVEL        : M_LEVEL_T := 0;
      --  present when M_LEVEL == 1
      Has_NID_NTC    : Boolean := False;
      NID_NTC        : NID_NTC_T := 0;
   end record;

   --  Every variable read holds a value of 7.5, not a spare one
   --  (Is_Valid of its type; SUBSET-026 3.16.1.1.1): those of the
   --  packet, of the conditional blocks present and of the items of
   --  its loops. Decode does not check it.
   function Valid (P : Packet_T) return Boolean;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Train_Packets.P0;
