--  ETCS on-board (EVC)
--  Packet 41, track to train: Level Transition Order, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Track_Packets.P41
  with SPARK_Mode => On
is

   --  The items with every component at its default
   Empty_M_LEVELTR_Item : constant M_LEVELTR_Item := (others => <>);

   --  One item of M_LEVELTR_List
   procedure Decode_M_LEVELTR_Item
     (R  : in out Reader;
      E1 : out M_LEVELTR_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      E1 := Empty_M_LEVELTR_Item;
      Read (R, 3, V);
      E1.M_LEVELTR := To_M_LEVELTR (V);
      E1.Has_NID_NTC := E1.M_LEVELTR = 1;
      if E1.Has_NID_NTC then
         Read (R, 8, V);
         E1.NID_NTC := To_NID_NTC (V);
      end if;
      Read (R, 15, V);
      E1.L_ACKLEVELTR := To_L_ACKLEVELTR (V);
   end Decode_M_LEVELTR_Item;

   --  One item of M_LEVELTR_List
   procedure Encode_M_LEVELTR_Item
     (E1   : M_LEVELTR_Item;
      W    : in out Writer;
      Good : in out Boolean)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 3, Code (E1.M_LEVELTR));
      if E1.Has_NID_NTC /= (E1.M_LEVELTR = 1) then
         Good := False;
      end if;
      if E1.M_LEVELTR = 1 then
         Write (W, 8, Code (E1.NID_NTC));
      end if;
      Write (W, 15, Code (E1.L_ACKLEVELTR));
   end Encode_M_LEVELTR_Item;

   --  Valid of one item of M_LEVELTR_List
   function Valid_M_LEVELTR_Item (E1 : M_LEVELTR_Item) return Boolean is
     (Is_Valid (E1.M_LEVELTR)
      and then (if E1.Has_NID_NTC then Is_Valid (E1.NID_NTC))
      and then Is_Valid (E1.L_ACKLEVELTR));

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.D_LEVELTR)
      and then Is_Valid (P.M_LEVELTR)
      and then (if P.Has_NID_NTC then Is_Valid (P.NID_NTC))
      and then Is_Valid (P.L_ACKLEVELTR)
      and then Is_Valid (P.N_ITER)
      and then (for all I1 in 1 .. Natural (P.N_ITER) =>
                  Valid_M_LEVELTR_Item (P.M_LEVELTR_List (I1))));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET     : NID_PACKET_T;
      Q_DIR          : Q_DIR_T;
      L_PACKET       : L_PACKET_T;
      Q_SCALE        : Q_SCALE_T;
      D_LEVELTR      : D_LEVELTR_T;
      M_LEVELTR      : M_LEVELTR_T;
      Has_NID_NTC    : Boolean;
      NID_NTC        : NID_NTC_T := 0;
      L_ACKLEVELTR   : L_ACKLEVELTR_T;
      N_ITER         : N_ITER_T;
      M_LEVELTR_List : M_LEVELTR_Array;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      D_LEVELTR := To_D_LEVELTR (V);
      Read (R, 3, V);
      M_LEVELTR := To_M_LEVELTR (V);
      Has_NID_NTC := M_LEVELTR = 1;
      if Has_NID_NTC then
         Read (R, 8, V);
         NID_NTC := To_NID_NTC (V);
      end if;
      Read (R, 15, V);
      L_ACKLEVELTR := To_L_ACKLEVELTR (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_M_LEVELTR_Item (R, M_LEVELTR_List (I1));
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         D_LEVELTR => D_LEVELTR,
         M_LEVELTR => M_LEVELTR,
         Has_NID_NTC => Has_NID_NTC,
         NID_NTC => NID_NTC,
         L_ACKLEVELTR => L_ACKLEVELTR,
         N_ITER => N_ITER,
         M_LEVELTR_List => M_LEVELTR_List);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_LEVELTR));
      Write (W, 3, Code (P.M_LEVELTR));
      if P.Has_NID_NTC /= (P.M_LEVELTR = 1) then
         Good := False;
      end if;
      if P.M_LEVELTR = 1 then
         Write (W, 8, Code (P.NID_NTC));
      end if;
      Write (W, 15, Code (P.L_ACKLEVELTR));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_M_LEVELTR_Item (P.M_LEVELTR_List (I1), W, Good);
      end loop;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P41;
