--  ETCS on-board (EVC)
--  Packet 0, train to track: Position Report, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Train_Packets.P0
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.NID_C)
      and then Is_Valid (P.NID_BG)
      and then Is_Valid (P.D_LRBG)
      and then Is_Valid (P.Q_DIRLRBG)
      and then Is_Valid (P.Q_DLRBG)
      and then Is_Valid (P.L_DOUBTOVER)
      and then Is_Valid (P.L_DOUBTUNDER)
      and then Is_Valid (P.Q_INTEGRITY)
      and then (if P.Has_L_TRAININT then Is_Valid (P.L_TRAININT))
      and then Is_Valid (P.V_TRAIN)
      and then Is_Valid (P.Q_DIRTRAIN)
      and then Is_Valid (P.M_MODE)
      and then Is_Valid (P.M_LEVEL)
      and then (if P.Has_NID_NTC then Is_Valid (P.NID_NTC)));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET     : NID_PACKET_T;
      L_PACKET       : L_PACKET_T;
      Q_SCALE        : Q_SCALE_T;
      NID_C          : NID_C_T;
      NID_BG         : NID_BG_T;
      D_LRBG         : D_LRBG_T;
      Q_DIRLRBG      : Q_DIRLRBG_T;
      Q_DLRBG        : Q_DLRBG_T;
      L_DOUBTOVER    : L_DOUBTOVER_T;
      L_DOUBTUNDER   : L_DOUBTUNDER_T;
      Q_INTEGRITY    : Q_INTEGRITY_T;
      Has_L_TRAININT : Boolean;
      L_TRAININT     : L_TRAININT_T := 0;
      V_TRAIN        : V_TRAIN_T;
      Q_DIRTRAIN     : Q_DIRTRAIN_T;
      M_MODE         : M_MODE_T;
      M_LEVEL        : M_LEVEL_T;
      Has_NID_NTC    : Boolean;
      NID_NTC        : NID_NTC_T := 0;
   begin
      Decode_Header (R, NID_PACKET, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_BG := To_NID_BG (V);
      Read (R, 15, V);
      D_LRBG := To_D_LRBG (V);
      Read (R, 2, V);
      Q_DIRLRBG := To_Q_DIRLRBG (V);
      Read (R, 2, V);
      Q_DLRBG := To_Q_DLRBG (V);
      Read (R, 15, V);
      L_DOUBTOVER := To_L_DOUBTOVER (V);
      Read (R, 15, V);
      L_DOUBTUNDER := To_L_DOUBTUNDER (V);
      Read (R, 2, V);
      Q_INTEGRITY := To_Q_INTEGRITY (V);
      Has_L_TRAININT := Q_INTEGRITY in 1 | 2;
      if Has_L_TRAININT then
         Read (R, 15, V);
         L_TRAININT := To_L_TRAININT (V);
      end if;
      Read (R, 7, V);
      V_TRAIN := To_V_TRAIN (V);
      Read (R, 2, V);
      Q_DIRTRAIN := To_Q_DIRTRAIN (V);
      Read (R, 5, V);
      M_MODE := To_M_MODE (V);
      Read (R, 3, V);
      M_LEVEL := To_M_LEVEL (V);
      Has_NID_NTC := M_LEVEL = 1;
      if Has_NID_NTC then
         Read (R, 8, V);
         NID_NTC := To_NID_NTC (V);
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         NID_C => NID_C,
         NID_BG => NID_BG,
         D_LRBG => D_LRBG,
         Q_DIRLRBG => Q_DIRLRBG,
         Q_DLRBG => Q_DLRBG,
         L_DOUBTOVER => L_DOUBTOVER,
         L_DOUBTUNDER => L_DOUBTUNDER,
         Q_INTEGRITY => Q_INTEGRITY,
         Has_L_TRAININT => Has_L_TRAININT,
         L_TRAININT => L_TRAININT,
         V_TRAIN => V_TRAIN,
         Q_DIRTRAIN => Q_DIRTRAIN,
         M_MODE => M_MODE,
         M_LEVEL => M_LEVEL,
         Has_NID_NTC => Has_NID_NTC,
         NID_NTC => NID_NTC);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_BG));
      Write (W, 15, Code (P.D_LRBG));
      Write (W, 2, Code (P.Q_DIRLRBG));
      Write (W, 2, Code (P.Q_DLRBG));
      Write (W, 15, Code (P.L_DOUBTOVER));
      Write (W, 15, Code (P.L_DOUBTUNDER));
      Write (W, 2, Code (P.Q_INTEGRITY));
      if P.Has_L_TRAININT /= (P.Q_INTEGRITY in 1 | 2) then
         Good := False;
      end if;
      if P.Q_INTEGRITY in 1 | 2 then
         Write (W, 15, Code (P.L_TRAININT));
      end if;
      Write (W, 7, Code (P.V_TRAIN));
      Write (W, 2, Code (P.Q_DIRTRAIN));
      Write (W, 5, Code (P.M_MODE));
      Write (W, 3, Code (P.M_LEVEL));
      if P.Has_NID_NTC /= (P.M_LEVEL = 1) then
         Good := False;
      end if;
      if P.M_LEVEL = 1 then
         Write (W, 8, Code (P.NID_NTC));
      end if;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P0;
