--  ETCS on-board (EVC)
--  The catalogue of the packets, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces;
with ETCS_Track_Packets.P0;
with ETCS_Track_Packets.P2;
with ETCS_Track_Packets.P3;
with ETCS_Track_Packets.P5;
with ETCS_Track_Packets.P6;
with ETCS_Track_Packets.P12;
with ETCS_Track_Packets.P13;
with ETCS_Track_Packets.P15;
with ETCS_Track_Packets.P16;
with ETCS_Track_Packets.P21;
with ETCS_Track_Packets.P27;
with ETCS_Track_Packets.P31;
with ETCS_Track_Packets.P32;
with ETCS_Track_Packets.P39;
with ETCS_Track_Packets.P40;
with ETCS_Track_Packets.P41;
with ETCS_Track_Packets.P42;
with ETCS_Track_Packets.P44;
with ETCS_Track_Packets.P45;
with ETCS_Track_Packets.P46;
with ETCS_Track_Packets.P49;
with ETCS_Track_Packets.P51;
with ETCS_Track_Packets.P52;
with ETCS_Track_Packets.P57;
with ETCS_Track_Packets.P58;
with ETCS_Track_Packets.P63;
with ETCS_Track_Packets.P64;
with ETCS_Track_Packets.P65;
with ETCS_Track_Packets.P66;
with ETCS_Track_Packets.P67;
with ETCS_Track_Packets.P68;
with ETCS_Track_Packets.P69;
with ETCS_Track_Packets.P70;
with ETCS_Track_Packets.P71;
with ETCS_Track_Packets.P73;
with ETCS_Track_Packets.P74;
with ETCS_Track_Packets.P79;
with ETCS_Track_Packets.P80;
with ETCS_Track_Packets.P88;
with ETCS_Track_Packets.P90;
with ETCS_Track_Packets.P131;
with ETCS_Track_Packets.P132;
with ETCS_Track_Packets.P133;
with ETCS_Track_Packets.P134;
with ETCS_Track_Packets.P135;
with ETCS_Track_Packets.P136;
with ETCS_Track_Packets.P137;
with ETCS_Track_Packets.P138;
with ETCS_Track_Packets.P139;
with ETCS_Track_Packets.P140;
with ETCS_Track_Packets.P141;
with ETCS_Track_Packets.P143;
with ETCS_Track_Packets.P145;
with ETCS_Track_Packets.P180;
with ETCS_Track_Packets.P181;
with ETCS_Track_Packets.P254;
with ETCS_Track_Packets.P255;
with ETCS_Train_Packets.P0;
with ETCS_Train_Packets.P1;
with ETCS_Train_Packets.P2;
with ETCS_Train_Packets.P4;
with ETCS_Train_Packets.P5;
with ETCS_Train_Packets.P9;
with ETCS_Train_Packets.P10;
with ETCS_Train_Packets.P11;
with ETCS_Train_Packets.P12;
with ETCS_Train_Packets.P44;

package body ETCS_Catalogue
  with SPARK_Mode => On
is

   ----------
   -- Kind --
   ----------

   function Kind (Direction : Direction_T; NID : Natural)
     return Packet_Kind_T
   is
   begin
      case Direction is
         when Track_To_Train =>
            case NID is
               when 0 => return Track_P0;
               when 2 => return Track_P2;
               when 3 => return Track_P3;
               when 5 => return Track_P5;
               when 6 => return Track_P6;
               when 12 => return Track_P12;
               when 13 => return Track_P13;
               when 15 => return Track_P15;
               when 16 => return Track_P16;
               when 21 => return Track_P21;
               when 27 => return Track_P27;
               when 31 => return Track_P31;
               when 32 => return Track_P32;
               when 39 => return Track_P39;
               when 40 => return Track_P40;
               when 41 => return Track_P41;
               when 42 => return Track_P42;
               when 44 => return Track_P44;
               when 45 => return Track_P45;
               when 46 => return Track_P46;
               when 49 => return Track_P49;
               when 51 => return Track_P51;
               when 52 => return Track_P52;
               when 57 => return Track_P57;
               when 58 => return Track_P58;
               when 63 => return Track_P63;
               when 64 => return Track_P64;
               when 65 => return Track_P65;
               when 66 => return Track_P66;
               when 67 => return Track_P67;
               when 68 => return Track_P68;
               when 69 => return Track_P69;
               when 70 => return Track_P70;
               when 71 => return Track_P71;
               when 73 => return Track_P73;
               when 74 => return Track_P74;
               when 79 => return Track_P79;
               when 80 => return Track_P80;
               when 88 => return Track_P88;
               when 90 => return Track_P90;
               when 131 => return Track_P131;
               when 132 => return Track_P132;
               when 133 => return Track_P133;
               when 134 => return Track_P134;
               when 135 => return Track_P135;
               when 136 => return Track_P136;
               when 137 => return Track_P137;
               when 138 => return Track_P138;
               when 139 => return Track_P139;
               when 140 => return Track_P140;
               when 141 => return Track_P141;
               when 143 => return Track_P143;
               when 145 => return Track_P145;
               when 180 => return Track_P180;
               when 181 => return Track_P181;
               when 254 => return Track_P254;
               when 255 => return Track_P255;
               when others => return Unknown;
            end case;
         when Train_To_Track =>
            case NID is
               when 0 => return Train_P0;
               when 1 => return Train_P1;
               when 2 => return Train_P2;
               when 4 => return Train_P4;
               when 5 => return Train_P5;
               when 9 => return Train_P9;
               when 10 => return Train_P10;
               when 11 => return Train_P11;
               when 12 => return Train_P12;
               when 44 => return Train_P44;
               when others => return Unknown;
            end case;
      end case;
   end Kind;

   -------------
   -- Sent_By --
   -------------

   function Sent_By (Kind : Known_Kind_T) return Senders_T is
   begin
      case Kind is
         when Track_P0 =>
            return (True, False, False, False);
         when Track_P2 =>
            return (True, False, False, False);
         when Track_P3 =>
            return (True, False, True, False);
         when Track_P5 =>
            return (True, True, True, True);
         when Track_P6 =>
            return (True, False, False, False);
         when Track_P12 =>
            return (True, True, False, True);
         when Track_P13 =>
            return (False, True, False, False);
         when Track_P15 =>
            return (False, False, True, False);
         when Track_P16 =>
            return (True, False, False, False);
         when Track_P21 =>
            return (True, True, True, True);
         when Track_P27 =>
            return (True, True, True, True);
         when Track_P31 =>
            return (True, False, True, False);
         when Track_P32 =>
            return (True, False, True, False);
         when Track_P39 =>
            return (True, True, True, True);
         when Track_P40 =>
            return (True, True, True, True);
         when Track_P41 =>
            return (True, True, True, True);
         when Track_P42 =>
            return (True, False, True, False);
         when Track_P44 =>
            return (True, True, True, True);
         when Track_P45 =>
            return (True, False, True, True);
         when Track_P46 =>
            return (True, False, False, False);
         when Track_P49 =>
            return (True, True, True, True);
         when Track_P51 =>
            return (True, True, True, True);
         when Track_P52 =>
            return (True, True, True, True);
         when Track_P57 =>
            return (False, False, True, False);
         when Track_P58 =>
            return (False, False, True, False);
         when Track_P63 =>
            return (False, False, True, False);
         when Track_P64 =>
            return (False, False, True, False);
         when Track_P65 =>
            return (True, True, True, True);
         when Track_P66 =>
            return (True, False, True, False);
         when Track_P67 =>
            return (True, False, True, False);
         when Track_P68 =>
            return (True, True, True, True);
         when Track_P69 =>
            return (True, True, True, True);
         when Track_P70 =>
            return (True, True, True, True);
         when Track_P71 =>
            return (True, True, True, True);
         when Track_P73 =>
            return (True, False, True, False);
         when Track_P74 =>
            return (True, False, True, False);
         when Track_P79 =>
            return (True, False, True, False);
         when Track_P80 =>
            return (True, True, True, True);
         when Track_P88 =>
            return (True, True, True, True);
         when Track_P90 =>
            return (True, False, False, False);
         when Track_P131 =>
            return (True, False, True, False);
         when Track_P132 =>
            return (True, False, False, False);
         when Track_P133 =>
            return (True, False, False, False);
         when Track_P134 =>
            return (True, False, False, False);
         when Track_P135 =>
            return (True, False, False, False);
         when Track_P136 =>
            return (True, True, False, True);
         when Track_P137 =>
            return (True, False, False, False);
         when Track_P138 =>
            return (True, True, True, True);
         when Track_P139 =>
            return (True, True, True, True);
         when Track_P140 =>
            return (False, False, True, False);
         when Track_P141 =>
            return (True, False, False, False);
         when Track_P143 =>
            return (False, False, False, True);
         when Track_P145 =>
            return (True, False, False, False);
         when Track_P180 =>
            return (True, True, True, True);
         when Track_P181 =>
            return (True, False, False, False);
         when Track_P254 =>
            return (True, True, False, True);
         when Track_P255 =>
            return (True, True, False, False);
         when Train_P0 =>
            return (False, False, True, True);
         when Train_P1 =>
            return (False, False, True, True);
         when Train_P2 =>
            return (False, False, True, True);
         when Train_P4 =>
            return (False, False, True, False);
         when Train_P5 =>
            return (False, False, True, False);
         when Train_P9 =>
            return (False, False, True, False);
         when Train_P10 =>
            return (False, False, True, False);
         when Train_P11 =>
            return (False, False, True, False);
         when Train_P12 =>
            return (False, False, True, False);
         when Train_P44 =>
            return (False, False, True, True);
      end case;
   end Sent_By;

   ----------
   -- Name --
   ----------

   function Name (Kind : Known_Kind_T) return String is
   begin
      case Kind is
         when Track_P0 =>
            return "Virtual Balise Cover marker";
         when Track_P2 =>
            return "System Version order";
         when Track_P3 =>
            return "National Values";
         when Track_P5 =>
            return "Linking";
         when Track_P6 =>
            return "Virtual Balise Cover order";
         when Track_P12 =>
            return "Level 1 Movement Authority";
         when Track_P13 =>
            return "Staff Responsible distance Information from loop";
         when Track_P15 =>
            return "Level 2 Movement Authority";
         when Track_P16 =>
            return "Repositioning Information";
         when Track_P21 =>
            return "Gradient Profile";
         when Track_P27 =>
            return "International Static Speed Profile";
         when Track_P31 =>
            return "RBC transition order for RBC interfaced to FRMCS only";
         when Track_P32 =>
            return "Session Management for RBC interfaced to FRMCS only";
         when Track_P39 =>
            return "Track Condition Change of traction system";
         when Track_P40 =>
            return "Track Condition Change of allowed current consumption";
         when Track_P41 =>
            return "Level Transition Order";
         when Track_P42 =>
            return "Session Management for RBC interfaced to GSM-R";
         when Track_P44 =>
            return "Data used by applications outside the ERTMS/ETCS system";
         when Track_P45 =>
            return "Radio Network transition order";
         when Track_P46 =>
            return "Conditional Level Transition Order";
         when Track_P49 =>
            return "List of Balise Groups for SH Area";
         when Track_P51 =>
            return "Axle Load Speed Profile";
         when Track_P52 =>
            return "Permitted Braking Distance Information";
         when Track_P57 =>
            return "Movement Authority Request Parameters";
         when Track_P58 =>
            return "Position Report Parameters";
         when Track_P63 =>
            return "List of Balise Groups in SR Authority";
         when Track_P64 =>
            return "Inhibition of revocable TSRs from balises in level 2";
         when Track_P65 =>
            return "Temporary Speed Restriction";
         when Track_P66 =>
            return "Temporary Speed Restriction Revocation";
         when Track_P67 =>
            return "Track Condition Big Metal Masses";
         when Track_P68 =>
            return "Track Condition";
         when Track_P69 =>
            return "Track Condition Station Platforms";
         when Track_P70 =>
            return "Route Suitability Data";
         when Track_P71 =>
            return "Adhesion factor";
         when Track_P73 =>
            return "Packet for sending plain text messages";
         when Track_P74 =>
            return "Packet for sending fixed text messages";
         when Track_P79 =>
            return "Geographical Position Information";
         when Track_P80 =>
            return "Mode profile";
         when Track_P88 =>
            return "Level Crossing information";
         when Track_P90 =>
            return "Track Ahead Free up to level 2 transition location";
         when Track_P131 =>
            return "RBC transition order for RBC interfaced to GSM-R";
         when Track_P132 =>
            return "Danger for Shunting information";
         when Track_P133 =>
            return "Radio infill area information";
         when Track_P134 =>
            return "EOLM Packet";
         when Track_P135 =>
            return "Stop Shunting on desk opening";
         when Track_P136 =>
            return "Infill location reference";
         when Track_P137 =>
            return "Stop if in Staff Responsible";
         when Track_P138 =>
            return "Reversing area information";
         when Track_P139 =>
            return "Reversing supervision information";
         when Track_P140 =>
            return "Train running number from RBC";
         when Track_P141 =>
            return "Default Gradient for Temporary Speed Restriction";
         when Track_P143 =>
            return "Session Management with neighbouring Radio Infill Unit";
         when Track_P145 =>
            return "Inhibition of balise group message consistency reaction";
         when Track_P180 =>
            return "LSSMA display toggle order";
         when Track_P181 =>
            return "Generic LS function marker";
         when Track_P254 =>
            return "Default balise, loop or RIU information";
         when Track_P255 =>
            return "End of Information";
         when Train_P0 =>
            return "Position Report";
         when Train_P1 =>
            return "Position Report based on two balise groups";
         when Train_P2 =>
            return "Onboard supported system versions";
         when Train_P4 =>
            return "Error reporting";
         when Train_P5 =>
            return "Train running number";
         when Train_P9 =>
            return "Level 2 transition information";
         when Train_P10 =>
            return "Safe consist length information for Supervised Manoeuvre";
         when Train_P11 =>
            return "Validated train data";
         when Train_P12 =>
            return "Default train data for Supervised Manoeuvre";
         when Train_P44 =>
            return "Data used by applications outside the ERTMS/ETCS system";
      end case;
   end Name;

   ------------
   -- Clause --
   ------------

   function Clause (Kind : Known_Kind_T) return String is
   begin
      case Kind is
         when Track_P0 =>
            return "7.4.2.0";
         when Track_P2 =>
            return "7.4.2.1";
         when Track_P3 =>
            return "7.4.2.1.1";
         when Track_P5 =>
            return "7.4.2.2";
         when Track_P6 =>
            return "7.4.2.2.1";
         when Track_P12 =>
            return "7.4.2.3";
         when Track_P13 =>
            return "7.4.2.3.1";
         when Track_P15 =>
            return "7.4.2.4";
         when Track_P16 =>
            return "7.4.2.5";
         when Track_P21 =>
            return "7.4.2.6";
         when Track_P27 =>
            return "7.4.2.7";
         when Track_P31 =>
            return "7.4.2.7.1";
         when Track_P32 =>
            return "7.4.2.7.2";
         when Track_P39 =>
            return "7.4.2.8";
         when Track_P40 =>
            return "7.4.2.8.1";
         when Track_P41 =>
            return "7.4.2.9";
         when Track_P42 =>
            return "7.4.2.10";
         when Track_P44 =>
            return "7.4.2.11";
         when Track_P45 =>
            return "7.4.2.11.1";
         when Track_P46 =>
            return "7.4.2.11.2";
         when Track_P49 =>
            return "7.4.2.12";
         when Track_P51 =>
            return "7.4.2.13";
         when Track_P52 =>
            return "7.4.2.13.1";
         when Track_P57 =>
            return "7.4.2.14";
         when Track_P58 =>
            return "7.4.2.15";
         when Track_P63 =>
            return "7.4.2.16";
         when Track_P64 =>
            return "7.4.2.16.1";
         when Track_P65 =>
            return "7.4.2.17";
         when Track_P66 =>
            return "7.4.2.18";
         when Track_P67 =>
            return "7.4.2.19";
         when Track_P68 =>
            return "7.4.2.20";
         when Track_P69 =>
            return "7.4.2.20.1";
         when Track_P70 =>
            return "7.4.2.21";
         when Track_P71 =>
            return "7.4.2.22";
         when Track_P73 =>
            return "7.4.2.23";
         when Track_P74 =>
            return "7.4.2.24";
         when Track_P79 =>
            return "7.4.2.25";
         when Track_P80 =>
            return "7.4.2.26";
         when Track_P88 =>
            return "7.4.2.26.1";
         when Track_P90 =>
            return "7.4.2.26.2";
         when Track_P131 =>
            return "7.4.2.27";
         when Track_P132 =>
            return "7.4.2.28";
         when Track_P133 =>
            return "7.4.2.29";
         when Track_P134 =>
            return "7.4.2.30";
         when Track_P135 =>
            return "7.4.2.31";
         when Track_P136 =>
            return "7.4.2.32";
         when Track_P137 =>
            return "7.4.2.33";
         when Track_P138 =>
            return "7.4.2.34";
         when Track_P139 =>
            return "7.4.2.35";
         when Track_P140 =>
            return "7.4.2.36";
         when Track_P141 =>
            return "7.4.2.37";
         when Track_P143 =>
            return "7.4.2.37.1";
         when Track_P145 =>
            return "7.4.2.37.2";
         when Track_P180 =>
            return "7.4.2.37.3";
         when Track_P181 =>
            return "7.4.2.37.4";
         when Track_P254 =>
            return "7.4.2.38";
         when Track_P255 =>
            return "7.4.2.39";
         when Train_P0 =>
            return "7.4.3.1";
         when Train_P1 =>
            return "7.4.3.2";
         when Train_P2 =>
            return "7.4.3.3";
         when Train_P4 =>
            return "7.4.3.4";
         when Train_P5 =>
            return "7.4.3.4.1";
         when Train_P9 =>
            return "7.4.3.4.2";
         when Train_P10 =>
            return "7.4.3.4.3";
         when Train_P11 =>
            return "7.4.3.5";
         when Train_P12 =>
            return "7.4.3.5.1";
         when Train_P44 =>
            return "7.4.3.6";
      end case;
   end Clause;

   procedure Check_Track_P0
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P0.Packet_T;
   begin
      ETCS_Track_Packets.P0.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P0.Valid (P);
   end Check_Track_P0;

   procedure Check_Track_P2
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P2.Packet_T;
   begin
      ETCS_Track_Packets.P2.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P2.Valid (P);
   end Check_Track_P2;

   procedure Check_Track_P3
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P3.Packet_T;
   begin
      ETCS_Track_Packets.P3.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P3.Valid (P);
   end Check_Track_P3;

   procedure Check_Track_P5
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P5.Packet_T;
   begin
      ETCS_Track_Packets.P5.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P5.Valid (P);
   end Check_Track_P5;

   procedure Check_Track_P6
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P6.Packet_T;
   begin
      ETCS_Track_Packets.P6.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P6.Valid (P);
   end Check_Track_P6;

   procedure Check_Track_P12
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P12.Packet_T;
   begin
      ETCS_Track_Packets.P12.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P12.Valid (P);
   end Check_Track_P12;

   procedure Check_Track_P13
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P13.Packet_T;
   begin
      ETCS_Track_Packets.P13.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P13.Valid (P);
   end Check_Track_P13;

   procedure Check_Track_P15
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P15.Packet_T;
   begin
      ETCS_Track_Packets.P15.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P15.Valid (P);
   end Check_Track_P15;

   procedure Check_Track_P16
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P16.Packet_T;
   begin
      ETCS_Track_Packets.P16.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P16.Valid (P);
   end Check_Track_P16;

   procedure Check_Track_P21
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P21.Packet_T;
   begin
      ETCS_Track_Packets.P21.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P21.Valid (P);
   end Check_Track_P21;

   procedure Check_Track_P27
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P27.Packet_T;
   begin
      ETCS_Track_Packets.P27.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P27.Valid (P);
   end Check_Track_P27;

   procedure Check_Track_P31
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P31.Packet_T;
   begin
      ETCS_Track_Packets.P31.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P31.Valid (P);
   end Check_Track_P31;

   procedure Check_Track_P32
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P32.Packet_T;
   begin
      ETCS_Track_Packets.P32.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P32.Valid (P);
   end Check_Track_P32;

   procedure Check_Track_P39
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P39.Packet_T;
   begin
      ETCS_Track_Packets.P39.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P39.Valid (P);
   end Check_Track_P39;

   procedure Check_Track_P40
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P40.Packet_T;
   begin
      ETCS_Track_Packets.P40.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P40.Valid (P);
   end Check_Track_P40;

   procedure Check_Track_P41
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P41.Packet_T;
   begin
      ETCS_Track_Packets.P41.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P41.Valid (P);
   end Check_Track_P41;

   procedure Check_Track_P42
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P42.Packet_T;
   begin
      ETCS_Track_Packets.P42.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P42.Valid (P);
   end Check_Track_P42;

   procedure Check_Track_P44
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P44.Packet_T;
   begin
      ETCS_Track_Packets.P44.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P44.Valid (P);
   end Check_Track_P44;

   procedure Check_Track_P45
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P45.Packet_T;
   begin
      ETCS_Track_Packets.P45.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P45.Valid (P);
   end Check_Track_P45;

   procedure Check_Track_P46
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P46.Packet_T;
   begin
      ETCS_Track_Packets.P46.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P46.Valid (P);
   end Check_Track_P46;

   procedure Check_Track_P49
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P49.Packet_T;
   begin
      ETCS_Track_Packets.P49.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P49.Valid (P);
   end Check_Track_P49;

   procedure Check_Track_P51
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P51.Packet_T;
   begin
      ETCS_Track_Packets.P51.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P51.Valid (P);
   end Check_Track_P51;

   procedure Check_Track_P52
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P52.Packet_T;
   begin
      ETCS_Track_Packets.P52.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P52.Valid (P);
   end Check_Track_P52;

   procedure Check_Track_P57
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P57.Packet_T;
   begin
      ETCS_Track_Packets.P57.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P57.Valid (P);
   end Check_Track_P57;

   procedure Check_Track_P58
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P58.Packet_T;
   begin
      ETCS_Track_Packets.P58.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P58.Valid (P);
   end Check_Track_P58;

   procedure Check_Track_P63
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P63.Packet_T;
   begin
      ETCS_Track_Packets.P63.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P63.Valid (P);
   end Check_Track_P63;

   procedure Check_Track_P64
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P64.Packet_T;
   begin
      ETCS_Track_Packets.P64.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P64.Valid (P);
   end Check_Track_P64;

   procedure Check_Track_P65
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P65.Packet_T;
   begin
      ETCS_Track_Packets.P65.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P65.Valid (P);
   end Check_Track_P65;

   procedure Check_Track_P66
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P66.Packet_T;
   begin
      ETCS_Track_Packets.P66.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P66.Valid (P);
   end Check_Track_P66;

   procedure Check_Track_P67
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P67.Packet_T;
   begin
      ETCS_Track_Packets.P67.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P67.Valid (P);
   end Check_Track_P67;

   procedure Check_Track_P68
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P68.Packet_T;
   begin
      ETCS_Track_Packets.P68.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P68.Valid (P);
   end Check_Track_P68;

   procedure Check_Track_P69
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P69.Packet_T;
   begin
      ETCS_Track_Packets.P69.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P69.Valid (P);
   end Check_Track_P69;

   procedure Check_Track_P70
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P70.Packet_T;
   begin
      ETCS_Track_Packets.P70.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P70.Valid (P);
   end Check_Track_P70;

   procedure Check_Track_P71
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P71.Packet_T;
   begin
      ETCS_Track_Packets.P71.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P71.Valid (P);
   end Check_Track_P71;

   procedure Check_Track_P73
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P73.Packet_T;
   begin
      ETCS_Track_Packets.P73.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P73.Valid (P);
   end Check_Track_P73;

   procedure Check_Track_P74
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P74.Packet_T;
   begin
      ETCS_Track_Packets.P74.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P74.Valid (P);
   end Check_Track_P74;

   procedure Check_Track_P79
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P79.Packet_T;
   begin
      ETCS_Track_Packets.P79.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P79.Valid (P);
   end Check_Track_P79;

   procedure Check_Track_P80
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P80.Packet_T;
   begin
      ETCS_Track_Packets.P80.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P80.Valid (P);
   end Check_Track_P80;

   procedure Check_Track_P88
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P88.Packet_T;
   begin
      ETCS_Track_Packets.P88.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P88.Valid (P);
   end Check_Track_P88;

   procedure Check_Track_P90
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P90.Packet_T;
   begin
      ETCS_Track_Packets.P90.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P90.Valid (P);
   end Check_Track_P90;

   procedure Check_Track_P131
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P131.Packet_T;
   begin
      ETCS_Track_Packets.P131.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P131.Valid (P);
   end Check_Track_P131;

   procedure Check_Track_P132
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P132.Packet_T;
   begin
      ETCS_Track_Packets.P132.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P132.Valid (P);
   end Check_Track_P132;

   procedure Check_Track_P133
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P133.Packet_T;
   begin
      ETCS_Track_Packets.P133.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P133.Valid (P);
   end Check_Track_P133;

   procedure Check_Track_P134
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P134.Packet_T;
   begin
      ETCS_Track_Packets.P134.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P134.Valid (P);
   end Check_Track_P134;

   procedure Check_Track_P135
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P135.Packet_T;
   begin
      ETCS_Track_Packets.P135.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P135.Valid (P);
   end Check_Track_P135;

   procedure Check_Track_P136
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P136.Packet_T;
   begin
      ETCS_Track_Packets.P136.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P136.Valid (P);
   end Check_Track_P136;

   procedure Check_Track_P137
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P137.Packet_T;
   begin
      ETCS_Track_Packets.P137.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P137.Valid (P);
   end Check_Track_P137;

   procedure Check_Track_P138
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P138.Packet_T;
   begin
      ETCS_Track_Packets.P138.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P138.Valid (P);
   end Check_Track_P138;

   procedure Check_Track_P139
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P139.Packet_T;
   begin
      ETCS_Track_Packets.P139.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P139.Valid (P);
   end Check_Track_P139;

   procedure Check_Track_P140
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P140.Packet_T;
   begin
      ETCS_Track_Packets.P140.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P140.Valid (P);
   end Check_Track_P140;

   procedure Check_Track_P141
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P141.Packet_T;
   begin
      ETCS_Track_Packets.P141.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P141.Valid (P);
   end Check_Track_P141;

   procedure Check_Track_P143
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P143.Packet_T;
   begin
      ETCS_Track_Packets.P143.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P143.Valid (P);
   end Check_Track_P143;

   procedure Check_Track_P145
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P145.Packet_T;
   begin
      ETCS_Track_Packets.P145.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P145.Valid (P);
   end Check_Track_P145;

   procedure Check_Track_P180
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P180.Packet_T;
   begin
      ETCS_Track_Packets.P180.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P180.Valid (P);
   end Check_Track_P180;

   procedure Check_Track_P181
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P181.Packet_T;
   begin
      ETCS_Track_Packets.P181.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P181.Valid (P);
   end Check_Track_P181;

   procedure Check_Track_P254
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P254.Packet_T;
   begin
      ETCS_Track_Packets.P254.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P254.Valid (P);
   end Check_Track_P254;

   procedure Check_Track_P255
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Track_Packets.P255.Packet_T;
   begin
      ETCS_Track_Packets.P255.Decode (R, P, OK);
      Valid := OK and then ETCS_Track_Packets.P255.Valid (P);
   end Check_Track_P255;

   procedure Check_Train_P0
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P0.Packet_T;
   begin
      ETCS_Train_Packets.P0.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P0.Valid (P);
   end Check_Train_P0;

   procedure Check_Train_P1
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P1.Packet_T;
   begin
      ETCS_Train_Packets.P1.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P1.Valid (P);
   end Check_Train_P1;

   procedure Check_Train_P2
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P2.Packet_T;
   begin
      ETCS_Train_Packets.P2.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P2.Valid (P);
   end Check_Train_P2;

   procedure Check_Train_P4
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P4.Packet_T;
   begin
      ETCS_Train_Packets.P4.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P4.Valid (P);
   end Check_Train_P4;

   procedure Check_Train_P5
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P5.Packet_T;
   begin
      ETCS_Train_Packets.P5.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P5.Valid (P);
   end Check_Train_P5;

   procedure Check_Train_P9
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P9.Packet_T;
   begin
      ETCS_Train_Packets.P9.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P9.Valid (P);
   end Check_Train_P9;

   procedure Check_Train_P10
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P10.Packet_T;
   begin
      ETCS_Train_Packets.P10.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P10.Valid (P);
   end Check_Train_P10;

   procedure Check_Train_P11
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P11.Packet_T;
   begin
      ETCS_Train_Packets.P11.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P11.Valid (P);
   end Check_Train_P11;

   procedure Check_Train_P12
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P12.Packet_T;
   begin
      ETCS_Train_Packets.P12.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P12.Valid (P);
   end Check_Train_P12;

   procedure Check_Train_P44
     (R : in out Reader; OK : out Boolean; Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK)
   is
      P : ETCS_Train_Packets.P44.Packet_T;
   begin
      ETCS_Train_Packets.P44.Decode (R, P, OK);
      Valid := OK and then ETCS_Train_Packets.P44.Valid (P);
   end Check_Train_P44;

   -----------
   -- Check --
   -----------

   procedure Check (Kind  : Known_Kind_T;
                    R     : in out Reader;
                    OK    : out Boolean;
                    Valid : out Boolean)
   is
   begin
      case Kind is
         when Track_P0 => Check_Track_P0 (R, OK, Valid);
         when Track_P2 => Check_Track_P2 (R, OK, Valid);
         when Track_P3 => Check_Track_P3 (R, OK, Valid);
         when Track_P5 => Check_Track_P5 (R, OK, Valid);
         when Track_P6 => Check_Track_P6 (R, OK, Valid);
         when Track_P12 => Check_Track_P12 (R, OK, Valid);
         when Track_P13 => Check_Track_P13 (R, OK, Valid);
         when Track_P15 => Check_Track_P15 (R, OK, Valid);
         when Track_P16 => Check_Track_P16 (R, OK, Valid);
         when Track_P21 => Check_Track_P21 (R, OK, Valid);
         when Track_P27 => Check_Track_P27 (R, OK, Valid);
         when Track_P31 => Check_Track_P31 (R, OK, Valid);
         when Track_P32 => Check_Track_P32 (R, OK, Valid);
         when Track_P39 => Check_Track_P39 (R, OK, Valid);
         when Track_P40 => Check_Track_P40 (R, OK, Valid);
         when Track_P41 => Check_Track_P41 (R, OK, Valid);
         when Track_P42 => Check_Track_P42 (R, OK, Valid);
         when Track_P44 => Check_Track_P44 (R, OK, Valid);
         when Track_P45 => Check_Track_P45 (R, OK, Valid);
         when Track_P46 => Check_Track_P46 (R, OK, Valid);
         when Track_P49 => Check_Track_P49 (R, OK, Valid);
         when Track_P51 => Check_Track_P51 (R, OK, Valid);
         when Track_P52 => Check_Track_P52 (R, OK, Valid);
         when Track_P57 => Check_Track_P57 (R, OK, Valid);
         when Track_P58 => Check_Track_P58 (R, OK, Valid);
         when Track_P63 => Check_Track_P63 (R, OK, Valid);
         when Track_P64 => Check_Track_P64 (R, OK, Valid);
         when Track_P65 => Check_Track_P65 (R, OK, Valid);
         when Track_P66 => Check_Track_P66 (R, OK, Valid);
         when Track_P67 => Check_Track_P67 (R, OK, Valid);
         when Track_P68 => Check_Track_P68 (R, OK, Valid);
         when Track_P69 => Check_Track_P69 (R, OK, Valid);
         when Track_P70 => Check_Track_P70 (R, OK, Valid);
         when Track_P71 => Check_Track_P71 (R, OK, Valid);
         when Track_P73 => Check_Track_P73 (R, OK, Valid);
         when Track_P74 => Check_Track_P74 (R, OK, Valid);
         when Track_P79 => Check_Track_P79 (R, OK, Valid);
         when Track_P80 => Check_Track_P80 (R, OK, Valid);
         when Track_P88 => Check_Track_P88 (R, OK, Valid);
         when Track_P90 => Check_Track_P90 (R, OK, Valid);
         when Track_P131 => Check_Track_P131 (R, OK, Valid);
         when Track_P132 => Check_Track_P132 (R, OK, Valid);
         when Track_P133 => Check_Track_P133 (R, OK, Valid);
         when Track_P134 => Check_Track_P134 (R, OK, Valid);
         when Track_P135 => Check_Track_P135 (R, OK, Valid);
         when Track_P136 => Check_Track_P136 (R, OK, Valid);
         when Track_P137 => Check_Track_P137 (R, OK, Valid);
         when Track_P138 => Check_Track_P138 (R, OK, Valid);
         when Track_P139 => Check_Track_P139 (R, OK, Valid);
         when Track_P140 => Check_Track_P140 (R, OK, Valid);
         when Track_P141 => Check_Track_P141 (R, OK, Valid);
         when Track_P143 => Check_Track_P143 (R, OK, Valid);
         when Track_P145 => Check_Track_P145 (R, OK, Valid);
         when Track_P180 => Check_Track_P180 (R, OK, Valid);
         when Track_P181 => Check_Track_P181 (R, OK, Valid);
         when Track_P254 => Check_Track_P254 (R, OK, Valid);
         when Track_P255 => Check_Track_P255 (R, OK, Valid);
         when Train_P0 => Check_Train_P0 (R, OK, Valid);
         when Train_P1 => Check_Train_P1 (R, OK, Valid);
         when Train_P2 => Check_Train_P2 (R, OK, Valid);
         when Train_P4 => Check_Train_P4 (R, OK, Valid);
         when Train_P5 => Check_Train_P5 (R, OK, Valid);
         when Train_P9 => Check_Train_P9 (R, OK, Valid);
         when Train_P10 => Check_Train_P10 (R, OK, Valid);
         when Train_P11 => Check_Train_P11 (R, OK, Valid);
         when Train_P12 => Check_Train_P12 (R, OK, Valid);
         when Train_P44 => Check_Train_P44 (R, OK, Valid);
      end case;
   end Check;

   ----------
   -- Skip --
   ----------

   procedure Skip (Direction : Direction_T;
                   R         : in out Reader;
                   OK        : out Boolean)
   is
      Start  : constant Natural := Position (R);
      V      : Interfaces.Unsigned_64;
      Length : Natural;
   begin
      Skip (R, 8);                   --  NID_PACKET
      if Direction = Track_To_Train then
         Skip (R, 2);                --  Q_DIR
      end if;
      Read (R, 13, V);               --  L_PACKET
      Length := Natural (V);
      OK := not Failed (R)
        and then Length >= Header_Bits (Direction)
        and then Length <= Limit (R) - Start;
      if OK then
         Seek (R, Start + Length);
         OK := not Failed (R);
      end if;
   end Skip;

end ETCS_Catalogue;
