--  ETCS on-board (EVC)
--  Packet 45, track to train: Radio Network transition order, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P45
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET    : NID_PACKET_T;
      Q_DIR         : Q_DIR_T;
      L_PACKET      : L_PACKET_T;
      Q_NETWORKTYPE : Q_NETWORKTYPE_T;
      Has_NID_MN    : Boolean;
      NID_MN        : NID_MN_T := 0;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 2, V);
      Q_NETWORKTYPE := To_Q_NETWORKTYPE (V);
      Has_NID_MN := Q_NETWORKTYPE in 1 | 2;
      if Has_NID_MN then
         Read (R, 24, V);
         NID_MN := To_NID_MN (V);
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_NETWORKTYPE => Q_NETWORKTYPE,
         Has_NID_MN => Has_NID_MN,
         NID_MN => NID_MN);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 2, Code (P.Q_NETWORKTYPE));
      if P.Has_NID_MN /= (P.Q_NETWORKTYPE in 1 | 2) then
         Good := False;
      end if;
      if P.Q_NETWORKTYPE in 1 | 2 then
         Write (W, 24, Code (P.NID_MN));
      end if;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P45;
