--  ETCS on-board (EVC)
--  The track to train packets of the ERTMS/ETCS language.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2. One child package per packet, P<NID_PACKET>:
--     P0 Virtual Balise Cover marker (7.4.2.0)
--     P2 System Version order (7.4.2.1)
--     P3 National Values (7.4.2.1.1)
--     P5 Linking (7.4.2.2)
--     P12 Level 1 Movement Authority (7.4.2.3)
--     P15 Level 2 Movement Authority (7.4.2.4)
--     P21 Gradient Profile (7.4.2.6)
--     P27 International Static Speed Profile (7.4.2.7)
--     P41 Level Transition Order (7.4.2.9)
--     P44 Data used by applications outside the ERTMS/ETCS system (7.4.2.11)
--     P65 Temporary Speed Restriction (7.4.2.17)
--     P73 Packet for sending plain text messages (7.4.2.23)
--     P136 Infill location reference (7.4.2.32)
--     P255 End of Information (7.4.2.39)

package ETCS_Track_Packets
  with SPARK_Mode => On, Pure
is
end ETCS_Track_Packets;
