--  ETCS on-board (EVC)
--  Packet 71, track to train: Adhesion factor, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P71
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.D_ADHESION)
      and then Is_Valid (P.L_ADHESION)
      and then Is_Valid (P.M_ADHESION));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      Q_DIR      : Q_DIR_T;
      L_PACKET   : L_PACKET_T;
      Q_SCALE    : Q_SCALE_T;
      D_ADHESION : D_ADHESION_T;
      L_ADHESION : L_ADHESION_T;
      M_ADHESION : M_ADHESION_T;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      D_ADHESION := To_D_ADHESION (V);
      Read (R, 15, V);
      L_ADHESION := To_L_ADHESION (V);
      Read (R, 1, V);
      M_ADHESION := To_M_ADHESION (V);
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         D_ADHESION => D_ADHESION,
         L_ADHESION => L_ADHESION,
         M_ADHESION => M_ADHESION);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_ADHESION));
      Write (W, 15, Code (P.L_ADHESION));
      Write (W, 1, Code (P.M_ADHESION));
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P71;
