--  ETCS on-board (EVC)
--  Packet 10, train to track: Safe consist length information for Supervised
--  Manoeuvre, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Train_Packets.P10
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET                  : NID_PACKET_T;
      L_PACKET                    : L_PACKET_T;
      Q_SAFECONSISTLENGTH         : Q_SAFECONSISTLENGTH_T;
      Has_L_CONSISTFRONTENGINENOM : Boolean;
      L_CONSISTFRONTENGINENOM     : L_CONSISTFRONTENGINENOM_T := 0;
      L_CONSISTFRONTENGINEMIN     : L_CONSISTFRONTENGINEMIN_T := 0;
      L_CONSISTFRONTENGINEMAX     : L_CONSISTFRONTENGINEMAX_T := 0;
      L_CONSISTREARENGINENOM      : L_CONSISTREARENGINENOM_T := 0;
      L_CONSISTREARENGINEMIN      : L_CONSISTREARENGINEMIN_T := 0;
      L_CONSISTREARENGINEMAX      : L_CONSISTREARENGINEMAX_T := 0;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 1, V);
      Q_SAFECONSISTLENGTH := To_Q_SAFECONSISTLENGTH (V);
      Has_L_CONSISTFRONTENGINENOM := Q_SAFECONSISTLENGTH = 1;
      if Has_L_CONSISTFRONTENGINENOM then
         Read (R, 12, V);
         L_CONSISTFRONTENGINENOM := To_L_CONSISTFRONTENGINENOM (V);
         Read (R, 12, V);
         L_CONSISTFRONTENGINEMIN := To_L_CONSISTFRONTENGINEMIN (V);
         Read (R, 12, V);
         L_CONSISTFRONTENGINEMAX := To_L_CONSISTFRONTENGINEMAX (V);
         Read (R, 12, V);
         L_CONSISTREARENGINENOM := To_L_CONSISTREARENGINENOM (V);
         Read (R, 12, V);
         L_CONSISTREARENGINEMIN := To_L_CONSISTREARENGINEMIN (V);
         Read (R, 12, V);
         L_CONSISTREARENGINEMAX := To_L_CONSISTREARENGINEMAX (V);
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         Q_SAFECONSISTLENGTH => Q_SAFECONSISTLENGTH,
         Has_L_CONSISTFRONTENGINENOM => Has_L_CONSISTFRONTENGINENOM,
         L_CONSISTFRONTENGINENOM => L_CONSISTFRONTENGINENOM,
         L_CONSISTFRONTENGINEMIN => L_CONSISTFRONTENGINEMIN,
         L_CONSISTFRONTENGINEMAX => L_CONSISTFRONTENGINEMAX,
         L_CONSISTREARENGINENOM => L_CONSISTREARENGINENOM,
         L_CONSISTREARENGINEMIN => L_CONSISTREARENGINEMIN,
         L_CONSISTREARENGINEMAX => L_CONSISTREARENGINEMAX);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 1, Code (P.Q_SAFECONSISTLENGTH));
      if P.Has_L_CONSISTFRONTENGINENOM /= (P.Q_SAFECONSISTLENGTH = 1) then
         Good := False;
      end if;
      if P.Q_SAFECONSISTLENGTH = 1 then
         Write (W, 12, Code (P.L_CONSISTFRONTENGINENOM));
         Write (W, 12, Code (P.L_CONSISTFRONTENGINEMIN));
         Write (W, 12, Code (P.L_CONSISTFRONTENGINEMAX));
         Write (W, 12, Code (P.L_CONSISTREARENGINENOM));
         Write (W, 12, Code (P.L_CONSISTREARENGINEMIN));
         Write (W, 12, Code (P.L_CONSISTREARENGINEMAX));
      end if;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P10;
