--  ETCS on-board (EVC)
--  Packet 44, track to train: Data used by applications outside the ERTMS/ETCS
--  system, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P44
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.NID_XUSER)
      and then (if P.Has_NID_NTC then Is_Valid (P.NID_NTC)));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      Bad   : Boolean := False;
      NID_PACKET  : NID_PACKET_T;
      Q_DIR       : Q_DIR_T;
      L_PACKET    : L_PACKET_T;
      NID_XUSER   : NID_XUSER_T;
      Has_NID_NTC : Boolean;
      NID_NTC     : NID_NTC_T := 0;
      Raw_Bits    : Raw_Bits_T := 0;
      Raw         : Raw_Data_T := (others => 0);
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 9, V);
      NID_XUSER := To_NID_XUSER (V);
      Has_NID_NTC := NID_XUSER = 102;
      if Has_NID_NTC then
         Read (R, 8, V);
         NID_NTC := To_NID_NTC (V);
      end if;
      if Position (R) <= Start + Natural (L_PACKET)
        and then Start + Natural (L_PACKET) - Position (R) <= 8191
      then
         Raw_Bits := Start + Natural (L_PACKET) - Position (R);
         Read_Bytes (R, Raw_Bits, Raw);
      else
         Bad := True;
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         NID_XUSER => NID_XUSER,
         Has_NID_NTC => Has_NID_NTC,
         NID_NTC => NID_NTC,
         Raw_Bits => Raw_Bits,
         Raw => Raw);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start)
        and then not Bad;
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 9, Code (P.NID_XUSER));
      if P.Has_NID_NTC /= (P.NID_XUSER = 102) then
         Good := False;
      end if;
      if P.NID_XUSER = 102 then
         Write (W, 8, Code (P.NID_NTC));
      end if;
      Write_Bytes (W, P.Raw_Bits, P.Raw);
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P44;
