--  ETCS on-board (EVC)
--  Packet 21, track to train: Gradient Profile, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P21
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
   begin
      P := (others => <>);
      Read (R, 8, V);
      P.NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      P.Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      P.L_PACKET := To_L_PACKET (V);
      Read (R, 2, V);
      P.Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      P.D_GRADIENT := To_D_GRADIENT (V);
      Read (R, 1, V);
      P.Q_GDIR := To_Q_GDIR (V);
      Read (R, 8, V);
      P.G_A := To_G_A (V);
      Read (R, 5, V);
      P.N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : D_GRADIENT_Item renames P.D_GRADIENT_List (I1);
         begin
            Read (R, 15, V);
            E1.D_GRADIENT := To_D_GRADIENT (V);
            Read (R, 1, V);
            E1.Q_GDIR := To_Q_GDIR (V);
            Read (R, 8, V);
            E1.G_A := To_G_A (V);
         end;
      end loop;
      OK := not Failed (R)
        and then P.NID_PACKET = NID
        and then Position (R) = Start + Natural (P.L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_GRADIENT));
      Write (W, 1, Code (P.Q_GDIR));
      Write (W, 8, Code (P.G_A));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         declare
            E1 : D_GRADIENT_Item renames P.D_GRADIENT_List (I1);
         begin
            Write (W, 15, Code (E1.D_GRADIENT));
            Write (W, 1, Code (E1.Q_GDIR));
            Write (W, 8, Code (E1.G_A));
         end;
      end loop;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P21;
