--  ETCS on-board (EVC)
--  Packet 12, track to train: Level 1 Movement Authority, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Track_Packets.P12
  with SPARK_Mode => On
is

   --  The items with every component at its default
   Empty_L_SECTION_Item : constant L_SECTION_Item := (others => <>);

   --  One item of L_SECTION_List
   procedure Decode_L_SECTION_Item
     (R  : in out Reader;
      E1 : out L_SECTION_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      E1 := Empty_L_SECTION_Item;
      Read (R, 15, V);
      E1.L_SECTION := To_L_SECTION (V);
      Read (R, 1, V);
      E1.Q_SECTIONTIMER := To_Q_SECTIONTIMER (V);
      E1.Has_T_SECTIONTIMER := E1.Q_SECTIONTIMER = 1;
      if E1.Has_T_SECTIONTIMER then
         Read (R, 10, V);
         E1.T_SECTIONTIMER := To_T_SECTIONTIMER (V);
         Read (R, 15, V);
         E1.D_SECTIONTIMERSTOPLOC := To_D_SECTIONTIMERSTOPLOC (V);
      end if;
   end Decode_L_SECTION_Item;

   --  One item of L_SECTION_List
   procedure Encode_L_SECTION_Item
     (E1   : L_SECTION_Item;
      W    : in out Writer;
      Good : in out Boolean)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 15, Code (E1.L_SECTION));
      Write (W, 1, Code (E1.Q_SECTIONTIMER));
      if E1.Has_T_SECTIONTIMER /= (E1.Q_SECTIONTIMER = 1) then
         Good := False;
      end if;
      if E1.Q_SECTIONTIMER = 1 then
         Write (W, 10, Code (E1.T_SECTIONTIMER));
         Write (W, 15, Code (E1.D_SECTIONTIMERSTOPLOC));
      end if;
   end Encode_L_SECTION_Item;

   --  Valid of one item of L_SECTION_List
   function Valid_L_SECTION_Item (E1 : L_SECTION_Item) return Boolean is
     (Is_Valid (E1.L_SECTION)
      and then Is_Valid (E1.Q_SECTIONTIMER)
      and then (if E1.Has_T_SECTIONTIMER
                then Is_Valid (E1.T_SECTIONTIMER)
                     and then Is_Valid (E1.D_SECTIONTIMERSTOPLOC)));

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.V_MAIN)
      and then Is_Valid (P.V_EMA)
      and then Is_Valid (P.T_EMA)
      and then Is_Valid (P.N_ITER)
      and then (for all I1 in 1 .. Natural (P.N_ITER) =>
                  Valid_L_SECTION_Item (P.L_SECTION_List (I1)))
      and then Is_Valid (P.L_ENDSECTION)
      and then Is_Valid (P.Q_SECTIONTIMER)
      and then (if P.Has_T_SECTIONTIMER
                then Is_Valid (P.T_SECTIONTIMER)
                     and then Is_Valid (P.D_SECTIONTIMERSTOPLOC))
      and then Is_Valid (P.Q_ENDTIMER)
      and then (if P.Has_T_ENDTIMER
                then Is_Valid (P.T_ENDTIMER)
                     and then Is_Valid (P.D_ENDTIMERSTARTLOC))
      and then Is_Valid (P.Q_DANGERPOINT)
      and then (if P.Has_D_DP
                then Is_Valid (P.D_DP)
                     and then Is_Valid (P.V_RELEASEDP))
      and then Is_Valid (P.Q_OVERLAP)
      and then (if P.Has_D_STARTOL
                then Is_Valid (P.D_STARTOL)
                     and then Is_Valid (P.T_OL)
                     and then Is_Valid (P.D_OL)
                     and then Is_Valid (P.V_RELEASEOL)));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET            : NID_PACKET_T;
      Q_DIR                 : Q_DIR_T;
      L_PACKET              : L_PACKET_T;
      Q_SCALE               : Q_SCALE_T;
      V_MAIN                : V_MAIN_T;
      V_EMA                 : V_EMA_T;
      T_EMA                 : T_EMA_T;
      N_ITER                : N_ITER_T;
      L_SECTION_List        : L_SECTION_Array;
      L_ENDSECTION          : L_ENDSECTION_T;
      Q_SECTIONTIMER        : Q_SECTIONTIMER_T;
      Has_T_SECTIONTIMER    : Boolean;
      T_SECTIONTIMER        : T_SECTIONTIMER_T := 0;
      D_SECTIONTIMERSTOPLOC : D_SECTIONTIMERSTOPLOC_T := 0;
      Q_ENDTIMER            : Q_ENDTIMER_T;
      Has_T_ENDTIMER        : Boolean;
      T_ENDTIMER            : T_ENDTIMER_T := 0;
      D_ENDTIMERSTARTLOC    : D_ENDTIMERSTARTLOC_T := 0;
      Q_DANGERPOINT         : Q_DANGERPOINT_T;
      Has_D_DP              : Boolean;
      D_DP                  : D_DP_T := 0;
      V_RELEASEDP           : V_RELEASEDP_T := 0;
      Q_OVERLAP             : Q_OVERLAP_T;
      Has_D_STARTOL         : Boolean;
      D_STARTOL             : D_STARTOL_T := 0;
      T_OL                  : T_OL_T := 0;
      D_OL                  : D_OL_T := 0;
      V_RELEASEOL           : V_RELEASEOL_T := 0;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 7, V);
      V_MAIN := To_V_MAIN (V);
      Read (R, 7, V);
      V_EMA := To_V_EMA (V);
      Read (R, 10, V);
      T_EMA := To_T_EMA (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_L_SECTION_Item (R, L_SECTION_List (I1));
      end loop;
      Read (R, 15, V);
      L_ENDSECTION := To_L_ENDSECTION (V);
      Read (R, 1, V);
      Q_SECTIONTIMER := To_Q_SECTIONTIMER (V);
      Has_T_SECTIONTIMER := Q_SECTIONTIMER = 1;
      if Has_T_SECTIONTIMER then
         Read (R, 10, V);
         T_SECTIONTIMER := To_T_SECTIONTIMER (V);
         Read (R, 15, V);
         D_SECTIONTIMERSTOPLOC := To_D_SECTIONTIMERSTOPLOC (V);
      end if;
      Read (R, 1, V);
      Q_ENDTIMER := To_Q_ENDTIMER (V);
      Has_T_ENDTIMER := Q_ENDTIMER = 1;
      if Has_T_ENDTIMER then
         Read (R, 10, V);
         T_ENDTIMER := To_T_ENDTIMER (V);
         Read (R, 15, V);
         D_ENDTIMERSTARTLOC := To_D_ENDTIMERSTARTLOC (V);
      end if;
      Read (R, 1, V);
      Q_DANGERPOINT := To_Q_DANGERPOINT (V);
      Has_D_DP := Q_DANGERPOINT = 1;
      if Has_D_DP then
         Read (R, 15, V);
         D_DP := To_D_DP (V);
         Read (R, 7, V);
         V_RELEASEDP := To_V_RELEASEDP (V);
      end if;
      Read (R, 1, V);
      Q_OVERLAP := To_Q_OVERLAP (V);
      Has_D_STARTOL := Q_OVERLAP = 1;
      if Has_D_STARTOL then
         Read (R, 15, V);
         D_STARTOL := To_D_STARTOL (V);
         Read (R, 10, V);
         T_OL := To_T_OL (V);
         Read (R, 15, V);
         D_OL := To_D_OL (V);
         Read (R, 7, V);
         V_RELEASEOL := To_V_RELEASEOL (V);
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         V_MAIN => V_MAIN,
         V_EMA => V_EMA,
         T_EMA => T_EMA,
         N_ITER => N_ITER,
         L_SECTION_List => L_SECTION_List,
         L_ENDSECTION => L_ENDSECTION,
         Q_SECTIONTIMER => Q_SECTIONTIMER,
         Has_T_SECTIONTIMER => Has_T_SECTIONTIMER,
         T_SECTIONTIMER => T_SECTIONTIMER,
         D_SECTIONTIMERSTOPLOC => D_SECTIONTIMERSTOPLOC,
         Q_ENDTIMER => Q_ENDTIMER,
         Has_T_ENDTIMER => Has_T_ENDTIMER,
         T_ENDTIMER => T_ENDTIMER,
         D_ENDTIMERSTARTLOC => D_ENDTIMERSTARTLOC,
         Q_DANGERPOINT => Q_DANGERPOINT,
         Has_D_DP => Has_D_DP,
         D_DP => D_DP,
         V_RELEASEDP => V_RELEASEDP,
         Q_OVERLAP => Q_OVERLAP,
         Has_D_STARTOL => Has_D_STARTOL,
         D_STARTOL => D_STARTOL,
         T_OL => T_OL,
         D_OL => D_OL,
         V_RELEASEOL => V_RELEASEOL);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 7, Code (P.V_MAIN));
      Write (W, 7, Code (P.V_EMA));
      Write (W, 10, Code (P.T_EMA));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_L_SECTION_Item (P.L_SECTION_List (I1), W, Good);
      end loop;
      Write (W, 15, Code (P.L_ENDSECTION));
      Write (W, 1, Code (P.Q_SECTIONTIMER));
      if P.Has_T_SECTIONTIMER /= (P.Q_SECTIONTIMER = 1) then
         Good := False;
      end if;
      if P.Q_SECTIONTIMER = 1 then
         Write (W, 10, Code (P.T_SECTIONTIMER));
         Write (W, 15, Code (P.D_SECTIONTIMERSTOPLOC));
      end if;
      Write (W, 1, Code (P.Q_ENDTIMER));
      if P.Has_T_ENDTIMER /= (P.Q_ENDTIMER = 1) then
         Good := False;
      end if;
      if P.Q_ENDTIMER = 1 then
         Write (W, 10, Code (P.T_ENDTIMER));
         Write (W, 15, Code (P.D_ENDTIMERSTARTLOC));
      end if;
      Write (W, 1, Code (P.Q_DANGERPOINT));
      if P.Has_D_DP /= (P.Q_DANGERPOINT = 1) then
         Good := False;
      end if;
      if P.Q_DANGERPOINT = 1 then
         Write (W, 15, Code (P.D_DP));
         Write (W, 7, Code (P.V_RELEASEDP));
      end if;
      Write (W, 1, Code (P.Q_OVERLAP));
      if P.Has_D_STARTOL /= (P.Q_OVERLAP = 1) then
         Good := False;
      end if;
      if P.Q_OVERLAP = 1 then
         Write (W, 15, Code (P.D_STARTOL));
         Write (W, 10, Code (P.T_OL));
         Write (W, 15, Code (P.D_OL));
         Write (W, 7, Code (P.V_RELEASEOL));
      end if;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P12;
