--  ETCS on-board (EVC)
--  Packet 11, train to track: Validated train data, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Train_Packets.P11
  with SPARK_Mode => On
is

   --  The items with every component at its default
   Empty_M_VOLTAGE_Item : constant M_VOLTAGE_Item := (others => <>);

   --  One item of M_VOLTAGE_List
   procedure Decode_M_VOLTAGE_Item
     (R  : in out Reader;
      E1 : out M_VOLTAGE_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      E1 := Empty_M_VOLTAGE_Item;
      Read (R, 4, V);
      E1.M_VOLTAGE := To_M_VOLTAGE (V);
      E1.Has_NID_CTRACTION := E1.M_VOLTAGE /= 0;
      if E1.Has_NID_CTRACTION then
         Read (R, 10, V);
         E1.NID_CTRACTION := To_NID_CTRACTION (V);
      end if;
   end Decode_M_VOLTAGE_Item;

   --  One item of M_VOLTAGE_List
   procedure Encode_M_VOLTAGE_Item
     (E1   : M_VOLTAGE_Item;
      W    : in out Writer;
      Good : in out Boolean)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 4, Code (E1.M_VOLTAGE));
      if E1.Has_NID_CTRACTION /= (E1.M_VOLTAGE /= 0) then
         Good := False;
      end if;
      if E1.M_VOLTAGE /= 0 then
         Write (W, 10, Code (E1.NID_CTRACTION));
      end if;
   end Encode_M_VOLTAGE_Item;

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET     : NID_PACKET_T;
      L_PACKET       : L_PACKET_T;
      NC_CDTRAIN     : NC_CDTRAIN_T;
      NC_TRAIN       : NC_TRAIN_T;
      L_TRAIN        : L_TRAIN_T;
      V_MAXTRAIN     : V_MAXTRAIN_T;
      M_LOADINGGAUGE : M_LOADINGGAUGE_T;
      M_AXLELOADCAT  : M_AXLELOADCAT_T;
      M_AIRTIGHT     : M_AIRTIGHT_T;
      N_AXLE         : N_AXLE_T;
      N_ITER         : N_ITER_T;
      M_VOLTAGE_List : M_VOLTAGE_Array;
      N_ITER_2       : N_ITER_T;
      NID_NTC_List   : NID_NTC_Array := (others => 0);
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 4, V);
      NC_CDTRAIN := To_NC_CDTRAIN (V);
      Read (R, 15, V);
      NC_TRAIN := To_NC_TRAIN (V);
      Read (R, 12, V);
      L_TRAIN := To_L_TRAIN (V);
      Read (R, 7, V);
      V_MAXTRAIN := To_V_MAXTRAIN (V);
      Read (R, 8, V);
      M_LOADINGGAUGE := To_M_LOADINGGAUGE (V);
      Read (R, 7, V);
      M_AXLELOADCAT := To_M_AXLELOADCAT (V);
      Read (R, 2, V);
      M_AIRTIGHT := To_M_AIRTIGHT (V);
      Read (R, 10, V);
      N_AXLE := To_N_AXLE (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_M_VOLTAGE_Item (R, M_VOLTAGE_List (I1));
      end loop;
      Read (R, 5, V);
      N_ITER_2 := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER_2) loop
         Read (R, 8, V);
         NID_NTC_List (I1) := To_NID_NTC (V);
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         NC_CDTRAIN => NC_CDTRAIN,
         NC_TRAIN => NC_TRAIN,
         L_TRAIN => L_TRAIN,
         V_MAXTRAIN => V_MAXTRAIN,
         M_LOADINGGAUGE => M_LOADINGGAUGE,
         M_AXLELOADCAT => M_AXLELOADCAT,
         M_AIRTIGHT => M_AIRTIGHT,
         N_AXLE => N_AXLE,
         N_ITER => N_ITER,
         M_VOLTAGE_List => M_VOLTAGE_List,
         N_ITER_2 => N_ITER_2,
         NID_NTC_List => NID_NTC_List);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 4, Code (P.NC_CDTRAIN));
      Write (W, 15, Code (P.NC_TRAIN));
      Write (W, 12, Code (P.L_TRAIN));
      Write (W, 7, Code (P.V_MAXTRAIN));
      Write (W, 8, Code (P.M_LOADINGGAUGE));
      Write (W, 7, Code (P.M_AXLELOADCAT));
      Write (W, 2, Code (P.M_AIRTIGHT));
      Write (W, 10, Code (P.N_AXLE));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_M_VOLTAGE_Item (P.M_VOLTAGE_List (I1), W, Good);
      end loop;
      Write (W, 5, Code (P.N_ITER_2));
      for I1 in 1 .. Natural (P.N_ITER_2) loop
         Write (W, 8, Code (P.NID_NTC_List (I1)));
      end loop;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P11;
