--  ETCS on-board (EVC)
--  The track to train packets of the ERTMS/ETCS language.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2. One child package per packet, P<NID_PACKET>:
--     P0 Virtual Balise Cover marker (7.4.2.0)
--     P2 System Version order (7.4.2.1)
--     P3 National Values (7.4.2.1.1)
--     P5 Linking (7.4.2.2)
--     P6 Virtual Balise Cover order (7.4.2.2.1)
--     P12 Level 1 Movement Authority (7.4.2.3)
--     P13 Staff Responsible distance Information from loop (7.4.2.3.1)
--     P15 Level 2 Movement Authority (7.4.2.4)
--     P16 Repositioning Information (7.4.2.5)
--     P21 Gradient Profile (7.4.2.6)
--     P27 International Static Speed Profile (7.4.2.7)
--     P31 RBC transition order for RBC interfaced to FRMCS only (7.4.2.7.1)
--     P32 Session Management for RBC interfaced to FRMCS only (7.4.2.7.2)
--     P39 Track Condition Change of traction system (7.4.2.8)
--     P40 Track Condition Change of allowed current consumption (7.4.2.8.1)
--     P41 Level Transition Order (7.4.2.9)
--     P42 Session Management for RBC interfaced to GSM-R (7.4.2.10)
--     P44 Data used by applications outside the ERTMS/ETCS system (7.4.2.11)
--     P45 Radio Network transition order (7.4.2.11.1)
--     P46 Conditional Level Transition Order (7.4.2.11.2)
--     P49 List of Balise Groups for SH Area (7.4.2.12)
--     P51 Axle Load Speed Profile (7.4.2.13)
--     P52 Permitted Braking Distance Information (7.4.2.13.1)
--     P57 Movement Authority Request Parameters (7.4.2.14)
--     P58 Position Report Parameters (7.4.2.15)
--     P63 List of Balise Groups in SR Authority (7.4.2.16)
--     P64 Inhibition of revocable TSRs from balises in level 2 (7.4.2.16.1)
--     P65 Temporary Speed Restriction (7.4.2.17)
--     P66 Temporary Speed Restriction Revocation (7.4.2.18)
--     P67 Track Condition Big Metal Masses (7.4.2.19)
--     P68 Track Condition (7.4.2.20)
--     P69 Track Condition Station Platforms (7.4.2.20.1)
--     P70 Route Suitability Data (7.4.2.21)
--     P71 Adhesion factor (7.4.2.22)
--     P73 Packet for sending plain text messages (7.4.2.23)
--     P74 Packet for sending fixed text messages (7.4.2.24)
--     P79 Geographical Position Information (7.4.2.25)
--     P80 Mode profile (7.4.2.26)
--     P88 Level Crossing information (7.4.2.26.1)
--     P90 Track Ahead Free up to level 2 transition location (7.4.2.26.2)
--     P131 RBC transition order for RBC interfaced to GSM-R (7.4.2.27)
--     P132 Danger for Shunting information (7.4.2.28)
--     P133 Radio infill area information (7.4.2.29)
--     P134 EOLM Packet (7.4.2.30)
--     P135 Stop Shunting on desk opening (7.4.2.31)
--     P136 Infill location reference (7.4.2.32)
--     P137 Stop if in Staff Responsible (7.4.2.33)
--     P138 Reversing area information (7.4.2.34)
--     P139 Reversing supervision information (7.4.2.35)
--     P140 Train running number from RBC (7.4.2.36)
--     P141 Default Gradient for Temporary Speed Restriction (7.4.2.37)
--     P143 Session Management with neighbouring Radio Infill Unit (7.4.2.37.1)
--     P145 Inhibition of balise group message consistency reaction
--     (7.4.2.37.2)
--     P180 LSSMA display toggle order (7.4.2.37.3)
--     P181 Generic LS function marker (7.4.2.37.4)
--     P254 Default balise, loop or RIU information (7.4.2.38)
--     P255 End of Information (7.4.2.39)
--
--  The standard header of 7.3.3.2 (NID_PACKET, Q_DIR, L_PACKET) is
--  read, written and checked here once for every child that has
--  it; a child keeps the header fields in its own record.

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;
with Interfaces;     use Interfaces;

package ETCS_Track_Packets
  with SPARK_Mode => On, Pure
is

   --  The header fields at the position of the reader
   procedure Decode_Header (R          : in out Reader;
                            NID_PACKET : out NID_PACKET_T;
                            Q_DIR      : out Q_DIR_T;
                            L_PACKET   : out L_PACKET_T)
     with Global => null,
          Post => Limit (R) = Limit (R)'Old;

   --  What Decode checks after the fields: the reader did not fail,
   --  the packet is the one expected (NID) and exactly L_PACKET
   --  bits were read from Start, the position before the header
   function Header_OK (R          : Reader;
                       NID_PACKET : NID_PACKET_T;
                       NID        : Natural;
                       L_PACKET   : L_PACKET_T;
                       Start      : Bit_Count) return Boolean is
     (not Failed (R)
      and then Natural (NID_PACKET) = NID
      and then Position (R) = Start + Natural (L_PACKET));

   --  NID_PACKET, Q_DIR and a place holder for L_PACKET, patched by
   --  Finish_Length once the packet is written; Length_At is the
   --  bit position of the place holder
   procedure Encode_Header (W         : in out Writer;
                            NID       : Unsigned_64;
                            Q_DIR     : Unsigned_64;
                            Length_At : out Natural)
     with Global => null,
          Pre => Fits (NID, 8) and then Fits (Q_DIR, 2);

   --  L_PACKET := the bits written since Start (the position
   --  before the header); Good becomes False when they do not fit
   procedure Finish_Length (W         : in out Writer;
                            Start     : Bit_Count;
                            Length_At : Natural;
                            Good      : in out Boolean)
     with Global => null;

end ETCS_Track_Packets;
