--  ETCS on-board (EVC)
--  The variables of the ERTMS/ETCS language, SUBSET-026 7.5.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  One integer type per variable over the codes of its bits (two's
--  complement where 7.5 says so), the special values as named
--  constants, To_<variable> from the bits read (ETCS_Bits) and
--  Code back, Is_Valid: the code is a value of 7.5 (min .. max or a
--  special value), not a spare one. Bits (V) and Max (V) give the
--  length and the largest meaningful code of every variable.

with Interfaces; use Interfaces;
with ETCS_Bits;  use ETCS_Bits;

package ETCS_Variables
  with SPARK_Mode => On, Pure
is

   --  Is_Valid of a variable without spare codes is True
   pragma Warnings (Off, "formal parameter ""X"" is not referenced");
   pragma Warnings (GNATprove, Off, "unused variable ""X""",
                    Reason => "Is_Valid without spare codes");

   type Variable_T is
     (A_NVMAXREDADH1,
      A_NVMAXREDADH2,
      A_NVMAXREDADH3,
      A_NVP12,
      A_NVP23,
      D_DP,
      D_EMERGENCYSTOP,
      D_ENDTIMERSTARTLOC,
      D_GRADIENT,
      D_LEVELTR,
      D_LINK,
      D_LRBG,
      D_NVOVTRP,
      D_NVPOTRP,
      D_NVROLL,
      D_NVSTFF,
      D_OL,
      D_REF,
      D_SECTIONTIMERSTOPLOC,
      D_SR,
      D_STARTOL,
      D_STATIC,
      D_TAFDISPLAY,
      D_TEXTDISPLAY,
      D_TSR,
      D_VALIDNV,
      G_A,
      L_ACKLEVELTR,
      L_DOUBTOVER,
      L_DOUBTUNDER,
      L_ENDSECTION,
      L_MESSAGE,
      L_NVKRINT,
      L_PACKET,
      L_SECTION,
      L_TAFDISPLAY,
      L_TEXT,
      L_TEXTDISPLAY,
      L_TRAININT,
      L_TSR,
      M_ACK,
      M_DUP,
      M_ERROR,
      M_LEVEL,
      M_LEVELTEXTDISPLAY,
      M_LEVELTR,
      M_MCOUNT,
      M_MODE,
      M_MODETEXTDISPLAY,
      M_NVAVADH,
      M_NVCONTACT,
      M_NVDERUN,
      M_NVEBCL,
      M_NVKRINT,
      M_NVKTINT,
      M_NVKVINT,
      M_VERSION,
      NC_CDDIFF,
      NC_DIFF,
      NID_BG,
      NID_C,
      NID_EM,
      NID_ENGINE,
      NID_MESSAGE,
      NID_NTC,
      NID_OPERATIONAL,
      NID_PACKET,
      NID_RBC,
      NID_TEXTMESSAGE,
      NID_TSR,
      NID_VBCMK,
      NID_XUSER,
      N_ITER,
      N_PIG,
      N_TOTAL,
      Q_CONFTEXTDISPLAY,
      Q_DANGERPOINT,
      Q_DESK,
      Q_DIFF,
      Q_DIR,
      Q_DIRLRBG,
      Q_DIRTRAIN,
      Q_DLRBG,
      Q_EMERGENCYSTOP,
      Q_ENDTIMER,
      Q_FRONT,
      Q_GDIR,
      Q_INFILL,
      Q_INTEGRITY,
      Q_LINK,
      Q_LINKORIENTATION,
      Q_LINKREACTION,
      Q_LOCACC,
      Q_MARQSTREASON,
      Q_MEDIA,
      Q_NEWCOUNTRY,
      Q_NVDRIVER_ADHES,
      Q_NVEMRRLS,
      Q_NVGUIPERM,
      Q_NVINHSMICPERM,
      Q_NVKINT,
      Q_NVKVINTSET,
      Q_NVLOCACC,
      Q_NVSBFBPERM,
      Q_NVSBTSMPERM,
      Q_ORIENTATION,
      Q_OVERLAP,
      Q_SCALE,
      Q_SECTIONTIMER,
      Q_STATUSLRBG,
      Q_TEXTCLASS,
      Q_TEXTCONFIRM,
      Q_TEXTDISPLAY,
      Q_TEXTREPORT,
      Q_UPDOWN,
      T_EMA,
      T_ENDTIMER,
      T_NVCONTACT,
      T_NVOVTRP,
      T_OL,
      T_SECTIONTIMER,
      T_TEXTDISPLAY,
      T_TRAIN,
      V_DIFF,
      V_EMA,
      V_MAIN,
      V_NVALLOWOVTRP,
      V_NVKVINT,
      V_NVLIMSUPERV,
      V_NVONSIGHT,
      V_NVREL,
      V_NVSHUNT,
      V_NVSTFF,
      V_NVSUPOVTRP,
      V_NVUNFIT,
      V_RELEASEDP,
      V_RELEASEOL,
      V_SM,
      V_STATIC,
      V_TRAIN,
      V_TSR,
      X_TEXT);

   --  The length of every variable, in bits
   Bits : constant array (Variable_T) of Width :=
     (A_NVMAXREDADH1 => 6,
      A_NVMAXREDADH2 => 6,
      A_NVMAXREDADH3 => 6,
      A_NVP12 => 6,
      A_NVP23 => 6,
      D_DP => 15,
      D_EMERGENCYSTOP => 15,
      D_ENDTIMERSTARTLOC => 15,
      D_GRADIENT => 15,
      D_LEVELTR => 15,
      D_LINK => 15,
      D_LRBG => 15,
      D_NVOVTRP => 15,
      D_NVPOTRP => 15,
      D_NVROLL => 15,
      D_NVSTFF => 15,
      D_OL => 15,
      D_REF => 16,
      D_SECTIONTIMERSTOPLOC => 15,
      D_SR => 15,
      D_STARTOL => 15,
      D_STATIC => 15,
      D_TAFDISPLAY => 15,
      D_TEXTDISPLAY => 15,
      D_TSR => 15,
      D_VALIDNV => 15,
      G_A => 8,
      L_ACKLEVELTR => 15,
      L_DOUBTOVER => 15,
      L_DOUBTUNDER => 15,
      L_ENDSECTION => 15,
      L_MESSAGE => 10,
      L_NVKRINT => 5,
      L_PACKET => 13,
      L_SECTION => 15,
      L_TAFDISPLAY => 15,
      L_TEXT => 8,
      L_TEXTDISPLAY => 15,
      L_TRAININT => 15,
      L_TSR => 15,
      M_ACK => 1,
      M_DUP => 2,
      M_ERROR => 8,
      M_LEVEL => 3,
      M_LEVELTEXTDISPLAY => 3,
      M_LEVELTR => 3,
      M_MCOUNT => 8,
      M_MODE => 5,
      M_MODETEXTDISPLAY => 4,
      M_NVAVADH => 5,
      M_NVCONTACT => 2,
      M_NVDERUN => 1,
      M_NVEBCL => 4,
      M_NVKRINT => 5,
      M_NVKTINT => 5,
      M_NVKVINT => 7,
      M_VERSION => 7,
      NC_CDDIFF => 4,
      NC_DIFF => 4,
      NID_BG => 14,
      NID_C => 10,
      NID_EM => 4,
      NID_ENGINE => 24,
      NID_MESSAGE => 8,
      NID_NTC => 8,
      NID_OPERATIONAL => 32,
      NID_PACKET => 8,
      NID_RBC => 14,
      NID_TEXTMESSAGE => 8,
      NID_TSR => 8,
      NID_VBCMK => 6,
      NID_XUSER => 9,
      N_ITER => 5,
      N_PIG => 3,
      N_TOTAL => 3,
      Q_CONFTEXTDISPLAY => 1,
      Q_DANGERPOINT => 1,
      Q_DESK => 1,
      Q_DIFF => 2,
      Q_DIR => 2,
      Q_DIRLRBG => 2,
      Q_DIRTRAIN => 2,
      Q_DLRBG => 2,
      Q_EMERGENCYSTOP => 2,
      Q_ENDTIMER => 1,
      Q_FRONT => 1,
      Q_GDIR => 1,
      Q_INFILL => 1,
      Q_INTEGRITY => 2,
      Q_LINK => 1,
      Q_LINKORIENTATION => 1,
      Q_LINKREACTION => 2,
      Q_LOCACC => 6,
      Q_MARQSTREASON => 5,
      Q_MEDIA => 1,
      Q_NEWCOUNTRY => 1,
      Q_NVDRIVER_ADHES => 1,
      Q_NVEMRRLS => 1,
      Q_NVGUIPERM => 1,
      Q_NVINHSMICPERM => 1,
      Q_NVKINT => 1,
      Q_NVKVINTSET => 2,
      Q_NVLOCACC => 6,
      Q_NVSBFBPERM => 1,
      Q_NVSBTSMPERM => 1,
      Q_ORIENTATION => 1,
      Q_OVERLAP => 1,
      Q_SCALE => 2,
      Q_SECTIONTIMER => 1,
      Q_STATUSLRBG => 2,
      Q_TEXTCLASS => 2,
      Q_TEXTCONFIRM => 2,
      Q_TEXTDISPLAY => 1,
      Q_TEXTREPORT => 1,
      Q_UPDOWN => 1,
      T_EMA => 10,
      T_ENDTIMER => 10,
      T_NVCONTACT => 8,
      T_NVOVTRP => 8,
      T_OL => 10,
      T_SECTIONTIMER => 10,
      T_TEXTDISPLAY => 10,
      T_TRAIN => 32,
      V_DIFF => 7,
      V_EMA => 7,
      V_MAIN => 7,
      V_NVALLOWOVTRP => 7,
      V_NVKVINT => 7,
      V_NVLIMSUPERV => 7,
      V_NVONSIGHT => 7,
      V_NVREL => 7,
      V_NVSHUNT => 7,
      V_NVSTFF => 7,
      V_NVSUPOVTRP => 7,
      V_NVUNFIT => 7,
      V_RELEASEDP => 7,
      V_RELEASEOL => 7,
      V_SM => 7,
      V_STATIC => 7,
      V_TRAIN => 7,
      V_TSR => 7,
      X_TEXT => 8);

   --  The largest meaningful code (special values aside)
   Max : constant array (Variable_T) of Unsigned_64 :=
     (A_NVMAXREDADH1 => 60,
      A_NVMAXREDADH2 => 60,
      A_NVMAXREDADH3 => 60,
      A_NVP12 => 63,
      A_NVP23 => 63,
      D_DP => 32767,
      D_EMERGENCYSTOP => 32767,
      D_ENDTIMERSTARTLOC => 32767,
      D_GRADIENT => 32767,
      D_LEVELTR => 32766,
      D_LINK => 32767,
      D_LRBG => 32766,
      D_NVOVTRP => 32767,
      D_NVPOTRP => 32767,
      D_NVROLL => 32766,
      D_NVSTFF => 32766,
      D_OL => 32767,
      D_REF => 32767,
      D_SECTIONTIMERSTOPLOC => 32767,
      D_SR => 32766,
      D_STARTOL => 32767,
      D_STATIC => 32767,
      D_TAFDISPLAY => 32767,
      D_TEXTDISPLAY => 32766,
      D_TSR => 32767,
      D_VALIDNV => 32766,
      G_A => 254,
      L_ACKLEVELTR => 32767,
      L_DOUBTOVER => 32766,
      L_DOUBTUNDER => 32766,
      L_ENDSECTION => 32767,
      L_MESSAGE => 1023,
      L_NVKRINT => 31,
      L_PACKET => 8191,
      L_SECTION => 32767,
      L_TAFDISPLAY => 32767,
      L_TEXT => 255,
      L_TEXTDISPLAY => 32766,
      L_TRAININT => 32767,
      L_TSR => 32767,
      M_ACK => 1,
      M_DUP => 2,
      M_ERROR => 10,
      M_LEVEL => 3,
      M_LEVELTEXTDISPLAY => 4,
      M_LEVELTR => 3,
      M_MCOUNT => 253,
      M_MODE => 17,
      M_MODETEXTDISPLAY => 15,
      M_NVAVADH => 20,
      M_NVCONTACT => 2,
      M_NVDERUN => 1,
      M_NVEBCL => 9,
      M_NVKRINT => 31,
      M_NVKTINT => 31,
      M_NVKVINT => 127,
      M_VERSION => 127,
      NC_CDDIFF => 10,
      NC_DIFF => 2,
      NID_BG => 16382,
      NID_C => 1023,
      NID_EM => 15,
      NID_ENGINE => 16777215,
      NID_MESSAGE => 255,
      NID_NTC => 255,
      NID_OPERATIONAL => 4294967295,
      NID_PACKET => 255,
      NID_RBC => 16382,
      NID_TEXTMESSAGE => 255,
      NID_TSR => 255,
      NID_VBCMK => 63,
      NID_XUSER => 511,
      N_ITER => 31,
      N_PIG => 7,
      N_TOTAL => 7,
      Q_CONFTEXTDISPLAY => 1,
      Q_DANGERPOINT => 1,
      Q_DESK => 1,
      Q_DIFF => 2,
      Q_DIR => 2,
      Q_DIRLRBG => 2,
      Q_DIRTRAIN => 2,
      Q_DLRBG => 2,
      Q_EMERGENCYSTOP => 3,
      Q_ENDTIMER => 1,
      Q_FRONT => 1,
      Q_GDIR => 1,
      Q_INFILL => 1,
      Q_INTEGRITY => 3,
      Q_LINK => 1,
      Q_LINKORIENTATION => 1,
      Q_LINKREACTION => 2,
      Q_LOCACC => 63,
      Q_MARQSTREASON => 31,
      Q_MEDIA => 1,
      Q_NEWCOUNTRY => 1,
      Q_NVDRIVER_ADHES => 1,
      Q_NVEMRRLS => 1,
      Q_NVGUIPERM => 1,
      Q_NVINHSMICPERM => 1,
      Q_NVKINT => 1,
      Q_NVKVINTSET => 1,
      Q_NVLOCACC => 63,
      Q_NVSBFBPERM => 1,
      Q_NVSBTSMPERM => 1,
      Q_ORIENTATION => 1,
      Q_OVERLAP => 1,
      Q_SCALE => 2,
      Q_SECTIONTIMER => 1,
      Q_STATUSLRBG => 2,
      Q_TEXTCLASS => 1,
      Q_TEXTCONFIRM => 3,
      Q_TEXTDISPLAY => 1,
      Q_TEXTREPORT => 1,
      Q_UPDOWN => 1,
      T_EMA => 1022,
      T_ENDTIMER => 1022,
      T_NVCONTACT => 254,
      T_NVOVTRP => 255,
      T_OL => 1022,
      T_SECTIONTIMER => 1022,
      T_TEXTDISPLAY => 1022,
      T_TRAIN => 4294967294,
      V_DIFF => 120,
      V_EMA => 120,
      V_MAIN => 120,
      V_NVALLOWOVTRP => 120,
      V_NVKVINT => 120,
      V_NVLIMSUPERV => 120,
      V_NVONSIGHT => 120,
      V_NVREL => 120,
      V_NVSHUNT => 120,
      V_NVSTFF => 120,
      V_NVSUPOVTRP => 120,
      V_NVUNFIT => 120,
      V_RELEASEDP => 120,
      V_RELEASEOL => 120,
      V_SM => 120,
      V_STATIC => 120,
      V_TRAIN => 120,
      V_TSR => 120,
      X_TEXT => 255);

   --  A_NVMAXREDADH1, 7.5.0.1: 6 bits, 0 .. 60, 0.05 m/s2
   type A_NVMAXREDADH1_T is range 0 .. 63;
   A_NVMAXREDADH1_No_Maximum_Display_Target : constant A_NVMAXREDADH1_T := 61;
   --  61: no maximum, display target
   A_NVMAXREDADH1_No_Maximum_Display_Time : constant A_NVMAXREDADH1_T := 62;
   --  62: no maximum, display time
   A_NVMAXREDADH1_No_Maximum_No_Display : constant A_NVMAXREDADH1_T := 63;
   --  63: no maximum, no display
   function To_A_NVMAXREDADH1 (V : Unsigned_64) return A_NVMAXREDADH1_T is
     (A_NVMAXREDADH1_T (V))
     with Pre => Fits (V, 6);
   function Code (X : A_NVMAXREDADH1_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : A_NVMAXREDADH1_T) return Boolean is
     (True);

   --  A_NVMAXREDADH2, 7.5.0.2: 6 bits, 0 .. 60, 0.05 m/s2
   type A_NVMAXREDADH2_T is range 0 .. 63;
   A_NVMAXREDADH2_No_Maximum_Display_Target : constant A_NVMAXREDADH2_T := 61;
   --  61: no maximum, display target
   A_NVMAXREDADH2_No_Maximum_Display_Time : constant A_NVMAXREDADH2_T := 62;
   --  62: no maximum, display time
   A_NVMAXREDADH2_No_Maximum_No_Display : constant A_NVMAXREDADH2_T := 63;
   --  63: no maximum, no display
   function To_A_NVMAXREDADH2 (V : Unsigned_64) return A_NVMAXREDADH2_T is
     (A_NVMAXREDADH2_T (V))
     with Pre => Fits (V, 6);
   function Code (X : A_NVMAXREDADH2_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : A_NVMAXREDADH2_T) return Boolean is
     (True);

   --  A_NVMAXREDADH3, 7.5.0.3: 6 bits, 0 .. 60, 0.05 m/s2
   type A_NVMAXREDADH3_T is range 0 .. 63;
   A_NVMAXREDADH3_No_Maximum_Display_Target : constant A_NVMAXREDADH3_T := 61;
   --  61: no maximum, display target
   A_NVMAXREDADH3_No_Maximum_Display_Time : constant A_NVMAXREDADH3_T := 62;
   --  62: no maximum, display time
   A_NVMAXREDADH3_No_Maximum_No_Display : constant A_NVMAXREDADH3_T := 63;
   --  63: no maximum, no display
   function To_A_NVMAXREDADH3 (V : Unsigned_64) return A_NVMAXREDADH3_T is
     (A_NVMAXREDADH3_T (V))
     with Pre => Fits (V, 6);
   function Code (X : A_NVMAXREDADH3_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : A_NVMAXREDADH3_T) return Boolean is
     (True);

   --  A_NVP12, 7.5.0.4: 6 bits, 0 .. 63, 0.05 m/s2
   type A_NVP12_T is range 0 .. 63;
   function To_A_NVP12 (V : Unsigned_64) return A_NVP12_T is
     (A_NVP12_T (V))
     with Pre => Fits (V, 6);
   function Code (X : A_NVP12_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : A_NVP12_T) return Boolean is
     (True);

   --  A_NVP23, 7.5.0.5: 6 bits, 0 .. 63, 0.05 m/s2
   type A_NVP23_T is range 0 .. 63;
   function To_A_NVP23 (V : Unsigned_64) return A_NVP23_T is
     (A_NVP23_T (V))
     with Pre => Fits (V, 6);
   function Code (X : A_NVP23_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : A_NVP23_T) return Boolean is
     (True);

   --  D_DP, 7.5.1.4: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_DP_T is range 0 .. 32767;
   function To_D_DP (V : Unsigned_64) return D_DP_T is
     (D_DP_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_DP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_DP_T) return Boolean is
     (True);

   --  D_EMERGENCYSTOP, 7.5.1.5: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_EMERGENCYSTOP_T is range 0 .. 32767;
   function To_D_EMERGENCYSTOP (V : Unsigned_64) return D_EMERGENCYSTOP_T is
     (D_EMERGENCYSTOP_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_EMERGENCYSTOP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_EMERGENCYSTOP_T) return Boolean is
     (True);

   --  D_ENDTIMERSTARTLOC, 7.5.1.6: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_ENDTIMERSTARTLOC_T is range 0 .. 32767;
   function To_D_ENDTIMERSTARTLOC (V : Unsigned_64)
     return D_ENDTIMERSTARTLOC_T
   is (D_ENDTIMERSTARTLOC_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_ENDTIMERSTARTLOC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_ENDTIMERSTARTLOC_T) return Boolean is
     (True);

   --  D_GRADIENT, 7.5.1.7: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_GRADIENT_T is range 0 .. 32767;
   function To_D_GRADIENT (V : Unsigned_64) return D_GRADIENT_T is
     (D_GRADIENT_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_GRADIENT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_GRADIENT_T) return Boolean is
     (True);

   --  D_LEVELTR, 7.5.1.9: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_LEVELTR_T is range 0 .. 32767;
   D_LEVELTR_Now : constant D_LEVELTR_T := 32767;
   --  32767: now
   function To_D_LEVELTR (V : Unsigned_64) return D_LEVELTR_T is
     (D_LEVELTR_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_LEVELTR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_LEVELTR_T) return Boolean is
     (True);

   --  D_LINK, 7.5.1.10: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_LINK_T is range 0 .. 32767;
   function To_D_LINK (V : Unsigned_64) return D_LINK_T is
     (D_LINK_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_LINK_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_LINK_T) return Boolean is
     (True);

   --  D_LRBG, 7.5.1.13: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_LRBG_T is range 0 .. 32767;
   D_LRBG_Unknown : constant D_LRBG_T := 32767;
   --  32767: unknown
   function To_D_LRBG (V : Unsigned_64) return D_LRBG_T is
     (D_LRBG_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_LRBG_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_LRBG_T) return Boolean is
     (True);

   --  D_NVOVTRP, 7.5.1.15: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_NVOVTRP_T is range 0 .. 32767;
   function To_D_NVOVTRP (V : Unsigned_64) return D_NVOVTRP_T is
     (D_NVOVTRP_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_NVOVTRP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_NVOVTRP_T) return Boolean is
     (True);

   --  D_NVPOTRP, 7.5.1.16: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_NVPOTRP_T is range 0 .. 32767;
   function To_D_NVPOTRP (V : Unsigned_64) return D_NVPOTRP_T is
     (D_NVPOTRP_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_NVPOTRP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_NVPOTRP_T) return Boolean is
     (True);

   --  D_NVROLL, 7.5.1.17: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_NVROLL_T is range 0 .. 32767;
   D_NVROLL_Infinite : constant D_NVROLL_T := 32767;
   --  32767: infinite
   function To_D_NVROLL (V : Unsigned_64) return D_NVROLL_T is
     (D_NVROLL_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_NVROLL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_NVROLL_T) return Boolean is
     (True);

   --  D_NVSTFF, 7.5.1.18: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_NVSTFF_T is range 0 .. 32767;
   D_NVSTFF_Infinite : constant D_NVSTFF_T := 32767;
   --  32767: infinite
   function To_D_NVSTFF (V : Unsigned_64) return D_NVSTFF_T is
     (D_NVSTFF_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_NVSTFF_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_NVSTFF_T) return Boolean is
     (True);

   --  D_OL, 7.5.1.19: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_OL_T is range 0 .. 32767;
   function To_D_OL (V : Unsigned_64) return D_OL_T is
     (D_OL_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_OL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_OL_T) return Boolean is
     (True);

   --  D_REF, 7.5.1.22: 16 bits, two's complement, -32768 .. 32767, resolution
   --  by Q_SCALE, two's complement, positive in the nominal direction of the
   --  LRBG
   type D_REF_T is range -32768 .. 32767;
   function To_D_REF (V : Unsigned_64) return D_REF_T is
     (if V >= 32768 then D_REF_T (Integer_64 (V) - 65536) else D_REF_T (V))
     with Pre => Fits (V, 16);
   function Code (X : D_REF_T) return Unsigned_64 is
     (if X < 0 then Unsigned_64 (Integer_64 (X) + 65536) else Unsigned_64 (X))
     with Post => Fits (Code'Result, 16);
   function Is_Valid (X : D_REF_T) return Boolean is
     (True);

   --  D_SECTIONTIMERSTOPLOC, 7.5.1.24: 15 bits, 0 .. 32767, resolution by
   --  Q_SCALE
   type D_SECTIONTIMERSTOPLOC_T is range 0 .. 32767;
   function To_D_SECTIONTIMERSTOPLOC (V : Unsigned_64)
     return D_SECTIONTIMERSTOPLOC_T
   is (D_SECTIONTIMERSTOPLOC_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_SECTIONTIMERSTOPLOC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_SECTIONTIMERSTOPLOC_T) return Boolean is
     (True);

   --  D_SR, 7.5.1.25: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_SR_T is range 0 .. 32767;
   D_SR_Infinite : constant D_SR_T := 32767;
   --  32767: infinite
   function To_D_SR (V : Unsigned_64) return D_SR_T is
     (D_SR_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_SR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_SR_T) return Boolean is
     (True);

   --  D_STARTOL, 7.5.1.26: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_STARTOL_T is range 0 .. 32767;
   function To_D_STARTOL (V : Unsigned_64) return D_STARTOL_T is
     (D_STARTOL_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_STARTOL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_STARTOL_T) return Boolean is
     (True);

   --  D_STATIC, 7.5.1.28: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_STATIC_T is range 0 .. 32767;
   function To_D_STATIC (V : Unsigned_64) return D_STATIC_T is
     (D_STATIC_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_STATIC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_STATIC_T) return Boolean is
     (True);

   --  D_TAFDISPLAY, 7.5.1.30: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_TAFDISPLAY_T is range 0 .. 32767;
   function To_D_TAFDISPLAY (V : Unsigned_64) return D_TAFDISPLAY_T is
     (D_TAFDISPLAY_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_TAFDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_TAFDISPLAY_T) return Boolean is
     (True);

   --  D_TEXTDISPLAY, 7.5.1.31: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_TEXTDISPLAY_T is range 0 .. 32767;
   D_TEXTDISPLAY_No_Location : constant D_TEXTDISPLAY_T := 32767;
   --  32767: no location
   function To_D_TEXTDISPLAY (V : Unsigned_64) return D_TEXTDISPLAY_T is
     (D_TEXTDISPLAY_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_TEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_TEXTDISPLAY_T) return Boolean is
     (True);

   --  D_TSR, 7.5.1.35: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type D_TSR_T is range 0 .. 32767;
   function To_D_TSR (V : Unsigned_64) return D_TSR_T is
     (D_TSR_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_TSR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_TSR_T) return Boolean is
     (True);

   --  D_VALIDNV, 7.5.1.36: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type D_VALIDNV_T is range 0 .. 32767;
   D_VALIDNV_Now : constant D_VALIDNV_T := 32767;
   --  32767: now
   function To_D_VALIDNV (V : Unsigned_64) return D_VALIDNV_T is
     (D_VALIDNV_T (V))
     with Pre => Fits (V, 15);
   function Code (X : D_VALIDNV_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : D_VALIDNV_T) return Boolean is
     (True);

   --  G_A, 7.5.1.37: 8 bits, 0 .. 254, 1 permil
   type G_A_T is range 0 .. 255;
   G_A_End_Of_Description : constant G_A_T := 255;
   --  255: end of description
   function To_G_A (V : Unsigned_64) return G_A_T is
     (G_A_T (V))
     with Pre => Fits (V, 8);
   function Code (X : G_A_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : G_A_T) return Boolean is
     (True);

   --  L_ACKLEVELTR, 7.5.1.39: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type L_ACKLEVELTR_T is range 0 .. 32767;
   function To_L_ACKLEVELTR (V : Unsigned_64) return L_ACKLEVELTR_T is
     (L_ACKLEVELTR_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_ACKLEVELTR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_ACKLEVELTR_T) return Boolean is
     (True);

   --  L_DOUBTOVER, 7.5.1.43: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type L_DOUBTOVER_T is range 0 .. 32767;
   L_DOUBTOVER_Unknown : constant L_DOUBTOVER_T := 32767;
   --  32767: unknown
   function To_L_DOUBTOVER (V : Unsigned_64) return L_DOUBTOVER_T is
     (L_DOUBTOVER_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_DOUBTOVER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_DOUBTOVER_T) return Boolean is
     (True);

   --  L_DOUBTUNDER, 7.5.1.44: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type L_DOUBTUNDER_T is range 0 .. 32767;
   L_DOUBTUNDER_Unknown : constant L_DOUBTUNDER_T := 32767;
   --  32767: unknown
   function To_L_DOUBTUNDER (V : Unsigned_64) return L_DOUBTUNDER_T is
     (L_DOUBTUNDER_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_DOUBTUNDER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_DOUBTUNDER_T) return Boolean is
     (True);

   --  L_ENDSECTION, 7.5.1.45: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type L_ENDSECTION_T is range 0 .. 32767;
   function To_L_ENDSECTION (V : Unsigned_64) return L_ENDSECTION_T is
     (L_ENDSECTION_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_ENDSECTION_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_ENDSECTION_T) return Boolean is
     (True);

   --  L_MESSAGE, 7.5.1.48: 10 bits, 0 .. 1023, 1 byte
   type L_MESSAGE_T is range 0 .. 1023;
   function To_L_MESSAGE (V : Unsigned_64) return L_MESSAGE_T is
     (L_MESSAGE_T (V))
     with Pre => Fits (V, 10);
   function Code (X : L_MESSAGE_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : L_MESSAGE_T) return Boolean is
     (True);

   --  L_NVKRINT, 7.5.1.48.1: 5 bits, 0 .. 31, 0 m, 25 m, 50 m, ... (table)
   type L_NVKRINT_T is range 0 .. 31;
   function To_L_NVKRINT (V : Unsigned_64) return L_NVKRINT_T is
     (L_NVKRINT_T (V))
     with Pre => Fits (V, 5);
   function Code (X : L_NVKRINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : L_NVKRINT_T) return Boolean is
     (True);

   --  L_PACKET, 7.5.1.49: 13 bits, 0 .. 8191, 1 bit
   type L_PACKET_T is range 0 .. 8191;
   function To_L_PACKET (V : Unsigned_64) return L_PACKET_T is
     (L_PACKET_T (V))
     with Pre => Fits (V, 13);
   function Code (X : L_PACKET_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 13);
   function Is_Valid (X : L_PACKET_T) return Boolean is
     (True);

   --  L_SECTION, 7.5.1.51: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type L_SECTION_T is range 0 .. 32767;
   function To_L_SECTION (V : Unsigned_64) return L_SECTION_T is
     (L_SECTION_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_SECTION_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_SECTION_T) return Boolean is
     (True);

   --  L_TAFDISPLAY, 7.5.1.52: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type L_TAFDISPLAY_T is range 0 .. 32767;
   function To_L_TAFDISPLAY (V : Unsigned_64) return L_TAFDISPLAY_T is
     (L_TAFDISPLAY_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_TAFDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_TAFDISPLAY_T) return Boolean is
     (True);

   --  L_TEXT, 7.5.1.53: 8 bits, 0 .. 255, 1 text string element
   type L_TEXT_T is range 0 .. 255;
   function To_L_TEXT (V : Unsigned_64) return L_TEXT_T is
     (L_TEXT_T (V))
     with Pre => Fits (V, 8);
   function Code (X : L_TEXT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : L_TEXT_T) return Boolean is
     (True);

   --  L_TEXTDISPLAY, 7.5.1.54: 15 bits, 0 .. 32766, resolution by Q_SCALE
   type L_TEXTDISPLAY_T is range 0 .. 32767;
   L_TEXTDISPLAY_No_Location : constant L_TEXTDISPLAY_T := 32767;
   --  32767: no location
   function To_L_TEXTDISPLAY (V : Unsigned_64) return L_TEXTDISPLAY_T is
     (L_TEXTDISPLAY_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_TEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_TEXTDISPLAY_T) return Boolean is
     (True);

   --  L_TRAININT, 7.5.1.57: 15 bits, 0 .. 32767, 1 m
   type L_TRAININT_T is range 0 .. 32767;
   function To_L_TRAININT (V : Unsigned_64) return L_TRAININT_T is
     (L_TRAININT_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_TRAININT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_TRAININT_T) return Boolean is
     (True);

   --  L_TSR, 7.5.1.58: 15 bits, 0 .. 32767, resolution by Q_SCALE
   type L_TSR_T is range 0 .. 32767;
   function To_L_TSR (V : Unsigned_64) return L_TSR_T is
     (L_TSR_T (V))
     with Pre => Fits (V, 15);
   function Code (X : L_TSR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 15);
   function Is_Valid (X : L_TSR_T) return Boolean is
     (True);

   --  M_ACK, 7.5.1.59: 1 bits, 0 .. 1
   type M_ACK_T is range 0 .. 1;
   M_ACK_No_Acknowledgement : constant M_ACK_T := 0;
   --  0: no acknowledgement
   M_ACK_Acknowledgement_Required : constant M_ACK_T := 1;
   --  1: acknowledgement required
   function To_M_ACK (V : Unsigned_64) return M_ACK_T is
     (M_ACK_T (V))
     with Pre => Fits (V, 1);
   function Code (X : M_ACK_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : M_ACK_T) return Boolean is
     (True);

   --  M_DUP, 7.5.1.63: 2 bits, 0 .. 2
   type M_DUP_T is range 0 .. 3;
   M_DUP_No_Duplicates : constant M_DUP_T := 0;
   --  0: no duplicates
   M_DUP_Duplicate_Of_Next : constant M_DUP_T := 1;
   --  1: duplicate of next
   M_DUP_Duplicate_Of_Previous : constant M_DUP_T := 2;
   --  2: duplicate of previous
   function To_M_DUP (V : Unsigned_64) return M_DUP_T is
     (M_DUP_T (V))
     with Pre => Fits (V, 2);
   function Code (X : M_DUP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : M_DUP_T) return Boolean is
     (X <= 2);

   --  M_ERROR, 7.5.1.64: 8 bits, 0 .. 10
   type M_ERROR_T is range 0 .. 255;
   function To_M_ERROR (V : Unsigned_64) return M_ERROR_T is
     (M_ERROR_T (V))
     with Pre => Fits (V, 8);
   function Code (X : M_ERROR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : M_ERROR_T) return Boolean is
     (X <= 10);

   --  M_LEVEL, 7.5.1.65: 3 bits, 0 .. 3
   type M_LEVEL_T is range 0 .. 7;
   M_LEVEL_Level_0 : constant M_LEVEL_T := 0;
   --  0: level 0
   M_LEVEL_NTC : constant M_LEVEL_T := 1;
   --  1: NTC
   M_LEVEL_Level_1 : constant M_LEVEL_T := 2;
   --  2: level 1
   M_LEVEL_Level_2 : constant M_LEVEL_T := 3;
   --  3: level 2
   function To_M_LEVEL (V : Unsigned_64) return M_LEVEL_T is
     (M_LEVEL_T (V))
     with Pre => Fits (V, 3);
   function Code (X : M_LEVEL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 3);
   function Is_Valid (X : M_LEVEL_T) return Boolean is
     (X <= 3);

   --  M_LEVELTEXTDISPLAY, 7.5.1.66: 3 bits, 0 .. 4
   type M_LEVELTEXTDISPLAY_T is range 0 .. 7;
   M_LEVELTEXTDISPLAY_Level_0 : constant M_LEVELTEXTDISPLAY_T := 0;
   --  0: level 0
   M_LEVELTEXTDISPLAY_NTC : constant M_LEVELTEXTDISPLAY_T := 1;
   --  1: NTC
   M_LEVELTEXTDISPLAY_Level_1 : constant M_LEVELTEXTDISPLAY_T := 2;
   --  2: level 1
   M_LEVELTEXTDISPLAY_Level_2 : constant M_LEVELTEXTDISPLAY_T := 3;
   --  3: level 2
   M_LEVELTEXTDISPLAY_No_Level : constant M_LEVELTEXTDISPLAY_T := 4;
   --  4: no level
   function To_M_LEVELTEXTDISPLAY (V : Unsigned_64)
     return M_LEVELTEXTDISPLAY_T
   is (M_LEVELTEXTDISPLAY_T (V))
     with Pre => Fits (V, 3);
   function Code (X : M_LEVELTEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 3);
   function Is_Valid (X : M_LEVELTEXTDISPLAY_T) return Boolean is
     (X <= 4);

   --  M_LEVELTR, 7.5.1.67: 3 bits, 0 .. 3
   type M_LEVELTR_T is range 0 .. 7;
   M_LEVELTR_Level_0 : constant M_LEVELTR_T := 0;
   --  0: level 0
   M_LEVELTR_NTC : constant M_LEVELTR_T := 1;
   --  1: NTC
   M_LEVELTR_Level_1 : constant M_LEVELTR_T := 2;
   --  2: level 1
   M_LEVELTR_Level_2 : constant M_LEVELTR_T := 3;
   --  3: level 2
   function To_M_LEVELTR (V : Unsigned_64) return M_LEVELTR_T is
     (M_LEVELTR_T (V))
     with Pre => Fits (V, 3);
   function Code (X : M_LEVELTR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 3);
   function Is_Valid (X : M_LEVELTR_T) return Boolean is
     (X <= 3);

   --  M_MCOUNT, 7.5.1.71: 8 bits, 0 .. 253
   type M_MCOUNT_T is range 0 .. 255;
   M_MCOUNT_Never_Fits : constant M_MCOUNT_T := 254;
   --  254: never fits
   M_MCOUNT_Fits_All : constant M_MCOUNT_T := 255;
   --  255: fits all
   function To_M_MCOUNT (V : Unsigned_64) return M_MCOUNT_T is
     (M_MCOUNT_T (V))
     with Pre => Fits (V, 8);
   function Code (X : M_MCOUNT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : M_MCOUNT_T) return Boolean is
     (True);

   --  M_MODE, 7.5.1.72: 5 bits, 0 .. 17
   type M_MODE_T is range 0 .. 31;
   function To_M_MODE (V : Unsigned_64) return M_MODE_T is
     (M_MODE_T (V))
     with Pre => Fits (V, 5);
   function Code (X : M_MODE_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : M_MODE_T) return Boolean is
     (X <= 17);

   --  M_MODETEXTDISPLAY, 7.5.1.73: 4 bits, 0 .. 15
   type M_MODETEXTDISPLAY_T is range 0 .. 15;
   function To_M_MODETEXTDISPLAY (V : Unsigned_64)
     return M_MODETEXTDISPLAY_T
   is (M_MODETEXTDISPLAY_T (V))
     with Pre => Fits (V, 4);
   function Code (X : M_MODETEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 4);
   function Is_Valid (X : M_MODETEXTDISPLAY_T) return Boolean is
     (True);

   --  M_NVAVADH, 7.5.1.73.1: 5 bits, 0 .. 20, 0.05
   type M_NVAVADH_T is range 0 .. 31;
   function To_M_NVAVADH (V : Unsigned_64) return M_NVAVADH_T is
     (M_NVAVADH_T (V))
     with Pre => Fits (V, 5);
   function Code (X : M_NVAVADH_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : M_NVAVADH_T) return Boolean is
     (X <= 20);

   --  M_NVCONTACT, 7.5.1.74: 2 bits, 0 .. 2
   type M_NVCONTACT_T is range 0 .. 3;
   M_NVCONTACT_Train_Trip : constant M_NVCONTACT_T := 0;
   --  0: train trip
   M_NVCONTACT_Service_Brake : constant M_NVCONTACT_T := 1;
   --  1: service brake
   M_NVCONTACT_No_Reaction : constant M_NVCONTACT_T := 2;
   --  2: no reaction
   function To_M_NVCONTACT (V : Unsigned_64) return M_NVCONTACT_T is
     (M_NVCONTACT_T (V))
     with Pre => Fits (V, 2);
   function Code (X : M_NVCONTACT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : M_NVCONTACT_T) return Boolean is
     (X <= 2);

   --  M_NVDERUN, 7.5.1.75: 1 bits, 0 .. 1
   type M_NVDERUN_T is range 0 .. 1;
   M_NVDERUN_No : constant M_NVDERUN_T := 0;
   --  0: no
   M_NVDERUN_Yes : constant M_NVDERUN_T := 1;
   --  1: yes
   function To_M_NVDERUN (V : Unsigned_64) return M_NVDERUN_T is
     (M_NVDERUN_T (V))
     with Pre => Fits (V, 1);
   function Code (X : M_NVDERUN_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : M_NVDERUN_T) return Boolean is
     (True);

   --  M_NVEBCL, 7.5.1.75.1: 4 bits, 0 .. 9
   type M_NVEBCL_T is range 0 .. 15;
   function To_M_NVEBCL (V : Unsigned_64) return M_NVEBCL_T is
     (M_NVEBCL_T (V))
     with Pre => Fits (V, 4);
   function Code (X : M_NVEBCL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 4);
   function Is_Valid (X : M_NVEBCL_T) return Boolean is
     (X <= 9);

   --  M_NVKRINT, 7.5.1.75.2: 5 bits, 0 .. 31, 0.05
   type M_NVKRINT_T is range 0 .. 31;
   function To_M_NVKRINT (V : Unsigned_64) return M_NVKRINT_T is
     (M_NVKRINT_T (V))
     with Pre => Fits (V, 5);
   function Code (X : M_NVKRINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : M_NVKRINT_T) return Boolean is
     (True);

   --  M_NVKTINT, 7.5.1.75.3: 5 bits, 0 .. 31, 0.05
   type M_NVKTINT_T is range 0 .. 31;
   function To_M_NVKTINT (V : Unsigned_64) return M_NVKTINT_T is
     (M_NVKTINT_T (V))
     with Pre => Fits (V, 5);
   function Code (X : M_NVKTINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : M_NVKTINT_T) return Boolean is
     (True);

   --  M_NVKVINT, 7.5.1.75.4: 7 bits, 0 .. 127, 0.02
   type M_NVKVINT_T is range 0 .. 127;
   function To_M_NVKVINT (V : Unsigned_64) return M_NVKVINT_T is
     (M_NVKVINT_T (V))
     with Pre => Fits (V, 7);
   function Code (X : M_NVKVINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : M_NVKVINT_T) return Boolean is
     (True);

   --  M_VERSION, 7.5.1.79: 7 bits, 0 .. 127
   type M_VERSION_T is range 0 .. 127;
   M_VERSION_V1_0 : constant M_VERSION_T := 16;
   --  16: V1.0
   M_VERSION_V1_1 : constant M_VERSION_T := 17;
   --  17: V1.1
   M_VERSION_V2_0 : constant M_VERSION_T := 32;
   --  32: V2.0
   M_VERSION_V2_1 : constant M_VERSION_T := 33;
   --  33: V2.1
   M_VERSION_V2_2 : constant M_VERSION_T := 34;
   --  34: V2.2
   M_VERSION_V2_3 : constant M_VERSION_T := 35;
   --  35: V2.3
   M_VERSION_V3_0 : constant M_VERSION_T := 48;
   --  48: V3.0
   function To_M_VERSION (V : Unsigned_64) return M_VERSION_T is
     (M_VERSION_T (V))
     with Pre => Fits (V, 7);
   function Code (X : M_VERSION_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : M_VERSION_T) return Boolean is
     (True);

   --  NC_CDDIFF, 7.5.1.82.1: 4 bits, 0 .. 10
   type NC_CDDIFF_T is range 0 .. 15;
   function To_NC_CDDIFF (V : Unsigned_64) return NC_CDDIFF_T is
     (NC_CDDIFF_T (V))
     with Pre => Fits (V, 4);
   function Code (X : NC_CDDIFF_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 4);
   function Is_Valid (X : NC_CDDIFF_T) return Boolean is
     (X <= 10);

   --  NC_DIFF, 7.5.1.83: 4 bits, 0 .. 2
   type NC_DIFF_T is range 0 .. 15;
   NC_DIFF_Freight_P : constant NC_DIFF_T := 0;
   --  0: freight P
   NC_DIFF_Freight_G : constant NC_DIFF_T := 1;
   --  1: freight G
   NC_DIFF_Passenger : constant NC_DIFF_T := 2;
   --  2: passenger
   function To_NC_DIFF (V : Unsigned_64) return NC_DIFF_T is
     (NC_DIFF_T (V))
     with Pre => Fits (V, 4);
   function Code (X : NC_DIFF_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 4);
   function Is_Valid (X : NC_DIFF_T) return Boolean is
     (X <= 2);

   --  NID_BG, 7.5.1.85: 14 bits, 0 .. 16382
   type NID_BG_T is range 0 .. 16383;
   NID_BG_Unknown : constant NID_BG_T := 16383;
   --  16383: unknown
   function To_NID_BG (V : Unsigned_64) return NID_BG_T is
     (NID_BG_T (V))
     with Pre => Fits (V, 14);
   function Code (X : NID_BG_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 14);
   function Is_Valid (X : NID_BG_T) return Boolean is
     (True);

   --  NID_C, 7.5.1.86: 10 bits, 0 .. 1023
   type NID_C_T is range 0 .. 1023;
   function To_NID_C (V : Unsigned_64) return NID_C_T is
     (NID_C_T (V))
     with Pre => Fits (V, 10);
   function Code (X : NID_C_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : NID_C_T) return Boolean is
     (True);

   --  NID_EM, 7.5.1.87: 4 bits, 0 .. 15
   type NID_EM_T is range 0 .. 15;
   function To_NID_EM (V : Unsigned_64) return NID_EM_T is
     (NID_EM_T (V))
     with Pre => Fits (V, 4);
   function Code (X : NID_EM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 4);
   function Is_Valid (X : NID_EM_T) return Boolean is
     (True);

   --  NID_ENGINE, 7.5.1.88: 24 bits, 0 .. 16777215
   type NID_ENGINE_T is range 0 .. 16777215;
   function To_NID_ENGINE (V : Unsigned_64) return NID_ENGINE_T is
     (NID_ENGINE_T (V))
     with Pre => Fits (V, 24);
   function Code (X : NID_ENGINE_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 24);
   function Is_Valid (X : NID_ENGINE_T) return Boolean is
     (True);

   --  NID_MESSAGE, 7.5.1.91: 8 bits, 0 .. 255
   type NID_MESSAGE_T is range 0 .. 255;
   function To_NID_MESSAGE (V : Unsigned_64) return NID_MESSAGE_T is
     (NID_MESSAGE_T (V))
     with Pre => Fits (V, 8);
   function Code (X : NID_MESSAGE_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : NID_MESSAGE_T) return Boolean is
     (True);

   --  NID_NTC, 7.5.1.98: 8 bits, 0 .. 255
   type NID_NTC_T is range 0 .. 255;
   function To_NID_NTC (V : Unsigned_64) return NID_NTC_T is
     (NID_NTC_T (V))
     with Pre => Fits (V, 8);
   function Code (X : NID_NTC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : NID_NTC_T) return Boolean is
     (True);

   --  NID_OPERATIONAL, 7.5.1.92: 32 bits, 0 .. 4294967295, 8 BCD digits, 15
   --  (F) where no digit
   type NID_OPERATIONAL_T is range 0 .. 4294967295;
   function To_NID_OPERATIONAL (V : Unsigned_64) return NID_OPERATIONAL_T is
     (NID_OPERATIONAL_T (V))
     with Pre => Fits (V, 32);
   function Code (X : NID_OPERATIONAL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 32);
   function Is_Valid (X : NID_OPERATIONAL_T) return Boolean is
     (True);

   --  NID_PACKET, 7.5.1.93: 8 bits, 0 .. 255
   type NID_PACKET_T is range 0 .. 255;
   function To_NID_PACKET (V : Unsigned_64) return NID_PACKET_T is
     (NID_PACKET_T (V))
     with Pre => Fits (V, 8);
   function Code (X : NID_PACKET_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : NID_PACKET_T) return Boolean is
     (True);

   --  NID_RBC, 7.5.1.96: 14 bits, 0 .. 16382
   type NID_RBC_T is range 0 .. 16383;
   NID_RBC_Contact_Last_Known_RBC : constant NID_RBC_T := 16383;
   --  16383: contact last known RBC
   function To_NID_RBC (V : Unsigned_64) return NID_RBC_T is
     (NID_RBC_T (V))
     with Pre => Fits (V, 14);
   function Code (X : NID_RBC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 14);
   function Is_Valid (X : NID_RBC_T) return Boolean is
     (True);

   --  NID_TEXTMESSAGE, 7.5.1.98.1: 8 bits, 0 .. 255
   type NID_TEXTMESSAGE_T is range 0 .. 255;
   function To_NID_TEXTMESSAGE (V : Unsigned_64) return NID_TEXTMESSAGE_T is
     (NID_TEXTMESSAGE_T (V))
     with Pre => Fits (V, 8);
   function Code (X : NID_TEXTMESSAGE_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : NID_TEXTMESSAGE_T) return Boolean is
     (True);

   --  NID_TSR, 7.5.1.99: 8 bits, 0 .. 255
   type NID_TSR_T is range 0 .. 255;
   NID_TSR_Non_Revocable : constant NID_TSR_T := 255;
   --  255: non revocable
   function To_NID_TSR (V : Unsigned_64) return NID_TSR_T is
     (NID_TSR_T (V))
     with Pre => Fits (V, 8);
   function Code (X : NID_TSR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : NID_TSR_T) return Boolean is
     (True);

   --  NID_VBCMK, 7.5.1.99.1: 6 bits, 0 .. 63
   type NID_VBCMK_T is range 0 .. 63;
   function To_NID_VBCMK (V : Unsigned_64) return NID_VBCMK_T is
     (NID_VBCMK_T (V))
     with Pre => Fits (V, 6);
   function Code (X : NID_VBCMK_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : NID_VBCMK_T) return Boolean is
     (True);

   --  NID_XUSER, 7.5.1.100: 9 bits, 0 .. 511
   type NID_XUSER_T is range 0 .. 511;
   function To_NID_XUSER (V : Unsigned_64) return NID_XUSER_T is
     (NID_XUSER_T (V))
     with Pre => Fits (V, 9);
   function Code (X : NID_XUSER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 9);
   function Is_Valid (X : NID_XUSER_T) return Boolean is
     (True);

   --  N_ITER, 7.5.1.80: 5 bits, 0 .. 31
   type N_ITER_T is range 0 .. 31;
   function To_N_ITER (V : Unsigned_64) return N_ITER_T is
     (N_ITER_T (V))
     with Pre => Fits (V, 5);
   function Code (X : N_ITER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : N_ITER_T) return Boolean is
     (True);

   --  N_PIG, 7.5.1.81: 3 bits, 0 .. 7
   type N_PIG_T is range 0 .. 7;
   function To_N_PIG (V : Unsigned_64) return N_PIG_T is
     (N_PIG_T (V))
     with Pre => Fits (V, 3);
   function Code (X : N_PIG_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 3);
   function Is_Valid (X : N_PIG_T) return Boolean is
     (True);

   --  N_TOTAL, 7.5.1.82: 3 bits, 0 .. 7
   type N_TOTAL_T is range 0 .. 7;
   function To_N_TOTAL (V : Unsigned_64) return N_TOTAL_T is
     (N_TOTAL_T (V))
     with Pre => Fits (V, 3);
   function Code (X : N_TOTAL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 3);
   function Is_Valid (X : N_TOTAL_T) return Boolean is
     (True);

   --  Q_CONFTEXTDISPLAY, 7.5.1.101.1: 1 bits, 0 .. 1
   type Q_CONFTEXTDISPLAY_T is range 0 .. 1;
   Q_CONFTEXTDISPLAY_Acknowledgement_Ends_Display :
     constant Q_CONFTEXTDISPLAY_T := 0;
   --  0: acknowledgement ends display
   Q_CONFTEXTDISPLAY_Acknowledgement_Additional :
     constant Q_CONFTEXTDISPLAY_T := 1;
   --  1: acknowledgement additional
   function To_Q_CONFTEXTDISPLAY (V : Unsigned_64)
     return Q_CONFTEXTDISPLAY_T
   is (Q_CONFTEXTDISPLAY_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_CONFTEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_CONFTEXTDISPLAY_T) return Boolean is
     (True);

   --  Q_DANGERPOINT, 7.5.1.102: 1 bits, 0 .. 1
   type Q_DANGERPOINT_T is range 0 .. 1;
   Q_DANGERPOINT_No_Danger_Point : constant Q_DANGERPOINT_T := 0;
   --  0: no danger point
   Q_DANGERPOINT_Danger_Point_Follows : constant Q_DANGERPOINT_T := 1;
   --  1: danger point follows
   function To_Q_DANGERPOINT (V : Unsigned_64) return Q_DANGERPOINT_T is
     (Q_DANGERPOINT_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_DANGERPOINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_DANGERPOINT_T) return Boolean is
     (True);

   --  Q_DESK, 7.5.1.102.2: 1 bits, 0 .. 1
   type Q_DESK_T is range 0 .. 1;
   Q_DESK_Desks_Closed : constant Q_DESK_T := 0;
   --  0: desks closed
   Q_DESK_Desk_Open : constant Q_DESK_T := 1;
   --  1: desk open
   function To_Q_DESK (V : Unsigned_64) return Q_DESK_T is
     (Q_DESK_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_DESK_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_DESK_T) return Boolean is
     (True);

   --  Q_DIFF, 7.5.1.102.1: 2 bits, 0 .. 2
   type Q_DIFF_T is range 0 .. 3;
   Q_DIFF_Cant_Deficiency : constant Q_DIFF_T := 0;
   --  0: cant deficiency
   Q_DIFF_Other_Replaces : constant Q_DIFF_T := 1;
   --  1: other, replaces
   Q_DIFF_Other_Does_Not_Replace : constant Q_DIFF_T := 2;
   --  2: other, does not replace
   function To_Q_DIFF (V : Unsigned_64) return Q_DIFF_T is
     (Q_DIFF_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_DIFF_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_DIFF_T) return Boolean is
     (X <= 2);

   --  Q_DIR, 7.5.1.103: 2 bits, 0 .. 2
   type Q_DIR_T is range 0 .. 3;
   Q_DIR_Reverse : constant Q_DIR_T := 0;
   --  0: reverse
   Q_DIR_Nominal : constant Q_DIR_T := 1;
   --  1: nominal
   Q_DIR_Both_Directions : constant Q_DIR_T := 2;
   --  2: both directions
   function To_Q_DIR (V : Unsigned_64) return Q_DIR_T is
     (Q_DIR_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_DIR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_DIR_T) return Boolean is
     (X <= 2);

   --  Q_DIRLRBG, 7.5.1.104: 2 bits, 0 .. 2
   type Q_DIRLRBG_T is range 0 .. 3;
   Q_DIRLRBG_Reverse : constant Q_DIRLRBG_T := 0;
   --  0: reverse
   Q_DIRLRBG_Nominal : constant Q_DIRLRBG_T := 1;
   --  1: nominal
   Q_DIRLRBG_Unknown : constant Q_DIRLRBG_T := 2;
   --  2: unknown
   function To_Q_DIRLRBG (V : Unsigned_64) return Q_DIRLRBG_T is
     (Q_DIRLRBG_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_DIRLRBG_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_DIRLRBG_T) return Boolean is
     (X <= 2);

   --  Q_DIRTRAIN, 7.5.1.105: 2 bits, 0 .. 2
   type Q_DIRTRAIN_T is range 0 .. 3;
   Q_DIRTRAIN_Reverse : constant Q_DIRTRAIN_T := 0;
   --  0: reverse
   Q_DIRTRAIN_Nominal : constant Q_DIRTRAIN_T := 1;
   --  1: nominal
   Q_DIRTRAIN_Unknown : constant Q_DIRTRAIN_T := 2;
   --  2: unknown
   function To_Q_DIRTRAIN (V : Unsigned_64) return Q_DIRTRAIN_T is
     (Q_DIRTRAIN_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_DIRTRAIN_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_DIRTRAIN_T) return Boolean is
     (X <= 2);

   --  Q_DLRBG, 7.5.1.106: 2 bits, 0 .. 2
   type Q_DLRBG_T is range 0 .. 3;
   Q_DLRBG_Reverse : constant Q_DLRBG_T := 0;
   --  0: reverse
   Q_DLRBG_Nominal : constant Q_DLRBG_T := 1;
   --  1: nominal
   Q_DLRBG_Unknown : constant Q_DLRBG_T := 2;
   --  2: unknown
   function To_Q_DLRBG (V : Unsigned_64) return Q_DLRBG_T is
     (Q_DLRBG_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_DLRBG_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_DLRBG_T) return Boolean is
     (X <= 2);

   --  Q_EMERGENCYSTOP, 7.5.1.107: 2 bits, 0 .. 3
   type Q_EMERGENCYSTOP_T is range 0 .. 3;
   function To_Q_EMERGENCYSTOP (V : Unsigned_64) return Q_EMERGENCYSTOP_T is
     (Q_EMERGENCYSTOP_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_EMERGENCYSTOP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_EMERGENCYSTOP_T) return Boolean is
     (True);

   --  Q_ENDTIMER, 7.5.1.108: 1 bits, 0 .. 1
   type Q_ENDTIMER_T is range 0 .. 1;
   Q_ENDTIMER_No_End_Timer : constant Q_ENDTIMER_T := 0;
   --  0: no end timer
   Q_ENDTIMER_End_Timer_Follows : constant Q_ENDTIMER_T := 1;
   --  1: end timer follows
   function To_Q_ENDTIMER (V : Unsigned_64) return Q_ENDTIMER_T is
     (Q_ENDTIMER_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_ENDTIMER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_ENDTIMER_T) return Boolean is
     (True);

   --  Q_FRONT, 7.5.1.109: 1 bits, 0 .. 1
   type Q_FRONT_T is range 0 .. 1;
   Q_FRONT_Train_Length_Delay : constant Q_FRONT_T := 0;
   --  0: train length delay
   Q_FRONT_No_Train_Length_Delay : constant Q_FRONT_T := 1;
   --  1: no train length delay
   function To_Q_FRONT (V : Unsigned_64) return Q_FRONT_T is
     (Q_FRONT_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_FRONT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_FRONT_T) return Boolean is
     (True);

   --  Q_GDIR, 7.5.1.110: 1 bits, 0 .. 1
   type Q_GDIR_T is range 0 .. 1;
   Q_GDIR_Downhill : constant Q_GDIR_T := 0;
   --  0: downhill
   Q_GDIR_Uphill : constant Q_GDIR_T := 1;
   --  1: uphill
   function To_Q_GDIR (V : Unsigned_64) return Q_GDIR_T is
     (Q_GDIR_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_GDIR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_GDIR_T) return Boolean is
     (True);

   --  Q_INFILL, 7.5.1.111: 1 bits, 0 .. 1
   type Q_INFILL_T is range 0 .. 1;
   Q_INFILL_Enter : constant Q_INFILL_T := 0;
   --  0: enter
   Q_INFILL_Exit : constant Q_INFILL_T := 1;
   --  1: exit
   function To_Q_INFILL (V : Unsigned_64) return Q_INFILL_T is
     (Q_INFILL_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_INFILL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_INFILL_T) return Boolean is
     (True);

   --  Q_INTEGRITY, 7.5.1.112: 2 bits, 0 .. 3
   type Q_INTEGRITY_T is range 0 .. 3;
   Q_INTEGRITY_No_Information : constant Q_INTEGRITY_T := 0;
   --  0: no information
   Q_INTEGRITY_Confirmed_By_External_Source : constant Q_INTEGRITY_T := 1;
   --  1: confirmed by external source
   Q_INTEGRITY_Confirmed_By_Driver : constant Q_INTEGRITY_T := 2;
   --  2: confirmed by driver
   Q_INTEGRITY_Lost : constant Q_INTEGRITY_T := 3;
   --  3: lost
   function To_Q_INTEGRITY (V : Unsigned_64) return Q_INTEGRITY_T is
     (Q_INTEGRITY_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_INTEGRITY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_INTEGRITY_T) return Boolean is
     (True);

   --  Q_LINK, 7.5.1.114: 1 bits, 0 .. 1
   type Q_LINK_T is range 0 .. 1;
   Q_LINK_Unlinked : constant Q_LINK_T := 0;
   --  0: unlinked
   Q_LINK_Linked : constant Q_LINK_T := 1;
   --  1: linked
   function To_Q_LINK (V : Unsigned_64) return Q_LINK_T is
     (Q_LINK_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_LINK_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_LINK_T) return Boolean is
     (True);

   --  Q_LINKORIENTATION, 7.5.1.116: 1 bits, 0 .. 1
   type Q_LINKORIENTATION_T is range 0 .. 1;
   Q_LINKORIENTATION_Reverse : constant Q_LINKORIENTATION_T := 0;
   --  0: reverse
   Q_LINKORIENTATION_Nominal : constant Q_LINKORIENTATION_T := 1;
   --  1: nominal
   function To_Q_LINKORIENTATION (V : Unsigned_64)
     return Q_LINKORIENTATION_T
   is (Q_LINKORIENTATION_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_LINKORIENTATION_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_LINKORIENTATION_T) return Boolean is
     (True);

   --  Q_LINKREACTION, 7.5.1.117: 2 bits, 0 .. 2
   type Q_LINKREACTION_T is range 0 .. 3;
   Q_LINKREACTION_Train_Trip : constant Q_LINKREACTION_T := 0;
   --  0: train trip
   Q_LINKREACTION_Service_Brake : constant Q_LINKREACTION_T := 1;
   --  1: service brake
   Q_LINKREACTION_No_Reaction : constant Q_LINKREACTION_T := 2;
   --  2: no reaction
   function To_Q_LINKREACTION (V : Unsigned_64) return Q_LINKREACTION_T is
     (Q_LINKREACTION_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_LINKREACTION_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_LINKREACTION_T) return Boolean is
     (X <= 2);

   --  Q_LOCACC, 7.5.1.115: 6 bits, 0 .. 63, 1 m
   type Q_LOCACC_T is range 0 .. 63;
   function To_Q_LOCACC (V : Unsigned_64) return Q_LOCACC_T is
     (Q_LOCACC_T (V))
     with Pre => Fits (V, 6);
   function Code (X : Q_LOCACC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : Q_LOCACC_T) return Boolean is
     (True);

   --  Q_MARQSTREASON, 7.5.1.118.3: 5 bits, 0 .. 31, bit set
   type Q_MARQSTREASON_T is range 0 .. 31;
   function To_Q_MARQSTREASON (V : Unsigned_64) return Q_MARQSTREASON_T is
     (Q_MARQSTREASON_T (V))
     with Pre => Fits (V, 5);
   function Code (X : Q_MARQSTREASON_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 5);
   function Is_Valid (X : Q_MARQSTREASON_T) return Boolean is
     (True);

   --  Q_MEDIA, 7.5.1.119: 1 bits, 0 .. 1
   type Q_MEDIA_T is range 0 .. 1;
   Q_MEDIA_Balise : constant Q_MEDIA_T := 0;
   --  0: balise
   Q_MEDIA_Loop : constant Q_MEDIA_T := 1;
   --  1: loop
   function To_Q_MEDIA (V : Unsigned_64) return Q_MEDIA_T is
     (Q_MEDIA_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_MEDIA_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_MEDIA_T) return Boolean is
     (True);

   --  Q_NEWCOUNTRY, 7.5.1.121: 1 bits, 0 .. 1
   type Q_NEWCOUNTRY_T is range 0 .. 1;
   Q_NEWCOUNTRY_Same_Country : constant Q_NEWCOUNTRY_T := 0;
   --  0: same country
   Q_NEWCOUNTRY_NID_C_Follows : constant Q_NEWCOUNTRY_T := 1;
   --  1: NID_C follows
   function To_Q_NEWCOUNTRY (V : Unsigned_64) return Q_NEWCOUNTRY_T is
     (Q_NEWCOUNTRY_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NEWCOUNTRY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NEWCOUNTRY_T) return Boolean is
     (True);

   --  Q_NVDRIVER_ADHES, 7.5.1.122: 1 bits, 0 .. 1
   type Q_NVDRIVER_ADHES_T is range 0 .. 1;
   Q_NVDRIVER_ADHES_Not_Allowed : constant Q_NVDRIVER_ADHES_T := 0;
   --  0: not allowed
   Q_NVDRIVER_ADHES_Allowed : constant Q_NVDRIVER_ADHES_T := 1;
   --  1: allowed
   function To_Q_NVDRIVER_ADHES (V : Unsigned_64) return Q_NVDRIVER_ADHES_T is
     (Q_NVDRIVER_ADHES_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVDRIVER_ADHES_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVDRIVER_ADHES_T) return Boolean is
     (True);

   --  Q_NVEMRRLS, 7.5.1.123: 1 bits, 0 .. 1
   type Q_NVEMRRLS_T is range 0 .. 1;
   Q_NVEMRRLS_At_Standstill : constant Q_NVEMRRLS_T := 0;
   --  0: at standstill
   Q_NVEMRRLS_When_Not_Exceeded : constant Q_NVEMRRLS_T := 1;
   --  1: when not exceeded
   function To_Q_NVEMRRLS (V : Unsigned_64) return Q_NVEMRRLS_T is
     (Q_NVEMRRLS_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVEMRRLS_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVEMRRLS_T) return Boolean is
     (True);

   --  Q_NVGUIPERM, 7.5.1.123.1: 1 bits, 0 .. 1
   type Q_NVGUIPERM_T is range 0 .. 1;
   Q_NVGUIPERM_No : constant Q_NVGUIPERM_T := 0;
   --  0: no
   Q_NVGUIPERM_Yes : constant Q_NVGUIPERM_T := 1;
   --  1: yes
   function To_Q_NVGUIPERM (V : Unsigned_64) return Q_NVGUIPERM_T is
     (Q_NVGUIPERM_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVGUIPERM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVGUIPERM_T) return Boolean is
     (True);

   --  Q_NVINHSMICPERM, 7.5.1.123.2: 1 bits, 0 .. 1
   type Q_NVINHSMICPERM_T is range 0 .. 1;
   Q_NVINHSMICPERM_No : constant Q_NVINHSMICPERM_T := 0;
   --  0: no
   Q_NVINHSMICPERM_Yes : constant Q_NVINHSMICPERM_T := 1;
   --  1: yes
   function To_Q_NVINHSMICPERM (V : Unsigned_64) return Q_NVINHSMICPERM_T is
     (Q_NVINHSMICPERM_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVINHSMICPERM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVINHSMICPERM_T) return Boolean is
     (True);

   --  Q_NVKINT, 7.5.1.123.3: 1 bits, 0 .. 1
   type Q_NVKINT_T is range 0 .. 1;
   Q_NVKINT_No_Correction_Factors : constant Q_NVKINT_T := 0;
   --  0: no correction factors
   Q_NVKINT_Correction_Factors_Follow : constant Q_NVKINT_T := 1;
   --  1: correction factors follow
   function To_Q_NVKINT (V : Unsigned_64) return Q_NVKINT_T is
     (Q_NVKINT_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVKINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVKINT_T) return Boolean is
     (True);

   --  Q_NVKVINTSET, 7.5.1.123.4: 2 bits, 0 .. 1
   type Q_NVKVINTSET_T is range 0 .. 3;
   Q_NVKVINTSET_Freight_Trains : constant Q_NVKVINTSET_T := 0;
   --  0: freight trains
   Q_NVKVINTSET_Conventional_Passenger_Trains : constant Q_NVKVINTSET_T := 1;
   --  1: conventional passenger trains
   function To_Q_NVKVINTSET (V : Unsigned_64) return Q_NVKVINTSET_T is
     (Q_NVKVINTSET_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_NVKVINTSET_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_NVKVINTSET_T) return Boolean is
     (X <= 1);

   --  Q_NVLOCACC, 7.5.1.123.5: 6 bits, 0 .. 63, 1 m
   type Q_NVLOCACC_T is range 0 .. 63;
   function To_Q_NVLOCACC (V : Unsigned_64) return Q_NVLOCACC_T is
     (Q_NVLOCACC_T (V))
     with Pre => Fits (V, 6);
   function Code (X : Q_NVLOCACC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 6);
   function Is_Valid (X : Q_NVLOCACC_T) return Boolean is
     (True);

   --  Q_NVSBFBPERM, 7.5.1.123.6: 1 bits, 0 .. 1
   type Q_NVSBFBPERM_T is range 0 .. 1;
   Q_NVSBFBPERM_No : constant Q_NVSBFBPERM_T := 0;
   --  0: no
   Q_NVSBFBPERM_Yes : constant Q_NVSBFBPERM_T := 1;
   --  1: yes
   function To_Q_NVSBFBPERM (V : Unsigned_64) return Q_NVSBFBPERM_T is
     (Q_NVSBFBPERM_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVSBFBPERM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVSBFBPERM_T) return Boolean is
     (True);

   --  Q_NVSBTSMPERM, 7.5.1.124: 1 bits, 0 .. 1
   type Q_NVSBTSMPERM_T is range 0 .. 1;
   Q_NVSBTSMPERM_No : constant Q_NVSBTSMPERM_T := 0;
   --  0: no
   Q_NVSBTSMPERM_Yes : constant Q_NVSBTSMPERM_T := 1;
   --  1: yes
   function To_Q_NVSBTSMPERM (V : Unsigned_64) return Q_NVSBTSMPERM_T is
     (Q_NVSBTSMPERM_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_NVSBTSMPERM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_NVSBTSMPERM_T) return Boolean is
     (True);

   --  Q_ORIENTATION, 7.5.1.125: 1 bits, 0 .. 1
   type Q_ORIENTATION_T is range 0 .. 1;
   Q_ORIENTATION_Reverse : constant Q_ORIENTATION_T := 0;
   --  0: reverse
   Q_ORIENTATION_Nominal : constant Q_ORIENTATION_T := 1;
   --  1: nominal
   function To_Q_ORIENTATION (V : Unsigned_64) return Q_ORIENTATION_T is
     (Q_ORIENTATION_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_ORIENTATION_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_ORIENTATION_T) return Boolean is
     (True);

   --  Q_OVERLAP, 7.5.1.126: 1 bits, 0 .. 1
   type Q_OVERLAP_T is range 0 .. 1;
   Q_OVERLAP_No_Overlap : constant Q_OVERLAP_T := 0;
   --  0: no overlap
   Q_OVERLAP_Overlap_Follows : constant Q_OVERLAP_T := 1;
   --  1: overlap follows
   function To_Q_OVERLAP (V : Unsigned_64) return Q_OVERLAP_T is
     (Q_OVERLAP_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_OVERLAP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_OVERLAP_T) return Boolean is
     (True);

   --  Q_SCALE, 7.5.1.129: 2 bits, 0 .. 2
   type Q_SCALE_T is range 0 .. 3;
   Q_SCALE_10_Cm : constant Q_SCALE_T := 0;
   --  0: 10 cm
   Q_SCALE_1_M : constant Q_SCALE_T := 1;
   --  1: 1 m
   Q_SCALE_10_M : constant Q_SCALE_T := 2;
   --  2: 10 m
   function To_Q_SCALE (V : Unsigned_64) return Q_SCALE_T is
     (Q_SCALE_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_SCALE_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_SCALE_T) return Boolean is
     (X <= 2);

   --  Q_SECTIONTIMER, 7.5.1.130: 1 bits, 0 .. 1
   type Q_SECTIONTIMER_T is range 0 .. 1;
   Q_SECTIONTIMER_No_Section_Timer : constant Q_SECTIONTIMER_T := 0;
   --  0: no section timer
   Q_SECTIONTIMER_Section_Timer_Follows : constant Q_SECTIONTIMER_T := 1;
   --  1: section timer follows
   function To_Q_SECTIONTIMER (V : Unsigned_64) return Q_SECTIONTIMER_T is
     (Q_SECTIONTIMER_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_SECTIONTIMER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_SECTIONTIMER_T) return Boolean is
     (True);

   --  Q_STATUSLRBG, 7.5.1.134: 2 bits, 0 .. 2
   type Q_STATUSLRBG_T is range 0 .. 3;
   Q_STATUSLRBG_Invalid : constant Q_STATUSLRBG_T := 0;
   --  0: invalid
   Q_STATUSLRBG_Valid : constant Q_STATUSLRBG_T := 1;
   --  1: valid
   Q_STATUSLRBG_Unknown : constant Q_STATUSLRBG_T := 2;
   --  2: unknown
   function To_Q_STATUSLRBG (V : Unsigned_64) return Q_STATUSLRBG_T is
     (Q_STATUSLRBG_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_STATUSLRBG_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_STATUSLRBG_T) return Boolean is
     (X <= 2);

   --  Q_TEXTCLASS, 7.5.1.137: 2 bits, 0 .. 1
   type Q_TEXTCLASS_T is range 0 .. 3;
   Q_TEXTCLASS_Auxiliary : constant Q_TEXTCLASS_T := 0;
   --  0: auxiliary
   Q_TEXTCLASS_Important : constant Q_TEXTCLASS_T := 1;
   --  1: important
   function To_Q_TEXTCLASS (V : Unsigned_64) return Q_TEXTCLASS_T is
     (Q_TEXTCLASS_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_TEXTCLASS_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_TEXTCLASS_T) return Boolean is
     (X <= 1);

   --  Q_TEXTCONFIRM, 7.5.1.138: 2 bits, 0 .. 3
   type Q_TEXTCONFIRM_T is range 0 .. 3;
   Q_TEXTCONFIRM_No_Confirmation : constant Q_TEXTCONFIRM_T := 0;
   --  0: no confirmation
   Q_TEXTCONFIRM_Confirmation : constant Q_TEXTCONFIRM_T := 1;
   --  1: confirmation
   Q_TEXTCONFIRM_Confirmation_Service_Brake : constant Q_TEXTCONFIRM_T := 2;
   --  2: confirmation, service brake
   Q_TEXTCONFIRM_Confirmation_Emergency_Brake : constant Q_TEXTCONFIRM_T := 3;
   --  3: confirmation, emergency brake
   function To_Q_TEXTCONFIRM (V : Unsigned_64) return Q_TEXTCONFIRM_T is
     (Q_TEXTCONFIRM_T (V))
     with Pre => Fits (V, 2);
   function Code (X : Q_TEXTCONFIRM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 2);
   function Is_Valid (X : Q_TEXTCONFIRM_T) return Boolean is
     (True);

   --  Q_TEXTDISPLAY, 7.5.1.139: 1 bits, 0 .. 1
   type Q_TEXTDISPLAY_T is range 0 .. 1;
   Q_TEXTDISPLAY_One_Sub_Condition : constant Q_TEXTDISPLAY_T := 0;
   --  0: one sub-condition
   Q_TEXTDISPLAY_All_Sub_Conditions : constant Q_TEXTDISPLAY_T := 1;
   --  1: all sub-conditions
   function To_Q_TEXTDISPLAY (V : Unsigned_64) return Q_TEXTDISPLAY_T is
     (Q_TEXTDISPLAY_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_TEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_TEXTDISPLAY_T) return Boolean is
     (True);

   --  Q_TEXTREPORT, 7.5.1.140: 1 bits, 0 .. 1
   type Q_TEXTREPORT_T is range 0 .. 1;
   Q_TEXTREPORT_No_Report : constant Q_TEXTREPORT_T := 0;
   --  0: no report
   Q_TEXTREPORT_Report_Required : constant Q_TEXTREPORT_T := 1;
   --  1: report required
   function To_Q_TEXTREPORT (V : Unsigned_64) return Q_TEXTREPORT_T is
     (Q_TEXTREPORT_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_TEXTREPORT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_TEXTREPORT_T) return Boolean is
     (True);

   --  Q_UPDOWN, 7.5.1.142: 1 bits, 0 .. 1
   type Q_UPDOWN_T is range 0 .. 1;
   Q_UPDOWN_Down_Link : constant Q_UPDOWN_T := 0;
   --  0: down link
   Q_UPDOWN_Up_Link : constant Q_UPDOWN_T := 1;
   --  1: up link
   function To_Q_UPDOWN (V : Unsigned_64) return Q_UPDOWN_T is
     (Q_UPDOWN_T (V))
     with Pre => Fits (V, 1);
   function Code (X : Q_UPDOWN_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 1);
   function Is_Valid (X : Q_UPDOWN_T) return Boolean is
     (True);

   --  T_EMA, 7.5.1.146: 10 bits, 0 .. 1022, 1 s
   type T_EMA_T is range 0 .. 1023;
   T_EMA_No_Time_Out : constant T_EMA_T := 1023;
   --  1023: no time-out
   function To_T_EMA (V : Unsigned_64) return T_EMA_T is
     (T_EMA_T (V))
     with Pre => Fits (V, 10);
   function Code (X : T_EMA_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : T_EMA_T) return Boolean is
     (True);

   --  T_ENDTIMER, 7.5.1.145: 10 bits, 0 .. 1022, 1 s
   type T_ENDTIMER_T is range 0 .. 1023;
   T_ENDTIMER_Infinite : constant T_ENDTIMER_T := 1023;
   --  1023: infinite
   function To_T_ENDTIMER (V : Unsigned_64) return T_ENDTIMER_T is
     (T_ENDTIMER_T (V))
     with Pre => Fits (V, 10);
   function Code (X : T_ENDTIMER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : T_ENDTIMER_T) return Boolean is
     (True);

   --  T_NVCONTACT, 7.5.1.148: 8 bits, 0 .. 254, 1 s
   type T_NVCONTACT_T is range 0 .. 255;
   T_NVCONTACT_Infinite : constant T_NVCONTACT_T := 255;
   --  255: infinite
   function To_T_NVCONTACT (V : Unsigned_64) return T_NVCONTACT_T is
     (T_NVCONTACT_T (V))
     with Pre => Fits (V, 8);
   function Code (X : T_NVCONTACT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : T_NVCONTACT_T) return Boolean is
     (True);

   --  T_NVOVTRP, 7.5.1.149: 8 bits, 0 .. 255, 1 s
   type T_NVOVTRP_T is range 0 .. 255;
   function To_T_NVOVTRP (V : Unsigned_64) return T_NVOVTRP_T is
     (T_NVOVTRP_T (V))
     with Pre => Fits (V, 8);
   function Code (X : T_NVOVTRP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : T_NVOVTRP_T) return Boolean is
     (True);

   --  T_OL, 7.5.1.150: 10 bits, 0 .. 1022, 1 s
   type T_OL_T is range 0 .. 1023;
   T_OL_Infinite : constant T_OL_T := 1023;
   --  1023: infinite
   function To_T_OL (V : Unsigned_64) return T_OL_T is
     (T_OL_T (V))
     with Pre => Fits (V, 10);
   function Code (X : T_OL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : T_OL_T) return Boolean is
     (True);

   --  T_SECTIONTIMER, 7.5.1.151: 10 bits, 0 .. 1022, 1 s
   type T_SECTIONTIMER_T is range 0 .. 1023;
   T_SECTIONTIMER_Infinite : constant T_SECTIONTIMER_T := 1023;
   --  1023: infinite
   function To_T_SECTIONTIMER (V : Unsigned_64) return T_SECTIONTIMER_T is
     (T_SECTIONTIMER_T (V))
     with Pre => Fits (V, 10);
   function Code (X : T_SECTIONTIMER_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : T_SECTIONTIMER_T) return Boolean is
     (True);

   --  T_TEXTDISPLAY, 7.5.1.152: 10 bits, 0 .. 1022, 1 s
   type T_TEXTDISPLAY_T is range 0 .. 1023;
   T_TEXTDISPLAY_No_Time : constant T_TEXTDISPLAY_T := 1023;
   --  1023: no time
   function To_T_TEXTDISPLAY (V : Unsigned_64) return T_TEXTDISPLAY_T is
     (T_TEXTDISPLAY_T (V))
     with Pre => Fits (V, 10);
   function Code (X : T_TEXTDISPLAY_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 10);
   function Is_Valid (X : T_TEXTDISPLAY_T) return Boolean is
     (True);

   --  T_TRAIN, 7.5.1.154: 32 bits, 0 .. 4294967294, 10 ms
   type T_TRAIN_T is range 0 .. 4294967295;
   T_TRAIN_Unknown : constant T_TRAIN_T := 4294967295;
   --  4294967295: unknown
   function To_T_TRAIN (V : Unsigned_64) return T_TRAIN_T is
     (T_TRAIN_T (V))
     with Pre => Fits (V, 32);
   function Code (X : T_TRAIN_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 32);
   function Is_Valid (X : T_TRAIN_T) return Boolean is
     (X <= 4294967294 or else X = 4294967295);

   --  V_DIFF, 7.5.1.156: 7 bits, 0 .. 120, 5 km/h
   type V_DIFF_T is range 0 .. 127;
   function To_V_DIFF (V : Unsigned_64) return V_DIFF_T is
     (V_DIFF_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_DIFF_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_DIFF_T) return Boolean is
     (X <= 120);

   --  V_EMA, 7.5.1.157: 7 bits, 0 .. 120, 5 km/h
   type V_EMA_T is range 0 .. 127;
   function To_V_EMA (V : Unsigned_64) return V_EMA_T is
     (V_EMA_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_EMA_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_EMA_T) return Boolean is
     (X <= 120);

   --  V_MAIN, 7.5.1.158: 7 bits, 0 .. 120, 5 km/h
   type V_MAIN_T is range 0 .. 127;
   function To_V_MAIN (V : Unsigned_64) return V_MAIN_T is
     (V_MAIN_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_MAIN_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_MAIN_T) return Boolean is
     (X <= 120);

   --  V_NVALLOWOVTRP, 7.5.1.161: 7 bits, 0 .. 120, 5 km/h
   type V_NVALLOWOVTRP_T is range 0 .. 127;
   function To_V_NVALLOWOVTRP (V : Unsigned_64) return V_NVALLOWOVTRP_T is
     (V_NVALLOWOVTRP_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVALLOWOVTRP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVALLOWOVTRP_T) return Boolean is
     (X <= 120);

   --  V_NVKVINT, 7.5.1.161.1: 7 bits, 0 .. 120, 5 km/h
   type V_NVKVINT_T is range 0 .. 127;
   function To_V_NVKVINT (V : Unsigned_64) return V_NVKVINT_T is
     (V_NVKVINT_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVKVINT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVKVINT_T) return Boolean is
     (X <= 120);

   --  V_NVLIMSUPERV, 7.5.1.161.2: 7 bits, 0 .. 120, 5 km/h
   type V_NVLIMSUPERV_T is range 0 .. 127;
   function To_V_NVLIMSUPERV (V : Unsigned_64) return V_NVLIMSUPERV_T is
     (V_NVLIMSUPERV_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVLIMSUPERV_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVLIMSUPERV_T) return Boolean is
     (X <= 120);

   --  V_NVONSIGHT, 7.5.1.162: 7 bits, 0 .. 120, 5 km/h
   type V_NVONSIGHT_T is range 0 .. 127;
   function To_V_NVONSIGHT (V : Unsigned_64) return V_NVONSIGHT_T is
     (V_NVONSIGHT_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVONSIGHT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVONSIGHT_T) return Boolean is
     (X <= 120);

   --  V_NVREL, 7.5.1.164: 7 bits, 0 .. 120, 5 km/h
   type V_NVREL_T is range 0 .. 127;
   function To_V_NVREL (V : Unsigned_64) return V_NVREL_T is
     (V_NVREL_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVREL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVREL_T) return Boolean is
     (X <= 120);

   --  V_NVSHUNT, 7.5.1.165: 7 bits, 0 .. 120, 5 km/h
   type V_NVSHUNT_T is range 0 .. 127;
   function To_V_NVSHUNT (V : Unsigned_64) return V_NVSHUNT_T is
     (V_NVSHUNT_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVSHUNT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVSHUNT_T) return Boolean is
     (X <= 120);

   --  V_NVSTFF, 7.5.1.166: 7 bits, 0 .. 120, 5 km/h
   type V_NVSTFF_T is range 0 .. 127;
   function To_V_NVSTFF (V : Unsigned_64) return V_NVSTFF_T is
     (V_NVSTFF_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVSTFF_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVSTFF_T) return Boolean is
     (X <= 120);

   --  V_NVSUPOVTRP, 7.5.1.163: 7 bits, 0 .. 120, 5 km/h
   type V_NVSUPOVTRP_T is range 0 .. 127;
   function To_V_NVSUPOVTRP (V : Unsigned_64) return V_NVSUPOVTRP_T is
     (V_NVSUPOVTRP_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVSUPOVTRP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVSUPOVTRP_T) return Boolean is
     (X <= 120);

   --  V_NVUNFIT, 7.5.1.167: 7 bits, 0 .. 120, 5 km/h
   type V_NVUNFIT_T is range 0 .. 127;
   function To_V_NVUNFIT (V : Unsigned_64) return V_NVUNFIT_T is
     (V_NVUNFIT_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_NVUNFIT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_NVUNFIT_T) return Boolean is
     (X <= 120);

   --  V_RELEASEDP, 7.5.1.168: 7 bits, 0 .. 120, 5 km/h
   type V_RELEASEDP_T is range 0 .. 127;
   V_RELEASEDP_On_Board_Calculated : constant V_RELEASEDP_T := 126;
   --  126: on-board calculated
   V_RELEASEDP_National_Value : constant V_RELEASEDP_T := 127;
   --  127: national value
   function To_V_RELEASEDP (V : Unsigned_64) return V_RELEASEDP_T is
     (V_RELEASEDP_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_RELEASEDP_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_RELEASEDP_T) return Boolean is
     (X <= 120 or else X = 126 or else X = 127);

   --  V_RELEASEOL, 7.5.1.169: 7 bits, 0 .. 120, 5 km/h
   type V_RELEASEOL_T is range 0 .. 127;
   V_RELEASEOL_On_Board_Calculated : constant V_RELEASEOL_T := 126;
   --  126: on-board calculated
   V_RELEASEOL_National_Value : constant V_RELEASEOL_T := 127;
   --  127: national value
   function To_V_RELEASEOL (V : Unsigned_64) return V_RELEASEOL_T is
     (V_RELEASEOL_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_RELEASEOL_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_RELEASEOL_T) return Boolean is
     (X <= 120 or else X = 126 or else X = 127);

   --  V_SM, 7.5.1.170.1: 7 bits, 0 .. 120, 5 km/h
   type V_SM_T is range 0 .. 127;
   function To_V_SM (V : Unsigned_64) return V_SM_T is
     (V_SM_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_SM_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_SM_T) return Boolean is
     (X <= 120);

   --  V_STATIC, 7.5.1.171: 7 bits, 0 .. 120, 5 km/h
   type V_STATIC_T is range 0 .. 127;
   V_STATIC_End_Of_Description : constant V_STATIC_T := 127;
   --  127: end of description
   function To_V_STATIC (V : Unsigned_64) return V_STATIC_T is
     (V_STATIC_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_STATIC_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_STATIC_T) return Boolean is
     (X <= 120 or else X = 127);

   --  V_TRAIN, 7.5.1.172: 7 bits, 0 .. 120, 5 km/h
   type V_TRAIN_T is range 0 .. 127;
   V_TRAIN_Standstill : constant V_TRAIN_T := 127;
   --  127: standstill
   function To_V_TRAIN (V : Unsigned_64) return V_TRAIN_T is
     (V_TRAIN_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_TRAIN_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_TRAIN_T) return Boolean is
     (X <= 120 or else X = 127);

   --  V_TSR, 7.5.1.173: 7 bits, 0 .. 120, 5 km/h
   type V_TSR_T is range 0 .. 127;
   function To_V_TSR (V : Unsigned_64) return V_TSR_T is
     (V_TSR_T (V))
     with Pre => Fits (V, 7);
   function Code (X : V_TSR_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 7);
   function Is_Valid (X : V_TSR_T) return Boolean is
     (X <= 120);

   --  X_TEXT, 7.5.1.174: 8 bits, 0 .. 255, ISO 8859-1 character
   type X_TEXT_T is range 0 .. 255;
   function To_X_TEXT (V : Unsigned_64) return X_TEXT_T is
     (X_TEXT_T (V))
     with Pre => Fits (V, 8);
   function Code (X : X_TEXT_T) return Unsigned_64 is
     (Unsigned_64 (X))
     with Post => Fits (Code'Result, 8);
   function Is_Valid (X : X_TEXT_T) return Boolean is
     (True);

   --  NID_LRBG and the other identities of a balise group given as
   --  NID_C + NID_BG (10 + 14 bits, 7.5.1.90) as one number
   function Balise_Group_Identity
     (C : NID_C_T; BG : NID_BG_T) return Unsigned_64
   is (Shift_Left (Code (C), 14) or Code (BG));

end ETCS_Variables;
