--  ETCS on-board (EVC)
--  Packet 9, train to track: Level 2 transition information, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Train_Packets.P9
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      L_PACKET   : L_PACKET_T;
      NID_C      : NID_C_T;
      NID_BG     : NID_BG_T;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_BG := To_NID_BG (V);
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         NID_C => NID_C,
         NID_BG => NID_BG);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_BG));
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P9;
