--  ETCS on-board (EVC)
--  Packet 73, track to train: Packet for sending plain text messages.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.23. Sent by: Balise, RBC.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P73
  with SPARK_Mode => On
is

   NID : constant := 73;
   Name : constant String := "Packet for sending plain text messages";

   type X_TEXT_Array is array (1 .. 255) of X_TEXT_T;

   type Packet_T is record
      NID_PACKET            : NID_PACKET_T := NID;
      Q_DIR                 : Q_DIR_T := 0;
      L_PACKET              : L_PACKET_T := 0;
      Q_SCALE               : Q_SCALE_T := 0;
      Q_TEXTCLASS           : Q_TEXTCLASS_T := 0;
      Q_TEXTDISPLAY         : Q_TEXTDISPLAY_T := 0;
      D_TEXTDISPLAY         : D_TEXTDISPLAY_T := 0;
      M_MODETEXTDISPLAY     : M_MODETEXTDISPLAY_T := 0;
      M_LEVELTEXTDISPLAY    : M_LEVELTEXTDISPLAY_T := 0;
      --  present when M_LEVELTEXTDISPLAY == 1
      Has_NID_NTC           : Boolean := False;
      NID_NTC               : NID_NTC_T := 0;
      L_TEXTDISPLAY         : L_TEXTDISPLAY_T := 0;
      T_TEXTDISPLAY         : T_TEXTDISPLAY_T := 0;
      M_MODETEXTDISPLAY_2   : M_MODETEXTDISPLAY_T := 0;
      M_LEVELTEXTDISPLAY_2  : M_LEVELTEXTDISPLAY_T := 0;
      --  present when M_LEVELTEXTDISPLAY == 1
      Has_NID_NTC_2         : Boolean := False;
      NID_NTC_2             : NID_NTC_T := 0;
      Q_TEXTCONFIRM         : Q_TEXTCONFIRM_T := 0;
      --  present when Q_TEXTCONFIRM != 0
      Has_Q_CONFTEXTDISPLAY : Boolean := False;
      Q_CONFTEXTDISPLAY     : Q_CONFTEXTDISPLAY_T := 0;
      Q_TEXTREPORT          : Q_TEXTREPORT_T := 0;
      --  present when Q_TEXTREPORT == 1
      Has_NID_TEXTMESSAGE   : Boolean := False;
      NID_TEXTMESSAGE       : NID_TEXTMESSAGE_T := 0;
      NID_C                 : NID_C_T := 0;
      NID_RBC               : NID_RBC_T := 0;
      L_TEXT                : L_TEXT_T := 0;
      --  loop over L_TEXT
      X_TEXT_List           : X_TEXT_Array := (others => 0);
   end record;

   --  Every variable read holds a value of 7.5, not a spare one
   --  (Is_Valid of its type; SUBSET-026 3.16.1.1.1): those of the
   --  packet, of the conditional blocks present and of the items of
   --  its loops. Decode does not check it.
   function Valid (P : Packet_T) return Boolean;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P73;
