--  ETCS on-board (EVC)
--  Packet 31, track to train: RBC transition order for RBC interfaced to FRMCS
--  only, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P31
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.D_RBCTR)
      and then Is_Valid (P.NID_C)
      and then Is_Valid (P.NID_RBC)
      and then Is_Valid (P.Q_SLEEPSESSION));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET     : NID_PACKET_T;
      Q_DIR          : Q_DIR_T;
      L_PACKET       : L_PACKET_T;
      Q_SCALE        : Q_SCALE_T;
      D_RBCTR        : D_RBCTR_T;
      NID_C          : NID_C_T;
      NID_RBC        : NID_RBC_T;
      Q_SLEEPSESSION : Q_SLEEPSESSION_T;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      D_RBCTR := To_D_RBCTR (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_RBC := To_NID_RBC (V);
      Read (R, 1, V);
      Q_SLEEPSESSION := To_Q_SLEEPSESSION (V);
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         D_RBCTR => D_RBCTR,
         NID_C => NID_C,
         NID_RBC => NID_RBC,
         Q_SLEEPSESSION => Q_SLEEPSESSION);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_RBCTR));
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_RBC));
      Write (W, 1, Code (P.Q_SLEEPSESSION));
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P31;
