--  ETCS on-board (EVC)
--  Packet 3, track to train: National Values.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.1.1. Sent by: Balise, RBC.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P3
  with SPARK_Mode => On
is

   NID : constant := 3;
   Name : constant String := "National Values";

   type NID_C_Array is array (1 .. 31) of NID_C_T;

   type V_NVKVINT_Item_2 is record
      V_NVKVINT       : V_NVKVINT_T := 0;
      M_NVKVINT       : M_NVKVINT_T := 0;
      --  present when Q_NVKVINTSET == 1
      Has_M_NVKVINT_2 : Boolean := False;
      M_NVKVINT_2     : M_NVKVINT_T := 0;
   end record;

   type V_NVKVINT_Array_2 is array (1 .. 31) of V_NVKVINT_Item_2;

   type V_NVKVINT_Item is record
      V_NVKVINT       : V_NVKVINT_T := 0;
      M_NVKVINT       : M_NVKVINT_T := 0;
      --  present when Q_NVKVINTSET == 1
      Has_M_NVKVINT_2 : Boolean := False;
      M_NVKVINT_2     : M_NVKVINT_T := 0;
   end record;

   type V_NVKVINT_Array is array (1 .. 31) of V_NVKVINT_Item;

   type Q_NVKVINTSET_Item is record
      Q_NVKVINTSET    : Q_NVKVINTSET_T := 0;
      --  present when Q_NVKVINTSET == 1
      Has_A_NVP12     : Boolean := False;
      A_NVP12         : A_NVP12_T := 0;
      A_NVP23         : A_NVP23_T := 0;
      V_NVKVINT       : V_NVKVINT_T := 0;
      M_NVKVINT       : M_NVKVINT_T := 0;
      --  present when Q_NVKVINTSET == 1
      Has_M_NVKVINT_2 : Boolean := False;
      M_NVKVINT_2     : M_NVKVINT_T := 0;
      N_ITER          : N_ITER_T := 0;
      --  loop over N_ITER
      V_NVKVINT_List  : V_NVKVINT_Array_2;
   end record;

   type Q_NVKVINTSET_Array is array (1 .. 31) of Q_NVKVINTSET_Item;

   type L_NVKRINT_Item is record
      L_NVKRINT : L_NVKRINT_T := 0;
      M_NVKRINT : M_NVKRINT_T := 0;
   end record;

   type L_NVKRINT_Array is array (1 .. 31) of L_NVKRINT_Item;

   type Packet_T is record
      NID_PACKET        : NID_PACKET_T := NID;
      Q_DIR             : Q_DIR_T := 0;
      L_PACKET          : L_PACKET_T := 0;
      Q_SCALE           : Q_SCALE_T := 0;
      D_VALIDNV         : D_VALIDNV_T := 0;
      NID_C             : NID_C_T := 0;
      N_ITER            : N_ITER_T := 0;
      --  loop over N_ITER
      NID_C_List        : NID_C_Array := (others => 0);
      V_NVSHUNT         : V_NVSHUNT_T := 0;
      V_NVSTFF          : V_NVSTFF_T := 0;
      V_NVONSIGHT       : V_NVONSIGHT_T := 0;
      V_NVLIMSUPERV     : V_NVLIMSUPERV_T := 0;
      V_NVUNFIT         : V_NVUNFIT_T := 0;
      V_NVREL           : V_NVREL_T := 0;
      D_NVROLL          : D_NVROLL_T := 0;
      Q_NVSBTSMPERM     : Q_NVSBTSMPERM_T := 0;
      Q_NVEMRRLS        : Q_NVEMRRLS_T := 0;
      Q_NVGUIPERM       : Q_NVGUIPERM_T := 0;
      Q_NVSBFBPERM      : Q_NVSBFBPERM_T := 0;
      Q_NVINHSMICPERM   : Q_NVINHSMICPERM_T := 0;
      V_NVALLOWOVTRP    : V_NVALLOWOVTRP_T := 0;
      V_NVSUPOVTRP      : V_NVSUPOVTRP_T := 0;
      D_NVOVTRP         : D_NVOVTRP_T := 0;
      T_NVOVTRP         : T_NVOVTRP_T := 0;
      D_NVPOTRP         : D_NVPOTRP_T := 0;
      M_NVCONTACT       : M_NVCONTACT_T := 0;
      T_NVCONTACT       : T_NVCONTACT_T := 0;
      M_NVDERUN         : M_NVDERUN_T := 0;
      D_NVSTFF          : D_NVSTFF_T := 0;
      Q_NVDRIVER_ADHES  : Q_NVDRIVER_ADHES_T := 0;
      A_NVMAXREDADH1    : A_NVMAXREDADH1_T := 0;
      A_NVMAXREDADH2    : A_NVMAXREDADH2_T := 0;
      A_NVMAXREDADH3    : A_NVMAXREDADH3_T := 0;
      Q_NVLOCACC        : Q_NVLOCACC_T := 0;
      M_NVAVADH         : M_NVAVADH_T := 0;
      M_NVEBCL          : M_NVEBCL_T := 0;
      Q_NVKINT          : Q_NVKINT_T := 0;
      --  present when Q_NVKINT == 1
      Has_Q_NVKVINTSET  : Boolean := False;
      Q_NVKVINTSET      : Q_NVKVINTSET_T := 0;
      --  present when Q_NVKVINTSET == 1
      Has_A_NVP12       : Boolean := False;
      A_NVP12           : A_NVP12_T := 0;
      A_NVP23           : A_NVP23_T := 0;
      V_NVKVINT         : V_NVKVINT_T := 0;
      M_NVKVINT         : M_NVKVINT_T := 0;
      --  present when Q_NVKVINTSET == 1
      Has_M_NVKVINT_2   : Boolean := False;
      M_NVKVINT_2       : M_NVKVINT_T := 0;
      N_ITER_2          : N_ITER_T := 0;
      --  loop over N_ITER
      V_NVKVINT_List    : V_NVKVINT_Array;
      N_ITER_3          : N_ITER_T := 0;
      --  loop over N_ITER
      Q_NVKVINTSET_List : Q_NVKVINTSET_Array;
      L_NVKRINT         : L_NVKRINT_T := 0;
      M_NVKRINT         : M_NVKRINT_T := 0;
      N_ITER_4          : N_ITER_T := 0;
      --  loop over N_ITER
      L_NVKRINT_List    : L_NVKRINT_Array;
      M_NVKTINT         : M_NVKTINT_T := 0;
   end record;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P3;
