--  ETCS on-board (EVC)
--  Packet 143, track to train: Session Management with neighbouring Radio
--  Infill Unit, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P143
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      Q_DIR      : Q_DIR_T;
      L_PACKET   : L_PACKET_T;
      Q_RIU      : Q_RIU_T;
      NID_C      : NID_C_T;
      NID_RIU    : NID_RIU_T;
      NID_RADIO  : NID_RADIO_T;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 1, V);
      Q_RIU := To_Q_RIU (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_RIU := To_NID_RIU (V);
      Read (R, 64, V);
      NID_RADIO := To_NID_RADIO (V);
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_RIU => Q_RIU,
         NID_C => NID_C,
         NID_RIU => NID_RIU,
         NID_RADIO => NID_RADIO);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 1, Code (P.Q_RIU));
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_RIU));
      Write (W, 64, Code (P.NID_RADIO));
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P143;
