--  ETCS on-board (EVC)
--  Packet 88, track to train: Level Crossing information, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P88
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET   : NID_PACKET_T;
      Q_DIR        : Q_DIR_T;
      L_PACKET     : L_PACKET_T;
      Q_SCALE      : Q_SCALE_T;
      NID_LX       : NID_LX_T;
      D_LX         : D_LX_T;
      L_LX         : L_LX_T;
      Q_LXSTATUS   : Q_LXSTATUS_T;
      Has_V_LX     : Boolean;
      V_LX         : V_LX_T := 0;
      Q_STOPLX     : Q_STOPLX_T := 0;
      Has_L_STOPLX : Boolean := False;
      L_STOPLX     : L_STOPLX_T := 0;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 8, V);
      NID_LX := To_NID_LX (V);
      Read (R, 15, V);
      D_LX := To_D_LX (V);
      Read (R, 15, V);
      L_LX := To_L_LX (V);
      Read (R, 1, V);
      Q_LXSTATUS := To_Q_LXSTATUS (V);
      Has_V_LX := Q_LXSTATUS = 1;
      if Has_V_LX then
         Read (R, 7, V);
         V_LX := To_V_LX (V);
         Read (R, 1, V);
         Q_STOPLX := To_Q_STOPLX (V);
         Has_L_STOPLX := Q_STOPLX = 1;
         if Has_L_STOPLX then
            Read (R, 15, V);
            L_STOPLX := To_L_STOPLX (V);
         end if;
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         NID_LX => NID_LX,
         D_LX => D_LX,
         L_LX => L_LX,
         Q_LXSTATUS => Q_LXSTATUS,
         Has_V_LX => Has_V_LX,
         V_LX => V_LX,
         Q_STOPLX => Q_STOPLX,
         Has_L_STOPLX => Has_L_STOPLX,
         L_STOPLX => L_STOPLX);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 8, Code (P.NID_LX));
      Write (W, 15, Code (P.D_LX));
      Write (W, 15, Code (P.L_LX));
      Write (W, 1, Code (P.Q_LXSTATUS));
      if P.Has_V_LX /= (P.Q_LXSTATUS = 1) then
         Good := False;
      end if;
      if P.Q_LXSTATUS = 1 then
         Write (W, 7, Code (P.V_LX));
         Write (W, 1, Code (P.Q_STOPLX));
         if P.Has_L_STOPLX /= (P.Q_STOPLX = 1) then
            Good := False;
         end if;
         if P.Q_STOPLX = 1 then
            Write (W, 15, Code (P.L_STOPLX));
         end if;
      end if;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P88;
