--  ETCS on-board (EVC)
--  Packet 136, track to train: Infill location reference, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P136
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
   begin
      P := (others => <>);
      Read (R, 8, V);
      P.NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      P.Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      P.L_PACKET := To_L_PACKET (V);
      Read (R, 1, V);
      P.Q_NEWCOUNTRY := To_Q_NEWCOUNTRY (V);
      P.Has_NID_C := P.Q_NEWCOUNTRY = 1;
      if P.Has_NID_C then
         Read (R, 10, V);
         P.NID_C := To_NID_C (V);
      end if;
      Read (R, 14, V);
      P.NID_BG := To_NID_BG (V);
      OK := not Failed (R)
        and then P.NID_PACKET = NID
        and then Position (R) = Start + Natural (P.L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 1, Code (P.Q_NEWCOUNTRY));
      if P.Has_NID_C /= (P.Q_NEWCOUNTRY = 1) then
         Good := False;
      end if;
      if P.Q_NEWCOUNTRY = 1 then
         Write (W, 10, Code (P.NID_C));
      end if;
      Write (W, 14, Code (P.NID_BG));
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P136;
