--  ETCS on-board (EVC)
--  Packet 143, track to train: Session Management with neighbouring Radio
--  Infill Unit, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P143
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_RIU)
      and then Is_Valid (P.NID_C)
      and then Is_Valid (P.NID_RIU)
      and then Is_Valid (P.NID_RADIO));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      Q_DIR      : Q_DIR_T;
      L_PACKET   : L_PACKET_T;
      Q_RIU      : Q_RIU_T;
      NID_C      : NID_C_T;
      NID_RIU    : NID_RIU_T;
      NID_RADIO  : NID_RADIO_T;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 1, V);
      Q_RIU := To_Q_RIU (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_RIU := To_NID_RIU (V);
      Read (R, 64, V);
      NID_RADIO := To_NID_RADIO (V);
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_RIU => Q_RIU,
         NID_C => NID_C,
         NID_RIU => NID_RIU,
         NID_RADIO => NID_RADIO);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 1, Code (P.Q_RIU));
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_RIU));
      Write (W, 64, Code (P.NID_RADIO));
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P143;
