--  ETCS on-board (EVC)
--  Packet 6, track to train: Virtual Balise Cover order, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P6
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_VBCO)
      and then Is_Valid (P.NID_VBCMK)
      and then Is_Valid (P.NID_C)
      and then (if P.Has_T_VBC then Is_Valid (P.T_VBC)));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      Q_DIR      : Q_DIR_T;
      L_PACKET   : L_PACKET_T;
      Q_VBCO     : Q_VBCO_T;
      NID_VBCMK  : NID_VBCMK_T;
      NID_C      : NID_C_T;
      Has_T_VBC  : Boolean;
      T_VBC      : T_VBC_T := 0;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 1, V);
      Q_VBCO := To_Q_VBCO (V);
      Read (R, 6, V);
      NID_VBCMK := To_NID_VBCMK (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Has_T_VBC := Q_VBCO = 1;
      if Has_T_VBC then
         Read (R, 8, V);
         T_VBC := To_T_VBC (V);
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_VBCO => Q_VBCO,
         NID_VBCMK => NID_VBCMK,
         NID_C => NID_C,
         Has_T_VBC => Has_T_VBC,
         T_VBC => T_VBC);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 1, Code (P.Q_VBCO));
      Write (W, 6, Code (P.NID_VBCMK));
      Write (W, 10, Code (P.NID_C));
      if P.Has_T_VBC /= (P.Q_VBCO = 1) then
         Good := False;
      end if;
      if P.Q_VBCO = 1 then
         Write (W, 8, Code (P.T_VBC));
      end if;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P6;
