--  ETCS on-board (EVC)
--  Packet 39, track to train: Track Condition Change of traction system,
--  implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P39
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET        : NID_PACKET_T;
      Q_DIR             : Q_DIR_T;
      L_PACKET          : L_PACKET_T;
      Q_SCALE           : Q_SCALE_T;
      D_TRACTION        : D_TRACTION_T;
      M_VOLTAGE         : M_VOLTAGE_T;
      Has_NID_CTRACTION : Boolean;
      NID_CTRACTION     : NID_CTRACTION_T := 0;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      D_TRACTION := To_D_TRACTION (V);
      Read (R, 4, V);
      M_VOLTAGE := To_M_VOLTAGE (V);
      Has_NID_CTRACTION := M_VOLTAGE /= 0;
      if Has_NID_CTRACTION then
         Read (R, 10, V);
         NID_CTRACTION := To_NID_CTRACTION (V);
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         D_TRACTION => D_TRACTION,
         M_VOLTAGE => M_VOLTAGE,
         Has_NID_CTRACTION => Has_NID_CTRACTION,
         NID_CTRACTION => NID_CTRACTION);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_TRACTION));
      Write (W, 4, Code (P.M_VOLTAGE));
      if P.Has_NID_CTRACTION /= (P.M_VOLTAGE /= 0) then
         Good := False;
      end if;
      if P.M_VOLTAGE /= 0 then
         Write (W, 10, Code (P.NID_CTRACTION));
      end if;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P39;
