--  ETCS on-board (EVC)
--  The track to train packets: the standard header.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Track_Packets
  with SPARK_Mode => On
is

   procedure Decode_Header (R          : in out Reader;
                            NID_PACKET : out NID_PACKET_T;
                            Q_DIR      : out Q_DIR_T;
                            L_PACKET   : out L_PACKET_T)
   is
      V : Unsigned_64;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
   end Decode_Header;

   procedure Encode_Header (W         : in out Writer;
                            NID       : Unsigned_64;
                            Q_DIR     : Unsigned_64;
                            Length_At : out Natural)
   is
   begin
      Write (W, 8, NID);
      Write (W, 2, Q_DIR);
      Length_At := Position (W);
      Write (W, 13, 0);
   end Encode_Header;

   procedure Finish_Length (W         : in out Writer;
                            Start     : Bit_Count;
                            Length_At : Natural;
                            Good      : in out Boolean)
   is
   begin
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
   end Finish_Length;

end ETCS_Track_Packets;
