--  ETCS on-board (EVC)
--  Packet 68, track to train: Track Condition.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.20. Sent by: Balise, Euroloop, RBC, RIU.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P68
  with SPARK_Mode => On
is

   NID : constant := 68;
   Name : constant String := "Track Condition";

   type D_TRACKCOND_Item is record
      D_TRACKCOND : D_TRACKCOND_T := 0;
      L_TRACKCOND : L_TRACKCOND_T := 0;
      M_TRACKCOND : M_TRACKCOND_T := 0;
   end record;

   type D_TRACKCOND_Array is array (1 .. 31) of D_TRACKCOND_Item;

   type Packet_T is record
      NID_PACKET       : NID_PACKET_T := NID;
      Q_DIR            : Q_DIR_T := 0;
      L_PACKET         : L_PACKET_T := 0;
      Q_SCALE          : Q_SCALE_T := 0;
      Q_TRACKINIT      : Q_TRACKINIT_T := 0;
      --  present when Q_TRACKINIT == 1
      Has_D_TRACKINIT  : Boolean := False;
      D_TRACKINIT      : D_TRACKINIT_T := 0;
      --  present when Q_TRACKINIT == 0
      Has_D_TRACKCOND  : Boolean := False;
      D_TRACKCOND      : D_TRACKCOND_T := 0;
      L_TRACKCOND      : L_TRACKCOND_T := 0;
      M_TRACKCOND      : M_TRACKCOND_T := 0;
      N_ITER           : N_ITER_T := 0;
      --  loop over N_ITER
      D_TRACKCOND_List : D_TRACKCOND_Array;
   end record;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P68;
