--  ETCS on-board (EVC)
--  Packet 0, track to train: Virtual Balise Cover marker, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P0
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      V     : Unsigned_64;
   begin
      P := (others => <>);
      Read (R, 8, V);
      P.NID_PACKET := To_NID_PACKET (V);
      Read (R, 6, V);
      P.NID_VBCMK := To_NID_VBCMK (V);
      OK := not Failed (R)
        and then P.NID_PACKET = NID;
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
   begin
      Write (W, 8, NID);
      Write (W, 6, Code (P.NID_VBCMK));
      OK := not Failed (W);
   end Encode;

end ETCS_Track_Packets.P0;
