--  ETCS on-board (EVC)
--  Packet 131, track to train: RBC transition order for RBC interfaced to
--  GSM-R.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.27. Sent by: Balise, RBC.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P131
  with SPARK_Mode => On
is

   NID : constant := 131;
   Name : constant String :=
     "RBC transition order for RBC interfaced to GSM-R";

   type Packet_T is record
      NID_PACKET     : NID_PACKET_T := NID;
      Q_DIR          : Q_DIR_T := 0;
      L_PACKET       : L_PACKET_T := 0;
      Q_SCALE        : Q_SCALE_T := 0;
      D_RBCTR        : D_RBCTR_T := 0;
      NID_C          : NID_C_T := 0;
      NID_RBC        : NID_RBC_T := 0;
      NID_RADIO      : NID_RADIO_T := 0;
      Q_SLEEPSESSION : Q_SLEEPSESSION_T := 0;
   end record;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P131;
