--  ETCS on-board (EVC)
--  Packet 9, train to track: Level 2 transition information, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Train_Packets.P9
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.NID_C)
      and then Is_Valid (P.NID_BG));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      L_PACKET   : L_PACKET_T;
      NID_C      : NID_C_T;
      NID_BG     : NID_BG_T;
   begin
      Decode_Header (R, NID_PACKET, L_PACKET);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_BG := To_NID_BG (V);
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         NID_C => NID_C,
         NID_BG => NID_BG);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Length_At);
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_BG));
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P9;
