--  ETCS on-board (EVC)
--  Packet 58, track to train: Position Report Parameters, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P58
  with SPARK_Mode => On
is

   --  One item of D_LOC_List
   procedure Decode_D_LOC_Item
     (R  : in out Reader;
      E1 : out D_LOC_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      Read (R, 15, V);
      E1.D_LOC := To_D_LOC (V);
      Read (R, 1, V);
      E1.Q_LGTLOC := To_Q_LGTLOC (V);
   end Decode_D_LOC_Item;

   --  One item of D_LOC_List
   procedure Encode_D_LOC_Item
     (E1 : D_LOC_Item;
      W  : in out Writer)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 15, Code (E1.D_LOC));
      Write (W, 1, Code (E1.Q_LGTLOC));
   end Encode_D_LOC_Item;

   --  Valid of one item of D_LOC_List
   function Valid_D_LOC_Item (E1 : D_LOC_Item) return Boolean is
     (Is_Valid (E1.D_LOC)
      and then Is_Valid (E1.Q_LGTLOC));

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.T_CYCLOC)
      and then Is_Valid (P.D_CYCLOC)
      and then Is_Valid (P.M_LOC)
      and then Is_Valid (P.N_ITER)
      and then (for all I1 in 1 .. Natural (P.N_ITER) =>
                  Valid_D_LOC_Item (P.D_LOC_List (I1))));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      Q_DIR      : Q_DIR_T;
      L_PACKET   : L_PACKET_T;
      Q_SCALE    : Q_SCALE_T;
      T_CYCLOC   : T_CYCLOC_T;
      D_CYCLOC   : D_CYCLOC_T;
      M_LOC      : M_LOC_T;
      N_ITER     : N_ITER_T;
      D_LOC_List : D_LOC_Array;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 8, V);
      T_CYCLOC := To_T_CYCLOC (V);
      Read (R, 15, V);
      D_CYCLOC := To_D_CYCLOC (V);
      Read (R, 3, V);
      M_LOC := To_M_LOC (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_D_LOC_Item (R, D_LOC_List (I1));
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         T_CYCLOC => T_CYCLOC,
         D_CYCLOC => D_CYCLOC,
         M_LOC => M_LOC,
         N_ITER => N_ITER,
         D_LOC_List => D_LOC_List);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 8, Code (P.T_CYCLOC));
      Write (W, 15, Code (P.D_CYCLOC));
      Write (W, 3, Code (P.M_LOC));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_D_LOC_Item (P.D_LOC_List (I1), W);
      end loop;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P58;
