--  ETCS on-board (EVC)
--  Packet 80, track to train: Mode profile, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P80
  with SPARK_Mode => On
is

   --  One item of D_MAMODE_List
   procedure Decode_D_MAMODE_Item
     (R  : in out Reader;
      E1 : out D_MAMODE_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      Read (R, 15, V);
      E1.D_MAMODE := To_D_MAMODE (V);
      Read (R, 2, V);
      E1.M_MAMODE := To_M_MAMODE (V);
      Read (R, 7, V);
      E1.V_MAMODE := To_V_MAMODE (V);
      Read (R, 15, V);
      E1.L_MAMODE := To_L_MAMODE (V);
      Read (R, 15, V);
      E1.L_ACKMAMODE := To_L_ACKMAMODE (V);
      Read (R, 1, V);
      E1.Q_MAMODE := To_Q_MAMODE (V);
   end Decode_D_MAMODE_Item;

   --  One item of D_MAMODE_List
   procedure Encode_D_MAMODE_Item
     (E1 : D_MAMODE_Item;
      W  : in out Writer)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 15, Code (E1.D_MAMODE));
      Write (W, 2, Code (E1.M_MAMODE));
      Write (W, 7, Code (E1.V_MAMODE));
      Write (W, 15, Code (E1.L_MAMODE));
      Write (W, 15, Code (E1.L_ACKMAMODE));
      Write (W, 1, Code (E1.Q_MAMODE));
   end Encode_D_MAMODE_Item;

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET    : NID_PACKET_T;
      Q_DIR         : Q_DIR_T;
      L_PACKET      : L_PACKET_T;
      Q_SCALE       : Q_SCALE_T;
      D_MAMODE      : D_MAMODE_T;
      M_MAMODE      : M_MAMODE_T;
      V_MAMODE      : V_MAMODE_T;
      L_MAMODE      : L_MAMODE_T;
      L_ACKMAMODE   : L_ACKMAMODE_T;
      Q_MAMODE      : Q_MAMODE_T;
      N_ITER        : N_ITER_T;
      D_MAMODE_List : D_MAMODE_Array;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      D_MAMODE := To_D_MAMODE (V);
      Read (R, 2, V);
      M_MAMODE := To_M_MAMODE (V);
      Read (R, 7, V);
      V_MAMODE := To_V_MAMODE (V);
      Read (R, 15, V);
      L_MAMODE := To_L_MAMODE (V);
      Read (R, 15, V);
      L_ACKMAMODE := To_L_ACKMAMODE (V);
      Read (R, 1, V);
      Q_MAMODE := To_Q_MAMODE (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_D_MAMODE_Item (R, D_MAMODE_List (I1));
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         D_MAMODE => D_MAMODE,
         M_MAMODE => M_MAMODE,
         V_MAMODE => V_MAMODE,
         L_MAMODE => L_MAMODE,
         L_ACKMAMODE => L_ACKMAMODE,
         Q_MAMODE => Q_MAMODE,
         N_ITER => N_ITER,
         D_MAMODE_List => D_MAMODE_List);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_MAMODE));
      Write (W, 2, Code (P.M_MAMODE));
      Write (W, 7, Code (P.V_MAMODE));
      Write (W, 15, Code (P.L_MAMODE));
      Write (W, 15, Code (P.L_ACKMAMODE));
      Write (W, 1, Code (P.Q_MAMODE));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_D_MAMODE_Item (P.D_MAMODE_List (I1), W);
      end loop;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P80;
