--  ETCS on-board (EVC)
--  The catalogue of the radio messages, SUBSET-026 8.5 to 8.7.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  NID_MESSAGE of each direction to its kind (8.5.2, 8.5.3); for
--  every message its variables in the order of 8.4.4.6.1 /
--  8.4.4.7.1 and of its table (the header included), and the rules
--  for its packets: the mandatory ones in their order (8.4.1.2),
--  then the optional ones of 8.4.4.4, which may come in any order
--  (8.4.1.3); a rule may allow several instances (8.4.1.4.1 to
--  8.4.1.4.5, 8.4.1.5.1) or only some senders (message 24).
--  ETCS_Message parses a message against these rules.

with ETCS_Catalogue; use ETCS_Catalogue;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Message_Catalogue
  with SPARK_Mode => On
is

   type Message_Kind_T is
     (Unknown,
      Track_M2,
      Track_M3,
      Track_M15,
      Track_M24,
      Track_M37,
      Track_M38,
      Track_M39,
      Train_M129,
      Train_M132,
      Train_M136,
      Train_M146,
      Train_M157,
      Train_M159);

   subtype Known_Message_T is Message_Kind_T
     range Track_M2 .. Train_M159;

   --  The kind of message NID_MESSAGE = NID in this direction
   function Kind (Direction : Direction_T; NID : Natural)
     return Message_Kind_T;

   function Name (Kind : Known_Message_T) return String;
   function Clause (Kind : Known_Message_T) return String;

   --  8.5.2 "Transmitted to", 8.5.3 "Transmitted by"
   function Sent_By (Kind : Known_Message_T) return Senders_T;

   NID_Of : constant array (Known_Message_T) of Natural :=
     (Track_M2 => 2,
      Track_M3 => 3,
      Track_M15 => 15,
      Track_M24 => 24,
      Track_M37 => 37,
      Track_M38 => 38,
      Track_M39 => 39,
      Train_M129 => 129,
      Train_M132 => 132,
      Train_M136 => 136,
      Train_M146 => 146,
      Train_M157 => 157,
      Train_M159 => 159);

   Direction_Of : constant array (Known_Message_T) of Direction_T :=
     (Track_M2 => Track_To_Train,
      Track_M3 => Track_To_Train,
      Track_M15 => Track_To_Train,
      Track_M24 => Track_To_Train,
      Track_M37 => Track_To_Train,
      Track_M38 => Track_To_Train,
      Track_M39 => Track_To_Train,
      Train_M129 => Train_To_Track,
      Train_M132 => Train_To_Track,
      Train_M136 => Train_To_Track,
      Train_M146 => Train_To_Track,
      Train_M157 => Train_To_Track,
      Train_M159 => Train_To_Track);

   --  The variables of a message, header included
   Max_Fields : constant := 11;
   subtype Field_Count_T is Natural range 0 .. Max_Fields;
   subtype Field_Index_T is Positive range 1 .. Max_Fields;
   type Field_Array is array (Field_Index_T) of Variable_T;

   Field_Count : constant array (Known_Message_T) of Field_Count_T :=
     (Track_M2 => 8,
      Track_M3 => 6,
      Track_M15 => 11,
      Track_M24 => 6,
      Track_M37 => 6,
      Track_M38 => 4,
      Track_M39 => 6,
      Train_M129 => 4,
      Train_M132 => 5,
      Train_M136 => 4,
      Train_M146 => 5,
      Train_M157 => 5,
      Train_M159 => 4);

   Fields : constant array (Known_Message_T) of Field_Array :=
     (Track_M2 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        5 => NID_C, 6 => NID_BG, 7 => Q_SCALE, 8 => D_SR,
        others => NID_MESSAGE),
      Track_M3 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        5 => NID_C, 6 => NID_BG, others => NID_MESSAGE),
      Track_M15 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        5 => NID_C, 6 => NID_BG, 7 => NID_EM, 8 => Q_SCALE, 9 => D_REF,
        10 => Q_DIR, 11 => D_EMERGENCYSTOP),
      Track_M24 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        5 => NID_C, 6 => NID_BG, others => NID_MESSAGE),
      Track_M37 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        5 => NID_C, 6 => NID_BG, others => NID_MESSAGE),
      Track_M38 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        others => NID_MESSAGE),
      Track_M39 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => M_ACK,
        5 => NID_C, 6 => NID_BG, others => NID_MESSAGE),
      Train_M129 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => NID_ENGINE,
        others => NID_MESSAGE),
      Train_M132 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => NID_ENGINE,
        5 => Q_MARQSTREASON, others => NID_MESSAGE),
      Train_M136 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => NID_ENGINE,
        others => NID_MESSAGE),
      Train_M146 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => NID_ENGINE,
        5 => T_TRAIN, others => NID_MESSAGE),
      Train_M157 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => NID_ENGINE,
        5 => Q_STATUSLRBG, others => NID_MESSAGE),
      Train_M159 =>
        (1 => NID_MESSAGE, 2 => L_MESSAGE, 3 => T_TRAIN, 4 => NID_ENGINE,
        others => NID_MESSAGE));

   --  A packet of a message: NID_PACKET First, or Second (the
   --  "one_of" of the position report, packet 0 or 1; Second =
   --  First otherwise)
   type Packet_NID_T is range 0 .. 255;
   type Rule_T is record
      First, Second : Packet_NID_T;
      Optional      : Boolean;
      Repeat        : Boolean;    -- several instances allowed
      From          : Senders_T;  -- the senders it may come from
   end record;

   --  The rules of all messages, one after the other: those of
   --  message K are Rules (First_Rule (K) .. First_Rule (K) +
   --  Rule_Count (K) - 1)
   Total_Rules : constant := 108;
   subtype Rule_Index_T is Positive range 1 .. Total_Rules;
   subtype Rule_Count_T is Natural range 0 .. Total_Rules;

   First_Rule : constant array (Known_Message_T) of Rule_Index_T :=
     (Track_M2 => 1,
      Track_M3 => 2,
      Track_M15 => 38,
      Track_M24 => 38,
      Track_M37 => 73,
      Track_M38 => 94,
      Track_M39 => 94,
      Train_M129 => 94,
      Train_M132 => 96,
      Train_M136 => 98,
      Train_M146 => 102,
      Train_M157 => 102,
      Train_M159 => 108);

   Rule_Count : constant array (Known_Message_T) of Rule_Count_T :=
     (Track_M2 => 1,
      Track_M3 => 36,
      Track_M15 => 0,
      Track_M24 => 35,
      Track_M37 => 21,
      Track_M38 => 0,
      Track_M39 => 0,
      Train_M129 => 2,
      Train_M132 => 2,
      Train_M136 => 4,
      Train_M146 => 0,
      Train_M157 => 6,
      Train_M159 => 1);

   Rules : constant array (Rule_Index_T) of Rule_T :=
      --  Track_M2, message 2
     (1 => (63, 63, True, False, (True, True, True, True)),
      --  Track_M3, message 3
      2 => (15, 15, False, False, (True, True, True, True)),
      3 => (21, 21, True, False, (True, True, True, True)),
      4 => (27, 27, True, False, (True, True, True, True)),
      5 => (49, 49, True, False, (True, True, True, True)),
      6 => (80, 80, True, False, (True, True, True, True)),
      7 => (3, 3, True, False, (True, True, True, True)),
      8 => (5, 5, True, False, (True, True, True, True)),
      9 => (31, 31, True, False, (True, True, True, True)),
      10 => (32, 32, True, False, (True, True, True, True)),
      11 => (39, 39, True, False, (True, True, True, True)),
      12 => (40, 40, True, False, (True, True, True, True)),
      13 => (51, 51, True, False, (True, True, True, True)),
      14 => (41, 41, True, False, (True, True, True, True)),
      15 => (42, 42, True, False, (True, True, True, True)),
      16 => (44, 44, True, True, (True, True, True, True)),
      17 => (45, 45, True, False, (True, True, True, True)),
      18 => (52, 52, True, False, (True, True, True, True)),
      19 => (57, 57, True, False, (True, True, True, True)),
      20 => (58, 58, True, False, (True, True, True, True)),
      21 => (64, 64, True, False, (True, True, True, True)),
      22 => (65, 65, True, True, (True, True, True, True)),
      23 => (66, 66, True, True, (True, True, True, True)),
      24 => (67, 67, True, False, (True, True, True, True)),
      25 => (68, 68, True, False, (True, True, True, True)),
      26 => (69, 69, True, False, (True, True, True, True)),
      27 => (70, 70, True, False, (True, True, True, True)),
      28 => (71, 71, True, False, (True, True, True, True)),
      29 => (73, 73, True, False, (True, True, True, True)),
      30 => (74, 74, True, False, (True, True, True, True)),
      31 => (79, 79, True, False, (True, True, True, True)),
      32 => (88, 88, True, True, (True, True, True, True)),
      33 => (131, 131, True, False, (True, True, True, True)),
      34 => (138, 138, True, False, (True, True, True, True)),
      35 => (139, 139, True, False, (True, True, True, True)),
      36 => (140, 140, True, False, (True, True, True, True)),
      37 => (180, 180, True, False, (True, True, True, True)),
      --  Track_M24, message 24
      38 => (21, 21, True, False, (False, False, True, False)),
      39 => (27, 27, True, False, (False, False, True, False)),
      40 => (3, 3, True, False, (False, False, True, False)),
      41 => (5, 5, True, False, (False, False, True, False)),
      42 => (31, 31, True, False, (False, False, True, False)),
      43 => (32, 32, True, False, (False, False, True, False)),
      44 => (39, 39, True, False, (False, False, True, False)),
      45 => (40, 40, True, False, (False, False, True, False)),
      46 => (51, 51, True, False, (False, False, True, False)),
      47 => (41, 41, True, False, (False, False, True, False)),
      48 => (42, 42, True, False, (False, False, True, False)),
      49 => (44, 44, True, True, (True, True, True, True)),
      50 => (45, 45, True, False, (True, True, True, True)),
      51 => (52, 52, True, False, (False, False, True, False)),
      52 => (57, 57, True, False, (False, False, True, False)),
      53 => (58, 58, True, False, (False, False, True, False)),
      54 => (64, 64, True, False, (False, False, True, False)),
      55 => (65, 65, True, True, (False, False, True, False)),
      56 => (66, 66, True, True, (False, False, True, False)),
      57 => (67, 67, True, False, (False, False, True, False)),
      58 => (68, 68, True, False, (False, False, True, False)),
      59 => (69, 69, True, False, (False, False, True, False)),
      60 => (70, 70, True, False, (False, False, True, False)),
      61 => (71, 71, True, False, (False, False, True, False)),
      62 => (73, 73, True, False, (False, False, True, False)),
      63 => (74, 74, True, False, (False, False, True, False)),
      64 => (79, 79, True, False, (False, False, True, False)),
      65 => (88, 88, True, True, (False, False, True, False)),
      66 => (131, 131, True, False, (False, False, True, False)),
      67 => (138, 138, True, False, (False, False, True, False)),
      68 => (139, 139, True, False, (False, False, True, False)),
      69 => (140, 140, True, False, (False, False, True, False)),
      70 => (180, 180, True, False, (True, True, True, True)),
      71 => (143, 143, True, False, (False, False, False, True)),
      72 => (254, 254, True, False, (False, False, False, True)),
      --  Track_M37, message 37
      73 => (136, 136, False, False, (True, True, True, True)),
      74 => (12, 12, False, False, (True, True, True, True)),
      75 => (5, 5, True, False, (True, True, True, True)),
      76 => (21, 21, True, False, (True, True, True, True)),
      77 => (27, 27, True, False, (True, True, True, True)),
      78 => (39, 39, True, False, (True, True, True, True)),
      79 => (40, 40, True, False, (True, True, True, True)),
      80 => (41, 41, True, False, (True, True, True, True)),
      81 => (44, 44, True, True, (True, True, True, True)),
      82 => (49, 49, True, False, (True, True, True, True)),
      83 => (51, 51, True, False, (True, True, True, True)),
      84 => (52, 52, True, False, (True, True, True, True)),
      85 => (65, 65, True, True, (True, True, True, True)),
      86 => (68, 68, True, False, (True, True, True, True)),
      87 => (69, 69, True, False, (True, True, True, True)),
      88 => (70, 70, True, False, (True, True, True, True)),
      89 => (71, 71, True, False, (True, True, True, True)),
      90 => (80, 80, True, False, (True, True, True, True)),
      91 => (88, 88, True, True, (True, True, True, True)),
      92 => (138, 138, True, False, (True, True, True, True)),
      93 => (139, 139, True, False, (True, True, True, True)),
      --  Train_M129, message 129
      94 => (0, 1, False, False, (True, True, True, True)),
      95 => (11, 11, False, False, (True, True, True, True)),
      --  Train_M132, message 132
      96 => (0, 1, False, False, (True, True, True, True)),
      97 => (9, 9, True, False, (True, True, True, True)),
      --  Train_M136, message 136
      98 => (0, 1, False, False, (True, True, True, True)),
      99 => (4, 4, True, False, (True, True, True, True)),
      100 => (5, 5, True, False, (True, True, True, True)),
      101 => (44, 44, True, True, (True, True, True, True)),
      --  Train_M157, message 157
      102 => (0, 1, False, False, (True, True, True, True)),
      103 => (4, 4, True, False, (True, True, True, True)),
      104 => (5, 5, True, False, (True, True, True, True)),
      105 => (10, 10, True, False, (True, True, True, True)),
      106 => (11, 11, True, False, (True, True, True, True)),
      107 => (44, 44, True, True, (True, True, True, True)),
      --  Train_M159, message 159
      108 => (2, 2, False, False, (True, True, True, True)));

end ETCS_Message_Catalogue;
