--  ETCS on-board (EVC)
--  Packet 27, track to train: International Static Speed Profile.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.7. Sent by: Balise, Euroloop, RBC, RIU.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P27
  with SPARK_Mode => On
is

   NID : constant := 27;
   Name : constant String := "International Static Speed Profile";

   type Q_DIFF_Item_2 is record
      Q_DIFF        : Q_DIFF_T := 0;
      --  present when Q_DIFF == 0
      Has_NC_CDDIFF : Boolean := False;
      NC_CDDIFF     : NC_CDDIFF_T := 0;
      --  present when Q_DIFF in [1, 2]
      Has_NC_DIFF   : Boolean := False;
      NC_DIFF       : NC_DIFF_T := 0;
      V_DIFF        : V_DIFF_T := 0;
   end record;

   type Q_DIFF_Array_2 is array (1 .. 31) of Q_DIFF_Item_2;

   type Q_DIFF_Item is record
      Q_DIFF        : Q_DIFF_T := 0;
      --  present when Q_DIFF == 0
      Has_NC_CDDIFF : Boolean := False;
      NC_CDDIFF     : NC_CDDIFF_T := 0;
      --  present when Q_DIFF in [1, 2]
      Has_NC_DIFF   : Boolean := False;
      NC_DIFF       : NC_DIFF_T := 0;
      V_DIFF        : V_DIFF_T := 0;
   end record;

   type Q_DIFF_Array is array (1 .. 31) of Q_DIFF_Item;

   type D_STATIC_Item is record
      D_STATIC    : D_STATIC_T := 0;
      V_STATIC    : V_STATIC_T := 0;
      Q_FRONT     : Q_FRONT_T := 0;
      N_ITER      : N_ITER_T := 0;
      --  loop over N_ITER
      Q_DIFF_List : Q_DIFF_Array_2;
   end record;

   type D_STATIC_Array is array (1 .. 31) of D_STATIC_Item;

   type Packet_T is record
      NID_PACKET    : NID_PACKET_T := NID;
      Q_DIR         : Q_DIR_T := 0;
      L_PACKET      : L_PACKET_T := 0;
      Q_SCALE       : Q_SCALE_T := 0;
      D_STATIC      : D_STATIC_T := 0;
      V_STATIC      : V_STATIC_T := 0;
      Q_FRONT       : Q_FRONT_T := 0;
      N_ITER        : N_ITER_T := 0;
      --  loop over N_ITER
      Q_DIFF_List   : Q_DIFF_Array;
      N_ITER_2      : N_ITER_T := 0;
      --  loop over N_ITER
      D_STATIC_List : D_STATIC_Array;
   end record;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P27;
