--  ETCS on-board (EVC)
--  Packet 255, track to train: End of Information.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.39. Sent by: Balise, Euroloop.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet or on another NID_PACKET.
--  This packet has no L_PACKET (7.3.3.5).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P255
  with SPARK_Mode => On
is

   NID : constant := 255;
   Name : constant String := "End of Information";

   type Packet_T is record
      NID_PACKET : NID_PACKET_T := NID;
   end record;

   --  Every variable read holds a value of 7.5, not a spare one
   --  (Is_Valid of its type; SUBSET-026 3.16.1.1.1): those of the
   --  packet, of the conditional blocks present and of the items of
   --  its loops. Decode does not check it.
   function Valid (P : Packet_T) return Boolean;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P255;
