--  ETCS on-board (EVC)
--  The catalogue of the packets, SUBSET-026 7.4.1.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  NID_PACKET of each direction to its kind; the name, clause and
--  senders of every kind (7.4.1.1, 7.4.1.2, 7.3.3.10); a check
--  that decodes a packet of any kind and validates its values
--  (on the stack, the record is dropped); and Skip, which passes
--  over any packet with the standard header of 7.3.3.2 by its
--  L_PACKET, known or not.

with ETCS_Bits; use ETCS_Bits;

package ETCS_Catalogue
  with SPARK_Mode => On
is

   type Direction_T is (Track_To_Train, Train_To_Track);

   type Packet_Kind_T is
     (Unknown,
      Track_P0,
      Track_P2,
      Track_P3,
      Track_P5,
      Track_P6,
      Track_P12,
      Track_P13,
      Track_P15,
      Track_P16,
      Track_P21,
      Track_P27,
      Track_P31,
      Track_P32,
      Track_P39,
      Track_P40,
      Track_P41,
      Track_P42,
      Track_P44,
      Track_P45,
      Track_P46,
      Track_P49,
      Track_P51,
      Track_P52,
      Track_P57,
      Track_P58,
      Track_P63,
      Track_P64,
      Track_P65,
      Track_P66,
      Track_P67,
      Track_P68,
      Track_P69,
      Track_P70,
      Track_P71,
      Track_P73,
      Track_P74,
      Track_P79,
      Track_P80,
      Track_P88,
      Track_P90,
      Track_P131,
      Track_P132,
      Track_P133,
      Track_P134,
      Track_P135,
      Track_P136,
      Track_P137,
      Track_P138,
      Track_P139,
      Track_P140,
      Track_P141,
      Track_P143,
      Track_P145,
      Track_P180,
      Track_P181,
      Track_P254,
      Track_P255,
      Train_P0,
      Train_P1,
      Train_P2,
      Train_P4,
      Train_P5,
      Train_P9,
      Train_P10,
      Train_P11,
      Train_P12,
      Train_P44);

   subtype Known_Kind_T is Packet_Kind_T
     range Track_P0 .. Train_P44;

   --  The kind of packet NID_PACKET = NID in this direction
   function Kind (Direction : Direction_T; NID : Natural)
     return Packet_Kind_T;

   NID_Of : constant array (Known_Kind_T) of Natural :=
     (Track_P0 => 0,
      Track_P2 => 2,
      Track_P3 => 3,
      Track_P5 => 5,
      Track_P6 => 6,
      Track_P12 => 12,
      Track_P13 => 13,
      Track_P15 => 15,
      Track_P16 => 16,
      Track_P21 => 21,
      Track_P27 => 27,
      Track_P31 => 31,
      Track_P32 => 32,
      Track_P39 => 39,
      Track_P40 => 40,
      Track_P41 => 41,
      Track_P42 => 42,
      Track_P44 => 44,
      Track_P45 => 45,
      Track_P46 => 46,
      Track_P49 => 49,
      Track_P51 => 51,
      Track_P52 => 52,
      Track_P57 => 57,
      Track_P58 => 58,
      Track_P63 => 63,
      Track_P64 => 64,
      Track_P65 => 65,
      Track_P66 => 66,
      Track_P67 => 67,
      Track_P68 => 68,
      Track_P69 => 69,
      Track_P70 => 70,
      Track_P71 => 71,
      Track_P73 => 73,
      Track_P74 => 74,
      Track_P79 => 79,
      Track_P80 => 80,
      Track_P88 => 88,
      Track_P90 => 90,
      Track_P131 => 131,
      Track_P132 => 132,
      Track_P133 => 133,
      Track_P134 => 134,
      Track_P135 => 135,
      Track_P136 => 136,
      Track_P137 => 137,
      Track_P138 => 138,
      Track_P139 => 139,
      Track_P140 => 140,
      Track_P141 => 141,
      Track_P143 => 143,
      Track_P145 => 145,
      Track_P180 => 180,
      Track_P181 => 181,
      Track_P254 => 254,
      Track_P255 => 255,
      Train_P0 => 0,
      Train_P1 => 1,
      Train_P2 => 2,
      Train_P4 => 4,
      Train_P5 => 5,
      Train_P9 => 9,
      Train_P10 => 10,
      Train_P11 => 11,
      Train_P12 => 12,
      Train_P44 => 44);

   Direction_Of : constant array (Known_Kind_T) of Direction_T :=
     (Track_P0 => Track_To_Train,
      Track_P2 => Track_To_Train,
      Track_P3 => Track_To_Train,
      Track_P5 => Track_To_Train,
      Track_P6 => Track_To_Train,
      Track_P12 => Track_To_Train,
      Track_P13 => Track_To_Train,
      Track_P15 => Track_To_Train,
      Track_P16 => Track_To_Train,
      Track_P21 => Track_To_Train,
      Track_P27 => Track_To_Train,
      Track_P31 => Track_To_Train,
      Track_P32 => Track_To_Train,
      Track_P39 => Track_To_Train,
      Track_P40 => Track_To_Train,
      Track_P41 => Track_To_Train,
      Track_P42 => Track_To_Train,
      Track_P44 => Track_To_Train,
      Track_P45 => Track_To_Train,
      Track_P46 => Track_To_Train,
      Track_P49 => Track_To_Train,
      Track_P51 => Track_To_Train,
      Track_P52 => Track_To_Train,
      Track_P57 => Track_To_Train,
      Track_P58 => Track_To_Train,
      Track_P63 => Track_To_Train,
      Track_P64 => Track_To_Train,
      Track_P65 => Track_To_Train,
      Track_P66 => Track_To_Train,
      Track_P67 => Track_To_Train,
      Track_P68 => Track_To_Train,
      Track_P69 => Track_To_Train,
      Track_P70 => Track_To_Train,
      Track_P71 => Track_To_Train,
      Track_P73 => Track_To_Train,
      Track_P74 => Track_To_Train,
      Track_P79 => Track_To_Train,
      Track_P80 => Track_To_Train,
      Track_P88 => Track_To_Train,
      Track_P90 => Track_To_Train,
      Track_P131 => Track_To_Train,
      Track_P132 => Track_To_Train,
      Track_P133 => Track_To_Train,
      Track_P134 => Track_To_Train,
      Track_P135 => Track_To_Train,
      Track_P136 => Track_To_Train,
      Track_P137 => Track_To_Train,
      Track_P138 => Track_To_Train,
      Track_P139 => Track_To_Train,
      Track_P140 => Track_To_Train,
      Track_P141 => Track_To_Train,
      Track_P143 => Track_To_Train,
      Track_P145 => Track_To_Train,
      Track_P180 => Track_To_Train,
      Track_P181 => Track_To_Train,
      Track_P254 => Track_To_Train,
      Track_P255 => Track_To_Train,
      Train_P0 => Train_To_Track,
      Train_P1 => Train_To_Track,
      Train_P2 => Train_To_Track,
      Train_P4 => Train_To_Track,
      Train_P5 => Train_To_Track,
      Train_P9 => Train_To_Track,
      Train_P10 => Train_To_Track,
      Train_P11 => Train_To_Track,
      Train_P12 => Train_To_Track,
      Train_P44 => Train_To_Track);

   --  The packet starts with NID_PACKET, (Q_DIR,) L_PACKET
   Has_Length : constant array (Known_Kind_T) of Boolean :=
     (Track_P0 => False,
      Track_P2 => True,
      Track_P3 => True,
      Track_P5 => True,
      Track_P6 => True,
      Track_P12 => True,
      Track_P13 => True,
      Track_P15 => True,
      Track_P16 => True,
      Track_P21 => True,
      Track_P27 => True,
      Track_P31 => True,
      Track_P32 => True,
      Track_P39 => True,
      Track_P40 => True,
      Track_P41 => True,
      Track_P42 => True,
      Track_P44 => True,
      Track_P45 => True,
      Track_P46 => True,
      Track_P49 => True,
      Track_P51 => True,
      Track_P52 => True,
      Track_P57 => True,
      Track_P58 => True,
      Track_P63 => True,
      Track_P64 => True,
      Track_P65 => True,
      Track_P66 => True,
      Track_P67 => True,
      Track_P68 => True,
      Track_P69 => True,
      Track_P70 => True,
      Track_P71 => True,
      Track_P73 => True,
      Track_P74 => True,
      Track_P79 => True,
      Track_P80 => True,
      Track_P88 => True,
      Track_P90 => True,
      Track_P131 => True,
      Track_P132 => True,
      Track_P133 => True,
      Track_P134 => True,
      Track_P135 => True,
      Track_P136 => True,
      Track_P137 => True,
      Track_P138 => True,
      Track_P139 => True,
      Track_P140 => True,
      Track_P141 => True,
      Track_P143 => True,
      Track_P145 => True,
      Track_P180 => True,
      Track_P181 => True,
      Track_P254 => True,
      Track_P255 => False,
      Train_P0 => True,
      Train_P1 => True,
      Train_P2 => True,
      Train_P4 => True,
      Train_P5 => True,
      Train_P9 => True,
      Train_P10 => True,
      Train_P11 => True,
      Train_P12 => True,
      Train_P44 => True);

   --  Bits of the standard header: NID_PACKET, Q_DIR (track to
   --  train only), L_PACKET
   Header_Bits : constant array (Direction_T) of Natural :=
     (Track_To_Train => 23, Train_To_Track => 21);

   --  The ERTMS/ETCS trackside devices of 7.3.3.10
   type Sender_T is (Balise, Euroloop, RBC, RIU);
   type Senders_T is array (Sender_T) of Boolean;

   function Sent_By (Kind : Known_Kind_T) return Senders_T;

   function Name (Kind : Known_Kind_T) return String;

   --  The clause of SUBSET-026 that defines the packet
   function Clause (Kind : Known_Kind_T) return String;

   --  Decode the packet of this kind at the position of R into a
   --  record on the stack, and drop it: OK when it decodes (see the
   --  Decode of its package), Valid when it decodes and every
   --  variable holds a value of 7.5, not a spare one (the Valid of
   --  its package, SUBSET-026 3.16.1.1.1)
   procedure Check (Kind  : Known_Kind_T;
                    R     : in out Reader;
                    OK    : out Boolean;
                    Valid : out Boolean)
     with Post => (if OK then not Failed (R))
                  and then (if Valid then OK);

   --  Pass over the packet at the position of R by its L_PACKET:
   --  OK when its header is complete, L_PACKET is at least the
   --  header and the packet is within the limit of R
   procedure Skip (Direction : Direction_T;
                   R         : in out Reader;
                   OK        : out Boolean)
     with Post => (if OK then not Failed (R));

end ETCS_Catalogue;
