--  ETCS on-board (EVC)
--  The train to track packets of the ERTMS/ETCS language.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.3. One child package per packet, P<NID_PACKET>:
--     P0 Position Report (7.4.3.1)
--     P1 Position Report based on two balise groups (7.4.3.2)
--     P2 Onboard supported system versions (7.4.3.3)
--     P4 Error reporting (7.4.3.4)
--     P5 Train running number (7.4.3.4.1)
--     P9 Level 2 transition information (7.4.3.4.2)
--     P10 Safe consist length information for Supervised Manoeuvre (7.4.3.4.3)
--     P11 Validated train data (7.4.3.5)
--     P12 Default train data for Supervised Manoeuvre (7.4.3.5.1)
--     P44 Data used by applications outside the ERTMS/ETCS system (7.4.3.6)

package ETCS_Train_Packets
  with SPARK_Mode => On, Pure
is
end ETCS_Train_Packets;
