--  ETCS on-board (EVC)
--  Packet 42, track to train: Session Management for RBC interfaced to GSM-R,
--  implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P42
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET     : NID_PACKET_T;
      Q_DIR          : Q_DIR_T;
      L_PACKET       : L_PACKET_T;
      Q_RBC          : Q_RBC_T;
      NID_C          : NID_C_T;
      NID_RBC        : NID_RBC_T;
      NID_RADIO      : NID_RADIO_T;
      Q_SLEEPSESSION : Q_SLEEPSESSION_T;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 1, V);
      Q_RBC := To_Q_RBC (V);
      Read (R, 10, V);
      NID_C := To_NID_C (V);
      Read (R, 14, V);
      NID_RBC := To_NID_RBC (V);
      Read (R, 64, V);
      NID_RADIO := To_NID_RADIO (V);
      Read (R, 1, V);
      Q_SLEEPSESSION := To_Q_SLEEPSESSION (V);
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_RBC => Q_RBC,
         NID_C => NID_C,
         NID_RBC => NID_RBC,
         NID_RADIO => NID_RADIO,
         Q_SLEEPSESSION => Q_SLEEPSESSION);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 1, Code (P.Q_RBC));
      Write (W, 10, Code (P.NID_C));
      Write (W, 14, Code (P.NID_RBC));
      Write (W, 64, Code (P.NID_RADIO));
      Write (W, 1, Code (P.Q_SLEEPSESSION));
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P42;
