--  ETCS on-board (EVC)
--  Packet 44, track to train: Data used by applications outside the ERTMS/ETCS
--  system, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P44
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.NID_XUSER)
      and then (if P.Has_NID_NTC then Is_Valid (P.NID_NTC)));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      Bad   : Boolean := False;
      NID_PACKET  : NID_PACKET_T;
      Q_DIR       : Q_DIR_T;
      L_PACKET    : L_PACKET_T;
      NID_XUSER   : NID_XUSER_T;
      Has_NID_NTC : Boolean;
      NID_NTC     : NID_NTC_T := 0;
      Raw_Bits    : Raw_Bits_T := 0;
      Raw         : Raw_Data_T := (others => 0);
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 9, V);
      NID_XUSER := To_NID_XUSER (V);
      Has_NID_NTC := NID_XUSER = 102;
      if Has_NID_NTC then
         Read (R, 8, V);
         NID_NTC := To_NID_NTC (V);
      end if;
      if Position (R) <= Start + Natural (L_PACKET)
        and then Start + Natural (L_PACKET) - Position (R) <= 8191
      then
         Raw_Bits := Start + Natural (L_PACKET) - Position (R);
         Read_Bytes (R, Raw_Bits, Raw);
      else
         Bad := True;
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         NID_XUSER => NID_XUSER,
         Has_NID_NTC => Has_NID_NTC,
         NID_NTC => NID_NTC,
         Raw_Bits => Raw_Bits,
         Raw => Raw);
      OK := not Failed (R)
        and then not Bad
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 9, Code (P.NID_XUSER));
      if P.Has_NID_NTC /= (P.NID_XUSER = 102) then
         Good := False;
      end if;
      if P.NID_XUSER = 102 then
         Write (W, 8, Code (P.NID_NTC));
      end if;
      Write_Bytes (W, P.Raw_Bits, P.Raw);
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P44;
