--  ETCS on-board (EVC)
--  Packet 2, track to train: System Version order, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P2
  with SPARK_Mode => On
is

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
   begin
      P := (others => <>);
      Read (R, 8, V);
      P.NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      P.Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      P.L_PACKET := To_L_PACKET (V);
      Read (R, 7, V);
      P.M_VERSION := To_M_VERSION (V);
      OK := not Failed (R)
        and then P.NID_PACKET = NID
        and then Position (R) = Start + Natural (P.L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 7, Code (P.M_VERSION));
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P2;
