--  ETCS on-board (EVC)
--  Packet 5, train to track: Train running number, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Train_Packets.P5
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.NID_OPERATIONAL));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET      : NID_PACKET_T;
      L_PACKET        : L_PACKET_T;
      NID_OPERATIONAL : NID_OPERATIONAL_T;
   begin
      Decode_Header (R, NID_PACKET, L_PACKET);
      Read (R, 32, V);
      NID_OPERATIONAL := To_NID_OPERATIONAL (V);
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         NID_OPERATIONAL => NID_OPERATIONAL);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Length_At);
      Write (W, 32, Code (P.NID_OPERATIONAL));
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P5;
