--  ETCS on-board (EVC)
--  Packet 2, train to track: Onboard supported system versions,
--  implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Train_Packets.P2
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.M_VERSION)
      and then Is_Valid (P.N_ITER)
      and then (for all I1 in 1 .. Natural (P.N_ITER) =>
                  Is_Valid (P.M_VERSION_List (I1))));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET     : NID_PACKET_T;
      L_PACKET       : L_PACKET_T;
      M_VERSION      : M_VERSION_T;
      N_ITER         : N_ITER_T;
      M_VERSION_List : M_VERSION_Array := (others => 0);
   begin
      Decode_Header (R, NID_PACKET, L_PACKET);
      Read (R, 7, V);
      M_VERSION := To_M_VERSION (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Read (R, 7, V);
         M_VERSION_List (I1) := To_M_VERSION (V);
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         M_VERSION => M_VERSION,
         N_ITER => N_ITER,
         M_VERSION_List => M_VERSION_List);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Length_At);
      Write (W, 7, Code (P.M_VERSION));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Write (W, 7, Code (P.M_VERSION_List (I1)));
      end loop;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P2;
