--  ETCS on-board (EVC)
--  Packet 40, track to train: Track Condition Change of allowed current
--  consumption.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.8.1. Sent by: Balise, Euroloop, RBC, RIU.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P40
  with SPARK_Mode => On
is

   NID : constant := 40;
   Name : constant String :=
     "Track Condition Change of allowed current consumption";

   type Packet_T is record
      NID_PACKET : NID_PACKET_T := NID;
      Q_DIR      : Q_DIR_T := 0;
      L_PACKET   : L_PACKET_T := 0;
      Q_SCALE    : Q_SCALE_T := 0;
      D_CURRENT  : D_CURRENT_T := 0;
      M_CURRENT  : M_CURRENT_T := 0;
   end record;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P40;
