--  ETCS on-board (EVC)
--  Packet 67, track to train: Track Condition Big Metal Masses,
--  implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Track_Packets.P67
  with SPARK_Mode => On
is

   --  One item of D_TRACKCOND_List
   procedure Decode_D_TRACKCOND_Item
     (R  : in out Reader;
      E1 : out D_TRACKCOND_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      Read (R, 15, V);
      E1.D_TRACKCOND := To_D_TRACKCOND (V);
      Read (R, 15, V);
      E1.L_TRACKCOND := To_L_TRACKCOND (V);
   end Decode_D_TRACKCOND_Item;

   --  One item of D_TRACKCOND_List
   procedure Encode_D_TRACKCOND_Item
     (E1 : D_TRACKCOND_Item;
      W  : in out Writer)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 15, Code (E1.D_TRACKCOND));
      Write (W, 15, Code (E1.L_TRACKCOND));
   end Encode_D_TRACKCOND_Item;

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET       : NID_PACKET_T;
      Q_DIR            : Q_DIR_T;
      L_PACKET         : L_PACKET_T;
      Q_SCALE          : Q_SCALE_T;
      D_TRACKCOND      : D_TRACKCOND_T;
      L_TRACKCOND      : L_TRACKCOND_T;
      N_ITER           : N_ITER_T;
      D_TRACKCOND_List : D_TRACKCOND_Array;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 2, V);
      Q_DIR := To_Q_DIR (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 15, V);
      D_TRACKCOND := To_D_TRACKCOND (V);
      Read (R, 15, V);
      L_TRACKCOND := To_L_TRACKCOND (V);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_D_TRACKCOND_Item (R, D_TRACKCOND_List (I1));
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         D_TRACKCOND => D_TRACKCOND,
         L_TRACKCOND => L_TRACKCOND,
         N_ITER => N_ITER,
         D_TRACKCOND_List => D_TRACKCOND_List);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Write (W, 2, Code (P.Q_DIR));
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 15, Code (P.D_TRACKCOND));
      Write (W, 15, Code (P.L_TRACKCOND));
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_D_TRACKCOND_Item (P.D_TRACKCOND_List (I1), W);
      end loop;
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P67;
