--  ETCS on-board (EVC)
--  Packet 46, track to train: Conditional Level Transition Order.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.11.2. Sent by: Balise.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

--  ETCS_Bits, ETCS_Variables and Interfaces are withed and used
--  by the parent package, which makes them visible here.

pragma Unevaluated_Use_Of_Old (Allow);

package ETCS_Track_Packets.P46
  with SPARK_Mode => On
is

   NID : constant := 46;
   Name : constant String := "Conditional Level Transition Order";

   type M_LEVELTR_Item is record
      M_LEVELTR   : M_LEVELTR_T := 0;
      --  present when M_LEVELTR == 1
      Has_NID_NTC : Boolean := False;
      NID_NTC     : NID_NTC_T := 0;
   end record;

   type M_LEVELTR_Array is array (1 .. 31) of M_LEVELTR_Item;

   type Packet_T is record
      NID_PACKET     : NID_PACKET_T := NID;
      Q_DIR          : Q_DIR_T := 0;
      L_PACKET       : L_PACKET_T := 0;
      M_LEVELTR      : M_LEVELTR_T := 0;
      --  present when M_LEVELTR == 1
      Has_NID_NTC    : Boolean := False;
      NID_NTC        : NID_NTC_T := 0;
      N_ITER         : N_ITER_T := 0;
      --  loop over N_ITER
      M_LEVELTR_List : M_LEVELTR_Array;
   end record;

   --  Every variable read holds a value of 7.5, not a spare one
   --  (Is_Valid of its type; SUBSET-026 3.16.1.1.1): those of the
   --  packet, of the conditional blocks present and of the items of
   --  its loops. Decode does not check it.
   function Valid (P : Packet_T) return Boolean;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P46;
