--  ETCS on-board (EVC)
--  Packet 4, train to track: Error reporting, implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

with Interfaces; use Interfaces;

package body ETCS_Train_Packets.P4
  with SPARK_Mode => On
is

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.M_ERROR));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Natural := Position (R);
      V     : Unsigned_64;
      NID_PACKET : NID_PACKET_T;
      L_PACKET   : L_PACKET_T;
      M_ERROR    : M_ERROR_T;
   begin
      Read (R, 8, V);
      NID_PACKET := To_NID_PACKET (V);
      Read (R, 13, V);
      L_PACKET := To_L_PACKET (V);
      Read (R, 8, V);
      M_ERROR := To_M_ERROR (V);
      P :=
        (NID_PACKET => NID_PACKET,
         L_PACKET => L_PACKET,
         M_ERROR => M_ERROR);
      OK := not Failed (R)
        and then NID_PACKET = NID
        and then Position (R) = Start + Natural (L_PACKET);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Natural := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Write (W, 8, NID);
      Length_At := Position (W);
      Write (W, 13, 0);
      Write (W, 8, Code (P.M_ERROR));
      --  L_PACKET: the bits written
      if Position (W) >= Start
        and then Position (W) - Start <= 8191
      then
         Patch (W, Length_At, 13, Unsigned_64 (Position (W) - Start));
      else
         Good := False;
      end if;
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Train_Packets.P4;
