--  ETCS on-board (EVC)
--  Packet 52, track to train: Permitted Braking Distance Information,
--  implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Track_Packets.P52
  with SPARK_Mode => On
is

   --  One item of D_PBD_List
   procedure Decode_D_PBD_Item
     (R  : in out Reader;
      E1 : out D_PBD_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      Read (R, 15, V);
      E1.D_PBD := To_D_PBD (V);
      Read (R, 1, V);
      E1.Q_GDIR := To_Q_GDIR (V);
      Read (R, 8, V);
      E1.G_PBDSR := To_G_PBDSR (V);
      Read (R, 1, V);
      E1.Q_PBDSR := To_Q_PBDSR (V);
      Read (R, 15, V);
      E1.D_PBDSR := To_D_PBDSR (V);
      Read (R, 15, V);
      E1.L_PBDSR := To_L_PBDSR (V);
   end Decode_D_PBD_Item;

   --  One item of D_PBD_List
   procedure Encode_D_PBD_Item
     (E1 : D_PBD_Item;
      W  : in out Writer)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 15, Code (E1.D_PBD));
      Write (W, 1, Code (E1.Q_GDIR));
      Write (W, 8, Code (E1.G_PBDSR));
      Write (W, 1, Code (E1.Q_PBDSR));
      Write (W, 15, Code (E1.D_PBDSR));
      Write (W, 15, Code (E1.L_PBDSR));
   end Encode_D_PBD_Item;

   --  Valid of one item of D_PBD_List
   function Valid_D_PBD_Item (E1 : D_PBD_Item) return Boolean is
     (Is_Valid (E1.D_PBD)
      and then Is_Valid (E1.Q_GDIR)
      and then Is_Valid (E1.G_PBDSR)
      and then Is_Valid (E1.Q_PBDSR)
      and then Is_Valid (E1.D_PBDSR)
      and then Is_Valid (E1.L_PBDSR));

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.Q_SCALE)
      and then Is_Valid (P.Q_TRACKINIT)
      and then (if P.Has_D_TRACKINIT then Is_Valid (P.D_TRACKINIT))
      and then (if P.Has_D_PBD
                then Is_Valid (P.D_PBD)
                     and then Is_Valid (P.Q_GDIR)
                     and then Is_Valid (P.G_PBDSR)
                     and then Is_Valid (P.Q_PBDSR)
                     and then Is_Valid (P.D_PBDSR)
                     and then Is_Valid (P.L_PBDSR)
                     and then Is_Valid (P.N_ITER)
                     and then (for all I1 in 1 .. Natural (P.N_ITER) =>
                                 Valid_D_PBD_Item (P.D_PBD_List (I1)))));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET      : NID_PACKET_T;
      Q_DIR           : Q_DIR_T;
      L_PACKET        : L_PACKET_T;
      Q_SCALE         : Q_SCALE_T;
      Q_TRACKINIT     : Q_TRACKINIT_T;
      Has_D_TRACKINIT : Boolean;
      D_TRACKINIT     : D_TRACKINIT_T := 0;
      Has_D_PBD       : Boolean;
      D_PBD           : D_PBD_T := 0;
      Q_GDIR          : Q_GDIR_T := 0;
      G_PBDSR         : G_PBDSR_T := 0;
      Q_PBDSR         : Q_PBDSR_T := 0;
      D_PBDSR         : D_PBDSR_T := 0;
      L_PBDSR         : L_PBDSR_T := 0;
      N_ITER          : N_ITER_T := 0;
      D_PBD_List      : D_PBD_Array;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 2, V);
      Q_SCALE := To_Q_SCALE (V);
      Read (R, 1, V);
      Q_TRACKINIT := To_Q_TRACKINIT (V);
      Has_D_TRACKINIT := Q_TRACKINIT = 1;
      if Has_D_TRACKINIT then
         Read (R, 15, V);
         D_TRACKINIT := To_D_TRACKINIT (V);
      end if;
      Has_D_PBD := Q_TRACKINIT = 0;
      if Has_D_PBD then
         Read (R, 15, V);
         D_PBD := To_D_PBD (V);
         Read (R, 1, V);
         Q_GDIR := To_Q_GDIR (V);
         Read (R, 8, V);
         G_PBDSR := To_G_PBDSR (V);
         Read (R, 1, V);
         Q_PBDSR := To_Q_PBDSR (V);
         Read (R, 15, V);
         D_PBDSR := To_D_PBDSR (V);
         Read (R, 15, V);
         L_PBDSR := To_L_PBDSR (V);
         Read (R, 5, V);
         N_ITER := To_N_ITER (V);
         for I1 in 1 .. Natural (N_ITER) loop
            Decode_D_PBD_Item (R, D_PBD_List (I1));
         end loop;
      end if;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         Q_SCALE => Q_SCALE,
         Q_TRACKINIT => Q_TRACKINIT,
         Has_D_TRACKINIT => Has_D_TRACKINIT,
         D_TRACKINIT => D_TRACKINIT,
         Has_D_PBD => Has_D_PBD,
         D_PBD => D_PBD,
         Q_GDIR => Q_GDIR,
         G_PBDSR => G_PBDSR,
         Q_PBDSR => Q_PBDSR,
         D_PBDSR => D_PBDSR,
         L_PBDSR => L_PBDSR,
         N_ITER => N_ITER,
         D_PBD_List => D_PBD_List);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 2, Code (P.Q_SCALE));
      Write (W, 1, Code (P.Q_TRACKINIT));
      if P.Has_D_TRACKINIT /= (P.Q_TRACKINIT = 1) then
         Good := False;
      end if;
      if P.Q_TRACKINIT = 1 then
         Write (W, 15, Code (P.D_TRACKINIT));
      end if;
      if P.Has_D_PBD /= (P.Q_TRACKINIT = 0) then
         Good := False;
      end if;
      if P.Q_TRACKINIT = 0 then
         Write (W, 15, Code (P.D_PBD));
         Write (W, 1, Code (P.Q_GDIR));
         Write (W, 8, Code (P.G_PBDSR));
         Write (W, 1, Code (P.Q_PBDSR));
         Write (W, 15, Code (P.D_PBDSR));
         Write (W, 15, Code (P.L_PBDSR));
         Write (W, 5, Code (P.N_ITER));
         for I1 in 1 .. Natural (P.N_ITER) loop
            Encode_D_PBD_Item (P.D_PBD_List (I1), W);
         end loop;
      end if;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P52;
