--  ETCS on-board (EVC)
--  Packet 13, track to train: Staff Responsible distance Information from
--  loop.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).
--
--  SUBSET-026 7.4.2.3.1. Sent by: Euroloop.
--
--  Decode reads the packet at the position of the reader; it fails
--  (OK False) on a truncated packet, on another NID_PACKET, or
--  when the bits read are not L_PACKET, and consumes exactly
--  L_PACKET bits when it succeeds. Encode writes the packet with
--  the L_PACKET of what it wrote (the component is ignored).
--  Encode fails when a Has_ flag does not match its condition, a
--  count is above its maximum or the writer is full.

pragma Unevaluated_Use_Of_Old (Allow);

with ETCS_Bits;      use ETCS_Bits;
with ETCS_Variables; use ETCS_Variables;

package ETCS_Track_Packets.P13
  with SPARK_Mode => On
is

   NID : constant := 13;
   Name : constant String :=
     "Staff Responsible distance Information from loop";

   type Q_NEWCOUNTRY_Item is record
      Q_NEWCOUNTRY : Q_NEWCOUNTRY_T := 0;
      --  present when Q_NEWCOUNTRY == 1
      Has_NID_C    : Boolean := False;
      NID_C        : NID_C_T := 0;
      NID_BG       : NID_BG_T := 0;
      D_SR         : D_SR_T := 0;
   end record;

   type Q_NEWCOUNTRY_Array is array (1 .. 31) of Q_NEWCOUNTRY_Item;

   type Packet_T is record
      NID_PACKET        : NID_PACKET_T := NID;
      Q_DIR             : Q_DIR_T := 0;
      L_PACKET          : L_PACKET_T := 0;
      Q_SCALE           : Q_SCALE_T := 0;
      Q_NEWCOUNTRY      : Q_NEWCOUNTRY_T := 0;
      --  present when Q_NEWCOUNTRY == 1
      Has_NID_C         : Boolean := False;
      NID_C             : NID_C_T := 0;
      NID_BG            : NID_BG_T := 0;
      Q_NEWCOUNTRY_2    : Q_NEWCOUNTRY_T := 0;
      --  present when Q_NEWCOUNTRY == 1
      Has_NID_C_2       : Boolean := False;
      NID_C_2           : NID_C_T := 0;
      NID_BG_2          : NID_BG_T := 0;
      D_SR              : D_SR_T := 0;
      N_ITER            : N_ITER_T := 0;
      --  loop over N_ITER
      Q_NEWCOUNTRY_List : Q_NEWCOUNTRY_Array;
   end record;

   --  Every variable read holds a value of 7.5, not a spare one
   --  (Is_Valid of its type; SUBSET-026 3.16.1.1.1): those of the
   --  packet, of the conditional blocks present and of the items of
   --  its loops. Decode does not check it.
   function Valid (P : Packet_T) return Boolean;

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
     with Post => (if OK then not Failed (R)
                     and then Position (R) =
                       Position (R)'Old + Natural (P.L_PACKET));

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
     with Post => (if OK then not Failed (W));

end ETCS_Track_Packets.P13;
