--  ETCS on-board (EVC)
--  Packet 49, track to train: List of Balise Groups for SH Area,
--  implementation.
--
--  GENERATED by evc/language/gen_language.py from
--  evc/language/etcs_language.toml. Do not edit: change the TOML and run
--  python3 evc/language/gen_language.py (--check verifies).

package body ETCS_Track_Packets.P49
  with SPARK_Mode => On
is

   --  The items with every component at its default
   Empty_Q_NEWCOUNTRY_Item : constant Q_NEWCOUNTRY_Item := (others => <>);

   --  One item of Q_NEWCOUNTRY_List
   procedure Decode_Q_NEWCOUNTRY_Item
     (R  : in out Reader;
      E1 : out Q_NEWCOUNTRY_Item)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
      V : Unsigned_64;
   begin
      E1 := Empty_Q_NEWCOUNTRY_Item;
      Read (R, 1, V);
      E1.Q_NEWCOUNTRY := To_Q_NEWCOUNTRY (V);
      E1.Has_NID_C := E1.Q_NEWCOUNTRY = 1;
      if E1.Has_NID_C then
         Read (R, 10, V);
         E1.NID_C := To_NID_C (V);
      end if;
      Read (R, 14, V);
      E1.NID_BG := To_NID_BG (V);
   end Decode_Q_NEWCOUNTRY_Item;

   --  One item of Q_NEWCOUNTRY_List
   procedure Encode_Q_NEWCOUNTRY_Item
     (E1   : Q_NEWCOUNTRY_Item;
      W    : in out Writer;
      Good : in out Boolean)
     --  a contract, so that it is proved once, not inlined
     with Post => True
   is
   begin
      Write (W, 1, Code (E1.Q_NEWCOUNTRY));
      if E1.Has_NID_C /= (E1.Q_NEWCOUNTRY = 1) then
         Good := False;
      end if;
      if E1.Q_NEWCOUNTRY = 1 then
         Write (W, 10, Code (E1.NID_C));
      end if;
      Write (W, 14, Code (E1.NID_BG));
   end Encode_Q_NEWCOUNTRY_Item;

   --  Valid of one item of Q_NEWCOUNTRY_List
   function Valid_Q_NEWCOUNTRY_Item (E1 : Q_NEWCOUNTRY_Item) return Boolean is
     (Is_Valid (E1.Q_NEWCOUNTRY)
      and then (if E1.Has_NID_C then Is_Valid (E1.NID_C))
      and then Is_Valid (E1.NID_BG));

   -----------
   -- Valid --
   -----------

   function Valid (P : Packet_T) return Boolean is
     (Is_Valid (P.NID_PACKET)
      and then Is_Valid (P.Q_DIR)
      and then Is_Valid (P.L_PACKET)
      and then Is_Valid (P.N_ITER)
      and then (for all I1 in 1 .. Natural (P.N_ITER) =>
                  Valid_Q_NEWCOUNTRY_Item (P.Q_NEWCOUNTRY_List (I1))));

   ------------
   -- Decode --
   ------------

   procedure Decode (R  : in out Reader;
                     P  : out Packet_T;
                     OK : out Boolean)
   is
      Start : constant Bit_Count := Position (R);
      V     : Unsigned_64;
      NID_PACKET        : NID_PACKET_T;
      Q_DIR             : Q_DIR_T;
      L_PACKET          : L_PACKET_T;
      N_ITER            : N_ITER_T;
      Q_NEWCOUNTRY_List : Q_NEWCOUNTRY_Array;
   begin
      Decode_Header (R, NID_PACKET, Q_DIR, L_PACKET);
      Read (R, 5, V);
      N_ITER := To_N_ITER (V);
      for I1 in 1 .. Natural (N_ITER) loop
         Decode_Q_NEWCOUNTRY_Item (R, Q_NEWCOUNTRY_List (I1));
      end loop;
      P :=
        (NID_PACKET => NID_PACKET,
         Q_DIR => Q_DIR,
         L_PACKET => L_PACKET,
         N_ITER => N_ITER,
         Q_NEWCOUNTRY_List => Q_NEWCOUNTRY_List);
      OK := Header_OK (R, NID_PACKET, NID, L_PACKET, Start);
   end Decode;

   ------------
   -- Encode --
   ------------

   procedure Encode (P  : Packet_T;
                     W  : in out Writer;
                     OK : out Boolean)
   is
      Start     : constant Bit_Count := Position (W);
      Length_At : Natural;
      Good      : Boolean := True;
   begin
      Encode_Header (W, NID, Code (P.Q_DIR), Length_At);
      Write (W, 5, Code (P.N_ITER));
      for I1 in 1 .. Natural (P.N_ITER) loop
         Encode_Q_NEWCOUNTRY_Item (P.Q_NEWCOUNTRY_List (I1), W, Good);
      end loop;
      Finish_Length (W, Start, Length_At, Good);
      OK := Good and then not Failed (W);
   end Encode;

end ETCS_Track_Packets.P49;
